repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        exclude: |
          (?x)^(
              src/funcs/*|
              src/lib/*|
              src/models/*|
              src/sdk/*|
              src/hooks/hooks.ts|
              src/hooks/index.ts|
              src/hooks/oauth2password.ts|
              src/hooks/types.ts|
              src/types/*
          )$
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
