/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d2e0a0845caf
 */

import { healthHealthcheckHealthcheckGet } from "../funcs/healthHealthcheckHealthcheckGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Health extends ClientSDK {
  /**
   * Healthcheck
   */
  async healthcheckHealthcheckGet(
    options?: RequestOptions,
  ): Promise<models.HealthcheckResponse> {
    return unwrapAsync(healthHealthcheckHealthcheckGet(
      this,
      options,
    ));
  }
}
