/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4eded93c65cc
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ComputeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostSecurity =
  {
    apiKeyHeader?: string | undefined;
    classicAPIKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type ComputeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostRequest =
  {
    projectId: string;
    runId: string;
    body: models.ComputeHealthScoreRequest;
  };

/** @internal */
export type ComputeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    ClassicAPIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const ComputeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostSecurity$outboundSchema:
  z.ZodMiniType<
    ComputeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostSecurity$Outbound,
    ComputeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      classicAPIKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function computeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostSecurityToJSON(
  computeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostSecurity:
    ComputeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostSecurity,
): string {
  return JSON.stringify(
    ComputeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostSecurity$outboundSchema
      .parse(
        computeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostSecurity,
      ),
  );
}

/** @internal */
export type ComputeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostRequest$Outbound =
  {
    project_id: string;
    run_id: string;
    body: models.ComputeHealthScoreRequest$Outbound;
  };

/** @internal */
export const ComputeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostRequest$outboundSchema:
  z.ZodMiniType<
    ComputeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostRequest$Outbound,
    ComputeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostRequest
  > = z.pipe(
    z.object({
      projectId: z.string(),
      runId: z.string(),
      body: models.ComputeHealthScoreRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
        runId: "run_id",
      });
    }),
  );

export function computeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostRequestToJSON(
  computeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostRequest:
    ComputeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostRequest,
): string {
  return JSON.stringify(
    ComputeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostRequest$outboundSchema
      .parse(
        computeHealthScoreEndpointProjectsProjectIdMetricsTestingRunIdHealthScorePostRequest,
      ),
  );
}
