/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c93e0ef1f131
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutSecurity =
  {
    classicAPIKeyHeader?: string | undefined;
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type CreateOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutRequest =
  {
    integrationId: string;
  };

/** @internal */
export type CreateOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutSecurity$Outbound =
  {
    ClassicAPIKeyHeader?: string | undefined;
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const CreateOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutSecurity$outboundSchema:
  z.ZodMiniType<
    CreateOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutSecurity$Outbound,
    CreateOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutSecurity
  > = z.pipe(
    z.object({
      classicAPIKeyHeader: z.optional(z.string()),
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function createOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutSecurityToJSON(
  createOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutSecurity:
    CreateOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutSecurity,
): string {
  return JSON.stringify(
    CreateOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutSecurity$outboundSchema
      .parse(
        createOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutSecurity,
      ),
  );
}

/** @internal */
export type CreateOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutRequest$Outbound =
  {
    integration_id: string;
  };

/** @internal */
export const CreateOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutRequest$outboundSchema:
  z.ZodMiniType<
    CreateOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutRequest$Outbound,
    CreateOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutRequest
  > = z.pipe(
    z.object({
      integrationId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        integrationId: "integration_id",
      });
    }),
  );

export function createOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutRequestToJSON(
  createOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutRequest:
    CreateOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutRequest,
): string {
  return JSON.stringify(
    CreateOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutRequest$outboundSchema
      .parse(
        createOrUpdateIntegrationSelectionIntegrationsIntegrationIdSelectPutRequest,
      ),
  );
}
