/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2e92cafd8b48
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreatePromptTemplateWithVersionProjectsProjectIdTemplatesPostSecurity =
  {
    classicAPIKeyHeader?: string | undefined;
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type CreatePromptTemplateWithVersionProjectsProjectIdTemplatesPostRequest =
  {
    projectId: string;
    body: models.CreatePromptTemplateWithVersionRequestBody;
  };

/** @internal */
export type CreatePromptTemplateWithVersionProjectsProjectIdTemplatesPostSecurity$Outbound =
  {
    ClassicAPIKeyHeader?: string | undefined;
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const CreatePromptTemplateWithVersionProjectsProjectIdTemplatesPostSecurity$outboundSchema:
  z.ZodMiniType<
    CreatePromptTemplateWithVersionProjectsProjectIdTemplatesPostSecurity$Outbound,
    CreatePromptTemplateWithVersionProjectsProjectIdTemplatesPostSecurity
  > = z.pipe(
    z.object({
      classicAPIKeyHeader: z.optional(z.string()),
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function createPromptTemplateWithVersionProjectsProjectIdTemplatesPostSecurityToJSON(
  createPromptTemplateWithVersionProjectsProjectIdTemplatesPostSecurity:
    CreatePromptTemplateWithVersionProjectsProjectIdTemplatesPostSecurity,
): string {
  return JSON.stringify(
    CreatePromptTemplateWithVersionProjectsProjectIdTemplatesPostSecurity$outboundSchema
      .parse(
        createPromptTemplateWithVersionProjectsProjectIdTemplatesPostSecurity,
      ),
  );
}

/** @internal */
export type CreatePromptTemplateWithVersionProjectsProjectIdTemplatesPostRequest$Outbound =
  {
    project_id: string;
    body: models.CreatePromptTemplateWithVersionRequestBody$Outbound;
  };

/** @internal */
export const CreatePromptTemplateWithVersionProjectsProjectIdTemplatesPostRequest$outboundSchema:
  z.ZodMiniType<
    CreatePromptTemplateWithVersionProjectsProjectIdTemplatesPostRequest$Outbound,
    CreatePromptTemplateWithVersionProjectsProjectIdTemplatesPostRequest
  > = z.pipe(
    z.object({
      projectId: z.string(),
      body: models.CreatePromptTemplateWithVersionRequestBody$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
      });
    }),
  );

export function createPromptTemplateWithVersionProjectsProjectIdTemplatesPostRequestToJSON(
  createPromptTemplateWithVersionProjectsProjectIdTemplatesPostRequest:
    CreatePromptTemplateWithVersionProjectsProjectIdTemplatesPostRequest,
): string {
  return JSON.stringify(
    CreatePromptTemplateWithVersionProjectsProjectIdTemplatesPostRequest$outboundSchema
      .parse(
        createPromptTemplateWithVersionProjectsProjectIdTemplatesPostRequest,
      ),
  );
}
