/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 29c122350ed4
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostSecurity =
  {
    classicAPIKeyHeader?: string | undefined;
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type CreateGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostRequest =
  {
    datasetId: string;
    body: Array<models.GroupCollaboratorCreate>;
  };

/** @internal */
export type CreateGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostSecurity$Outbound =
  {
    ClassicAPIKeyHeader?: string | undefined;
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const CreateGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostSecurity$outboundSchema:
  z.ZodMiniType<
    CreateGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostSecurity$Outbound,
    CreateGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostSecurity
  > = z.pipe(
    z.object({
      classicAPIKeyHeader: z.optional(z.string()),
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function createGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostSecurityToJSON(
  createGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostSecurity:
    CreateGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostSecurity,
): string {
  return JSON.stringify(
    CreateGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostSecurity$outboundSchema
      .parse(
        createGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostSecurity,
      ),
  );
}

/** @internal */
export type CreateGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostRequest$Outbound =
  {
    dataset_id: string;
    body: Array<models.GroupCollaboratorCreate$Outbound>;
  };

/** @internal */
export const CreateGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostRequest$outboundSchema:
  z.ZodMiniType<
    CreateGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostRequest$Outbound,
    CreateGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostRequest
  > = z.pipe(
    z.object({
      datasetId: z.string(),
      body: z.array(models.GroupCollaboratorCreate$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        datasetId: "dataset_id",
      });
    }),
  );

export function createGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostRequestToJSON(
  createGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostRequest:
    CreateGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostRequest,
): string {
  return JSON.stringify(
    CreateGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostRequest$outboundSchema
      .parse(createGroupDatasetCollaboratorsDatasetsDatasetIdGroupsPostRequest),
  );
}
