/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0cb7c8235f66
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateStageProjectsProjectIdStagesPostSecurity = {
  apiKeyHeader?: string | undefined;
  classicAPIKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type CreateStageProjectsProjectIdStagesPostRequest = {
  projectId: string;
  body: models.StageWithRulesets;
};

/** @internal */
export type CreateStageProjectsProjectIdStagesPostSecurity$Outbound = {
  APIKeyHeader?: string | undefined;
  ClassicAPIKeyHeader?: string | undefined;
  OAuth2PasswordBearer?: models.OAuth2PasswordBearerInput$Outbound | undefined;
  HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
};

/** @internal */
export const CreateStageProjectsProjectIdStagesPostSecurity$outboundSchema:
  z.ZodMiniType<
    CreateStageProjectsProjectIdStagesPostSecurity$Outbound,
    CreateStageProjectsProjectIdStagesPostSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      classicAPIKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function createStageProjectsProjectIdStagesPostSecurityToJSON(
  createStageProjectsProjectIdStagesPostSecurity:
    CreateStageProjectsProjectIdStagesPostSecurity,
): string {
  return JSON.stringify(
    CreateStageProjectsProjectIdStagesPostSecurity$outboundSchema.parse(
      createStageProjectsProjectIdStagesPostSecurity,
    ),
  );
}

/** @internal */
export type CreateStageProjectsProjectIdStagesPostRequest$Outbound = {
  project_id: string;
  body: models.StageWithRulesets$Outbound;
};

/** @internal */
export const CreateStageProjectsProjectIdStagesPostRequest$outboundSchema:
  z.ZodMiniType<
    CreateStageProjectsProjectIdStagesPostRequest$Outbound,
    CreateStageProjectsProjectIdStagesPostRequest
  > = z.pipe(
    z.object({
      projectId: z.string(),
      body: models.StageWithRulesets$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
      });
    }),
  );

export function createStageProjectsProjectIdStagesPostRequestToJSON(
  createStageProjectsProjectIdStagesPostRequest:
    CreateStageProjectsProjectIdStagesPostRequest,
): string {
  return JSON.stringify(
    CreateStageProjectsProjectIdStagesPostRequest$outboundSchema.parse(
      createStageProjectsProjectIdStagesPostRequest,
    ),
  );
}
