/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 229febec6ab1
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateGroupProjectCollaboratorsProjectsProjectIdGroupsPostSecurity =
  {
    apiKeyHeader?: string | undefined;
    classicAPIKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type CreateGroupProjectCollaboratorsProjectsProjectIdGroupsPostRequest =
  {
    projectId: string;
    body: Array<models.GroupCollaboratorCreate>;
  };

/** @internal */
export type CreateGroupProjectCollaboratorsProjectsProjectIdGroupsPostSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    ClassicAPIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const CreateGroupProjectCollaboratorsProjectsProjectIdGroupsPostSecurity$outboundSchema:
  z.ZodMiniType<
    CreateGroupProjectCollaboratorsProjectsProjectIdGroupsPostSecurity$Outbound,
    CreateGroupProjectCollaboratorsProjectsProjectIdGroupsPostSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      classicAPIKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function createGroupProjectCollaboratorsProjectsProjectIdGroupsPostSecurityToJSON(
  createGroupProjectCollaboratorsProjectsProjectIdGroupsPostSecurity:
    CreateGroupProjectCollaboratorsProjectsProjectIdGroupsPostSecurity,
): string {
  return JSON.stringify(
    CreateGroupProjectCollaboratorsProjectsProjectIdGroupsPostSecurity$outboundSchema
      .parse(
        createGroupProjectCollaboratorsProjectsProjectIdGroupsPostSecurity,
      ),
  );
}

/** @internal */
export type CreateGroupProjectCollaboratorsProjectsProjectIdGroupsPostRequest$Outbound =
  {
    project_id: string;
    body: Array<models.GroupCollaboratorCreate$Outbound>;
  };

/** @internal */
export const CreateGroupProjectCollaboratorsProjectsProjectIdGroupsPostRequest$outboundSchema:
  z.ZodMiniType<
    CreateGroupProjectCollaboratorsProjectsProjectIdGroupsPostRequest$Outbound,
    CreateGroupProjectCollaboratorsProjectsProjectIdGroupsPostRequest
  > = z.pipe(
    z.object({
      projectId: z.string(),
      body: z.array(models.GroupCollaboratorCreate$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
      });
    }),
  );

export function createGroupProjectCollaboratorsProjectsProjectIdGroupsPostRequestToJSON(
  createGroupProjectCollaboratorsProjectsProjectIdGroupsPostRequest:
    CreateGroupProjectCollaboratorsProjectsProjectIdGroupsPostRequest,
): string {
  return JSON.stringify(
    CreateGroupProjectCollaboratorsProjectsProjectIdGroupsPostRequest$outboundSchema
      .parse(createGroupProjectCollaboratorsProjectsProjectIdGroupsPostRequest),
  );
}
