/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3c5e3386f211
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateGlobalPromptTemplateTemplatesPostSecurity = {
  classicAPIKeyHeader?: string | undefined;
  apiKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type CreateGlobalPromptTemplateTemplatesPostRequest = {
  projectId?: string | null | undefined;
  body: models.CreatePromptTemplateWithVersionRequestBody;
};

/** @internal */
export type CreateGlobalPromptTemplateTemplatesPostSecurity$Outbound = {
  ClassicAPIKeyHeader?: string | undefined;
  APIKeyHeader?: string | undefined;
  OAuth2PasswordBearer?: models.OAuth2PasswordBearerInput$Outbound | undefined;
  HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
};

/** @internal */
export const CreateGlobalPromptTemplateTemplatesPostSecurity$outboundSchema:
  z.ZodMiniType<
    CreateGlobalPromptTemplateTemplatesPostSecurity$Outbound,
    CreateGlobalPromptTemplateTemplatesPostSecurity
  > = z.pipe(
    z.object({
      classicAPIKeyHeader: z.optional(z.string()),
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function createGlobalPromptTemplateTemplatesPostSecurityToJSON(
  createGlobalPromptTemplateTemplatesPostSecurity:
    CreateGlobalPromptTemplateTemplatesPostSecurity,
): string {
  return JSON.stringify(
    CreateGlobalPromptTemplateTemplatesPostSecurity$outboundSchema.parse(
      createGlobalPromptTemplateTemplatesPostSecurity,
    ),
  );
}

/** @internal */
export type CreateGlobalPromptTemplateTemplatesPostRequest$Outbound = {
  project_id?: string | null | undefined;
  body: models.CreatePromptTemplateWithVersionRequestBody$Outbound;
};

/** @internal */
export const CreateGlobalPromptTemplateTemplatesPostRequest$outboundSchema:
  z.ZodMiniType<
    CreateGlobalPromptTemplateTemplatesPostRequest$Outbound,
    CreateGlobalPromptTemplateTemplatesPostRequest
  > = z.pipe(
    z.object({
      projectId: z.optional(z.nullable(z.string())),
      body: models.CreatePromptTemplateWithVersionRequestBody$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
      });
    }),
  );

export function createGlobalPromptTemplateTemplatesPostRequestToJSON(
  createGlobalPromptTemplateTemplatesPostRequest:
    CreateGlobalPromptTemplateTemplatesPostRequest,
): string {
  return JSON.stringify(
    CreateGlobalPromptTemplateTemplatesPostRequest$outboundSchema.parse(
      createGlobalPromptTemplateTemplatesPostRequest,
    ),
  );
}
