/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 550f732973e9
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostSecurity =
  {
    classicAPIKeyHeader?: string | undefined;
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type CreateUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostRequest =
  {
    templateId: string;
    body: Array<models.UserCollaboratorCreate>;
  };

/** @internal */
export type CreateUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostSecurity$Outbound =
  {
    ClassicAPIKeyHeader?: string | undefined;
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const CreateUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostSecurity$outboundSchema:
  z.ZodMiniType<
    CreateUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostSecurity$Outbound,
    CreateUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostSecurity
  > = z.pipe(
    z.object({
      classicAPIKeyHeader: z.optional(z.string()),
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function createUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostSecurityToJSON(
  createUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostSecurity:
    CreateUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostSecurity,
): string {
  return JSON.stringify(
    CreateUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostSecurity$outboundSchema
      .parse(
        createUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostSecurity,
      ),
  );
}

/** @internal */
export type CreateUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostRequest$Outbound =
  {
    template_id: string;
    body: Array<models.UserCollaboratorCreate$Outbound>;
  };

/** @internal */
export const CreateUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostRequest$outboundSchema:
  z.ZodMiniType<
    CreateUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostRequest$Outbound,
    CreateUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostRequest
  > = z.pipe(
    z.object({
      templateId: z.string(),
      body: z.array(models.UserCollaboratorCreate$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        templateId: "template_id",
      });
    }),
  );

export function createUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostRequestToJSON(
  createUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostRequest:
    CreateUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostRequest,
): string {
  return JSON.stringify(
    CreateUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostRequest$outboundSchema
      .parse(
        createUserPromptTemplateCollaboratorsTemplatesTemplateIdUsersPostRequest,
      ),
  );
}
