/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cf61b48871f7
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostSecurity =
  {
    apiKeyHeader?: string | undefined;
    classicAPIKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type CreateGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostRequest =
  {
    templateId: string;
    body: Array<models.GroupCollaboratorCreate>;
  };

/** @internal */
export type CreateGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    ClassicAPIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const CreateGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostSecurity$outboundSchema:
  z.ZodMiniType<
    CreateGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostSecurity$Outbound,
    CreateGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      classicAPIKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function createGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostSecurityToJSON(
  createGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostSecurity:
    CreateGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostSecurity,
): string {
  return JSON.stringify(
    CreateGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostSecurity$outboundSchema
      .parse(
        createGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostSecurity,
      ),
  );
}

/** @internal */
export type CreateGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostRequest$Outbound =
  {
    template_id: string;
    body: Array<models.GroupCollaboratorCreate$Outbound>;
  };

/** @internal */
export const CreateGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostRequest$outboundSchema:
  z.ZodMiniType<
    CreateGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostRequest$Outbound,
    CreateGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostRequest
  > = z.pipe(
    z.object({
      templateId: z.string(),
      body: z.array(models.GroupCollaboratorCreate$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        templateId: "template_id",
      });
    }),
  );

export function createGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostRequestToJSON(
  createGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostRequest:
    CreateGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostRequest,
): string {
  return JSON.stringify(
    CreateGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostRequest$outboundSchema
      .parse(
        createGroupPromptTemplateCollaboratorsTemplatesTemplateIdGroupsPostRequest,
      ),
  );
}
