/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 575e98a3b5a3
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateAnnotationQueueAnnotationQueuesPostSecurity = {
  apiKeyHeader?: string | undefined;
  classicAPIKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

/** @internal */
export type CreateAnnotationQueueAnnotationQueuesPostSecurity$Outbound = {
  APIKeyHeader?: string | undefined;
  ClassicAPIKeyHeader?: string | undefined;
  OAuth2PasswordBearer?: models.OAuth2PasswordBearerInput$Outbound | undefined;
  HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
};

/** @internal */
export const CreateAnnotationQueueAnnotationQueuesPostSecurity$outboundSchema:
  z.ZodMiniType<
    CreateAnnotationQueueAnnotationQueuesPostSecurity$Outbound,
    CreateAnnotationQueueAnnotationQueuesPostSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      classicAPIKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function createAnnotationQueueAnnotationQueuesPostSecurityToJSON(
  createAnnotationQueueAnnotationQueuesPostSecurity:
    CreateAnnotationQueueAnnotationQueuesPostSecurity,
): string {
  return JSON.stringify(
    CreateAnnotationQueueAnnotationQueuesPostSecurity$outboundSchema.parse(
      createAnnotationQueueAnnotationQueuesPostSecurity,
    ),
  );
}
