/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8e856f859be3
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type DeleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteSecurity =
  {
    apiKeyHeader?: string | undefined;
    classicAPIKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type DeleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteRequest =
  {
    templateId: string;
    queueId: string;
  };

/** @internal */
export type DeleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    ClassicAPIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const DeleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteSecurity$outboundSchema:
  z.ZodMiniType<
    DeleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteSecurity$Outbound,
    DeleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      classicAPIKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function deleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteSecurityToJSON(
  deleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteSecurity:
    DeleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteSecurity,
): string {
  return JSON.stringify(
    DeleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteSecurity$outboundSchema
      .parse(
        deleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteSecurity,
      ),
  );
}

/** @internal */
export type DeleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteRequest$Outbound =
  {
    template_id: string;
    queue_id: string;
  };

/** @internal */
export const DeleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteRequest$Outbound,
    DeleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteRequest
  > = z.pipe(
    z.object({
      templateId: z.string(),
      queueId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        templateId: "template_id",
        queueId: "queue_id",
      });
    }),
  );

export function deleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteRequestToJSON(
  deleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteRequest:
    DeleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteRequest$outboundSchema
      .parse(
        deleteQueueTemplateAnnotationQueuesQueueIdTemplatesTemplateIdDeleteRequest,
      ),
  );
}
