/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type DeleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteSecurity =
  {
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type DeleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteRequest =
  {
    logStreamId: string;
    projectId: string;
  };

/** @internal */
export type DeleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const DeleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteSecurity$outboundSchema:
  z.ZodMiniType<
    DeleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteSecurity$Outbound,
    DeleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function deleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteSecurityToJSON(
  deleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteSecurity:
    DeleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteSecurity,
): string {
  return JSON.stringify(
    DeleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteSecurity$outboundSchema
      .parse(
        deleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteSecurity,
      ),
  );
}

/** @internal */
export type DeleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteRequest$Outbound =
  {
    log_stream_id: string;
    project_id: string;
  };

/** @internal */
export const DeleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteRequest$Outbound,
    DeleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteRequest
  > = z.pipe(
    z.object({
      logStreamId: z.string(),
      projectId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        logStreamId: "log_stream_id",
        projectId: "project_id",
      });
    }),
  );

export function deleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteRequestToJSON(
  deleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteRequest:
    DeleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteRequest$outboundSchema
      .parse(
        deleteLogStreamProjectsProjectIdLogStreamsLogStreamIdDeleteRequest,
      ),
  );
}
