/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4af32d8eaf4d
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type DeleteProjectProjectsProjectIdDeleteSecurity = {
  apiKeyHeader?: string | undefined;
  classicAPIKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type DeleteProjectProjectsProjectIdDeleteRequest = {
  projectId: string;
};

/** @internal */
export type DeleteProjectProjectsProjectIdDeleteSecurity$Outbound = {
  APIKeyHeader?: string | undefined;
  ClassicAPIKeyHeader?: string | undefined;
  OAuth2PasswordBearer?: models.OAuth2PasswordBearerInput$Outbound | undefined;
  HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
};

/** @internal */
export const DeleteProjectProjectsProjectIdDeleteSecurity$outboundSchema:
  z.ZodMiniType<
    DeleteProjectProjectsProjectIdDeleteSecurity$Outbound,
    DeleteProjectProjectsProjectIdDeleteSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      classicAPIKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function deleteProjectProjectsProjectIdDeleteSecurityToJSON(
  deleteProjectProjectsProjectIdDeleteSecurity:
    DeleteProjectProjectsProjectIdDeleteSecurity,
): string {
  return JSON.stringify(
    DeleteProjectProjectsProjectIdDeleteSecurity$outboundSchema.parse(
      deleteProjectProjectsProjectIdDeleteSecurity,
    ),
  );
}

/** @internal */
export type DeleteProjectProjectsProjectIdDeleteRequest$Outbound = {
  project_id: string;
};

/** @internal */
export const DeleteProjectProjectsProjectIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeleteProjectProjectsProjectIdDeleteRequest$Outbound,
    DeleteProjectProjectsProjectIdDeleteRequest
  > = z.pipe(
    z.object({
      projectId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
      });
    }),
  );

export function deleteProjectProjectsProjectIdDeleteRequestToJSON(
  deleteProjectProjectsProjectIdDeleteRequest:
    DeleteProjectProjectsProjectIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteProjectProjectsProjectIdDeleteRequest$outboundSchema.parse(
      deleteProjectProjectsProjectIdDeleteRequest,
    ),
  );
}
