/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type DeleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteSecurity =
  {
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type DeleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteRequest =
  {
    projectId: string;
    experimentId: string;
    tagId: string;
  };

/** @internal */
export type DeleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const DeleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteSecurity$outboundSchema:
  z.ZodMiniType<
    DeleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteSecurity$Outbound,
    DeleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function deleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteSecurityToJSON(
  deleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteSecurity:
    DeleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteSecurity,
): string {
  return JSON.stringify(
    DeleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteSecurity$outboundSchema
      .parse(
        deleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteSecurity,
      ),
  );
}

/** @internal */
export type DeleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteRequest$Outbound =
  {
    project_id: string;
    experiment_id: string;
    tag_id: string;
  };

/** @internal */
export const DeleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteRequest$Outbound,
    DeleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteRequest
  > = z.pipe(
    z.object({
      projectId: z.string(),
      experimentId: z.string(),
      tagId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
        experimentId: "experiment_id",
        tagId: "tag_id",
      });
    }),
  );

export function deleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteRequestToJSON(
  deleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteRequest:
    DeleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteRequest$outboundSchema
      .parse(
        deleteExperimentTagProjectsProjectIdExperimentsExperimentIdTagsTagIdDeleteRequest,
      ),
  );
}
