/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1a32550d2844
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type DeleteIntegrationIntegrationsNameDeleteSecurity = {
  apiKeyHeader?: string | undefined;
  classicAPIKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type DeleteIntegrationIntegrationsNameDeleteRequest = {
  name: models.IntegrationProvider;
};

/** @internal */
export type DeleteIntegrationIntegrationsNameDeleteSecurity$Outbound = {
  APIKeyHeader?: string | undefined;
  ClassicAPIKeyHeader?: string | undefined;
  OAuth2PasswordBearer?: models.OAuth2PasswordBearerInput$Outbound | undefined;
  HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
};

/** @internal */
export const DeleteIntegrationIntegrationsNameDeleteSecurity$outboundSchema:
  z.ZodMiniType<
    DeleteIntegrationIntegrationsNameDeleteSecurity$Outbound,
    DeleteIntegrationIntegrationsNameDeleteSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      classicAPIKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function deleteIntegrationIntegrationsNameDeleteSecurityToJSON(
  deleteIntegrationIntegrationsNameDeleteSecurity:
    DeleteIntegrationIntegrationsNameDeleteSecurity,
): string {
  return JSON.stringify(
    DeleteIntegrationIntegrationsNameDeleteSecurity$outboundSchema.parse(
      deleteIntegrationIntegrationsNameDeleteSecurity,
    ),
  );
}

/** @internal */
export type DeleteIntegrationIntegrationsNameDeleteRequest$Outbound = {
  name: string;
};

/** @internal */
export const DeleteIntegrationIntegrationsNameDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeleteIntegrationIntegrationsNameDeleteRequest$Outbound,
    DeleteIntegrationIntegrationsNameDeleteRequest
  > = z.object({
    name: models.IntegrationProvider$outboundSchema,
  });

export function deleteIntegrationIntegrationsNameDeleteRequestToJSON(
  deleteIntegrationIntegrationsNameDeleteRequest:
    DeleteIntegrationIntegrationsNameDeleteRequest,
): string {
  return JSON.stringify(
    DeleteIntegrationIntegrationsNameDeleteRequest$outboundSchema.parse(
      deleteIntegrationIntegrationsNameDeleteRequest,
    ),
  );
}
