/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2dbad564f9c1
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type DeleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteSecurity =
  {
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type DeleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteRequest =
  {
    templateId: string;
    userId: string;
  };

/** @internal */
export type DeleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const DeleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteSecurity$outboundSchema:
  z.ZodMiniType<
    DeleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteSecurity$Outbound,
    DeleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function deleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteSecurityToJSON(
  deleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteSecurity:
    DeleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteSecurity,
): string {
  return JSON.stringify(
    DeleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteSecurity$outboundSchema
      .parse(
        deleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteSecurity,
      ),
  );
}

/** @internal */
export type DeleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteRequest$Outbound =
  {
    template_id: string;
    user_id: string;
  };

/** @internal */
export const DeleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteRequest$Outbound,
    DeleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteRequest
  > = z.pipe(
    z.object({
      templateId: z.string(),
      userId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        templateId: "template_id",
        userId: "user_id",
      });
    }),
  );

export function deleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteRequestToJSON(
  deleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteRequest:
    DeleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteRequest$outboundSchema
      .parse(
        deleteUserPromptTemplateCollaboratorTemplatesTemplateIdUsersUserIdDeleteRequest,
      ),
  );
}
