/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type DownloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetSecurity =
  {
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type DownloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetRequest =
  {
    projectId: string;
    datasetId: string;
  };

/** @internal */
export type DownloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const DownloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetSecurity$outboundSchema:
  z.ZodMiniType<
    DownloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetSecurity$Outbound,
    DownloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function downloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetSecurityToJSON(
  downloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetSecurity:
    DownloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetSecurity,
): string {
  return JSON.stringify(
    DownloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetSecurity$outboundSchema
      .parse(
        downloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetSecurity,
      ),
  );
}

/** @internal */
export type DownloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetRequest$Outbound =
  {
    project_id: string;
    dataset_id: string;
  };

/** @internal */
export const DownloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetRequest$outboundSchema:
  z.ZodMiniType<
    DownloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetRequest$Outbound,
    DownloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetRequest
  > = z.pipe(
    z.object({
      projectId: z.string(),
      datasetId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
        datasetId: "dataset_id",
      });
    }),
  );

export function downloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetRequestToJSON(
  downloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetRequest:
    DownloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetRequest,
): string {
  return JSON.stringify(
    DownloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetRequest$outboundSchema
      .parse(
        downloadPromptDatasetProjectsProjectIdPromptDatasetsDatasetIdGetRequest,
      ),
  );
}
