/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fbb6957868b2
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ExportEditsDatabricksIntegrationsDatabricksEditsExportPostSecurity =
  {
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type ExportEditsDatabricksIntegrationsDatabricksEditsExportPostRequest =
  {
    ignoreConflictingEdits?: boolean | undefined;
    body: models.DatabricksEditExportRequest;
  };

/** @internal */
export type ExportEditsDatabricksIntegrationsDatabricksEditsExportPostSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const ExportEditsDatabricksIntegrationsDatabricksEditsExportPostSecurity$outboundSchema:
  z.ZodMiniType<
    ExportEditsDatabricksIntegrationsDatabricksEditsExportPostSecurity$Outbound,
    ExportEditsDatabricksIntegrationsDatabricksEditsExportPostSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function exportEditsDatabricksIntegrationsDatabricksEditsExportPostSecurityToJSON(
  exportEditsDatabricksIntegrationsDatabricksEditsExportPostSecurity:
    ExportEditsDatabricksIntegrationsDatabricksEditsExportPostSecurity,
): string {
  return JSON.stringify(
    ExportEditsDatabricksIntegrationsDatabricksEditsExportPostSecurity$outboundSchema
      .parse(
        exportEditsDatabricksIntegrationsDatabricksEditsExportPostSecurity,
      ),
  );
}

/** @internal */
export type ExportEditsDatabricksIntegrationsDatabricksEditsExportPostRequest$Outbound =
  {
    ignore_conflicting_edits: boolean;
    body: models.DatabricksEditExportRequest$Outbound;
  };

/** @internal */
export const ExportEditsDatabricksIntegrationsDatabricksEditsExportPostRequest$outboundSchema:
  z.ZodMiniType<
    ExportEditsDatabricksIntegrationsDatabricksEditsExportPostRequest$Outbound,
    ExportEditsDatabricksIntegrationsDatabricksEditsExportPostRequest
  > = z.pipe(
    z.object({
      ignoreConflictingEdits: z._default(z.boolean(), true),
      body: models.DatabricksEditExportRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        ignoreConflictingEdits: "ignore_conflicting_edits",
      });
    }),
  );

export function exportEditsDatabricksIntegrationsDatabricksEditsExportPostRequestToJSON(
  exportEditsDatabricksIntegrationsDatabricksEditsExportPostRequest:
    ExportEditsDatabricksIntegrationsDatabricksEditsExportPostRequest,
): string {
  return JSON.stringify(
    ExportEditsDatabricksIntegrationsDatabricksEditsExportPostRequest$outboundSchema
      .parse(exportEditsDatabricksIntegrationsDatabricksEditsExportPostRequest),
  );
}
