/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type GetAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetSecurity =
  {
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type GetAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetRequest =
  {
    llmIntegration: models.LLMIntegration;
  };

/** @internal */
export type GetAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const GetAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetSecurity$Outbound,
    GetAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function getAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetSecurityToJSON(
  getAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetSecurity:
    GetAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetSecurity,
): string {
  return JSON.stringify(
    GetAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetSecurity$outboundSchema
      .parse(
        getAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetSecurity,
      ),
  );
}

/** @internal */
export type GetAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetRequest$Outbound =
  {
    llm_integration: string;
  };

/** @internal */
export const GetAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetRequest$outboundSchema:
  z.ZodMiniType<
    GetAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetRequest$Outbound,
    GetAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetRequest
  > = z.pipe(
    z.object({
      llmIntegration: models.LLMIntegration$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        llmIntegration: "llm_integration",
      });
    }),
  );

export function getAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetRequestToJSON(
  getAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetRequest:
    GetAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetRequest,
): string {
  return JSON.stringify(
    GetAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetRequest$outboundSchema
      .parse(
        getAvailableScorerModelsLlmIntegrationsLlmIntegrationScorerModelsGetRequest,
      ),
  );
}
