/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9adfa12f9f1a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type GetCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetSecurity =
  {
    apiKeyHeader?: string | undefined;
    classicAPIKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type GetCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetRequest =
  {
    generationId: string;
  };

/** @internal */
export type GetCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    ClassicAPIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const GetCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetSecurity$Outbound,
    GetCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      classicAPIKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function getCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetSecurityToJSON(
  getCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetSecurity:
    GetCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetSecurity,
): string {
  return JSON.stringify(
    GetCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetSecurity$outboundSchema
      .parse(
        getCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetSecurity,
      ),
  );
}

/** @internal */
export type GetCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetRequest$Outbound =
  {
    generation_id: string;
  };

/** @internal */
export const GetCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetRequest$outboundSchema:
  z.ZodMiniType<
    GetCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetRequest$Outbound,
    GetCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetRequest
  > = z.pipe(
    z.object({
      generationId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        generationId: "generation_id",
      });
    }),
  );

export function getCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetRequestToJSON(
  getCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetRequest:
    GetCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetRequest,
): string {
  return JSON.stringify(
    GetCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetRequest$outboundSchema
      .parse(
        getCodeMetricGenerationStatusCodeMetricGenerationsGenerationIdStatusGetRequest,
      ),
  );
}
