/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type GetExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostSecurity =
  {
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type GetExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostRequest =
  {
    projectId: string;
    experimentId: string;
    body: models.ExperimentMetricsRequest;
  };

/** @internal */
export type GetExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const GetExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostSecurity$outboundSchema:
  z.ZodMiniType<
    GetExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostSecurity$Outbound,
    GetExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function getExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostSecurityToJSON(
  getExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostSecurity:
    GetExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostSecurity,
): string {
  return JSON.stringify(
    GetExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostSecurity$outboundSchema
      .parse(
        getExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostSecurity,
      ),
  );
}

/** @internal */
export type GetExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostRequest$Outbound =
  {
    project_id: string;
    experiment_id: string;
    body: models.ExperimentMetricsRequest$Outbound;
  };

/** @internal */
export const GetExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostRequest$outboundSchema:
  z.ZodMiniType<
    GetExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostRequest$Outbound,
    GetExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostRequest
  > = z.pipe(
    z.object({
      projectId: z.string(),
      experimentId: z.string(),
      body: models.ExperimentMetricsRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
        experimentId: "experiment_id",
      });
    }),
  );

export function getExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostRequestToJSON(
  getExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostRequest:
    GetExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostRequest,
): string {
  return JSON.stringify(
    GetExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostRequest$outboundSchema
      .parse(
        getExperimentMetricsProjectsProjectIdExperimentsExperimentIdMetricsPostRequest,
      ),
  );
}
