/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type GetExperimentProjectsProjectIdExperimentsExperimentIdGetSecurity = {
  apiKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type GetExperimentProjectsProjectIdExperimentsExperimentIdGetRequest = {
  experimentId: string;
  projectId: string;
};

/** @internal */
export type GetExperimentProjectsProjectIdExperimentsExperimentIdGetSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const GetExperimentProjectsProjectIdExperimentsExperimentIdGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetExperimentProjectsProjectIdExperimentsExperimentIdGetSecurity$Outbound,
    GetExperimentProjectsProjectIdExperimentsExperimentIdGetSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function getExperimentProjectsProjectIdExperimentsExperimentIdGetSecurityToJSON(
  getExperimentProjectsProjectIdExperimentsExperimentIdGetSecurity:
    GetExperimentProjectsProjectIdExperimentsExperimentIdGetSecurity,
): string {
  return JSON.stringify(
    GetExperimentProjectsProjectIdExperimentsExperimentIdGetSecurity$outboundSchema
      .parse(getExperimentProjectsProjectIdExperimentsExperimentIdGetSecurity),
  );
}

/** @internal */
export type GetExperimentProjectsProjectIdExperimentsExperimentIdGetRequest$Outbound =
  {
    experiment_id: string;
    project_id: string;
  };

/** @internal */
export const GetExperimentProjectsProjectIdExperimentsExperimentIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetExperimentProjectsProjectIdExperimentsExperimentIdGetRequest$Outbound,
    GetExperimentProjectsProjectIdExperimentsExperimentIdGetRequest
  > = z.pipe(
    z.object({
      experimentId: z.string(),
      projectId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        experimentId: "experiment_id",
        projectId: "project_id",
      });
    }),
  );

export function getExperimentProjectsProjectIdExperimentsExperimentIdGetRequestToJSON(
  getExperimentProjectsProjectIdExperimentsExperimentIdGetRequest:
    GetExperimentProjectsProjectIdExperimentsExperimentIdGetRequest,
): string {
  return JSON.stringify(
    GetExperimentProjectsProjectIdExperimentsExperimentIdGetRequest$outboundSchema
      .parse(getExperimentProjectsProjectIdExperimentsExperimentIdGetRequest),
  );
}
