/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9492c07007b4
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type GetIntegrationsAndModelInfoLlmIntegrationsGetSecurity = {
  apiKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
};

export type GetIntegrationsAndModelInfoLlmIntegrationsGetRequest = {
  multimodalCapabilities?:
    | Array<models.MultimodalCapability>
    | null
    | undefined;
};

/** @internal */
export type GetIntegrationsAndModelInfoLlmIntegrationsGetSecurity$Outbound = {
  APIKeyHeader?: string | undefined;
  OAuth2PasswordBearer?: models.OAuth2PasswordBearerInput$Outbound | undefined;
};

/** @internal */
export const GetIntegrationsAndModelInfoLlmIntegrationsGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetIntegrationsAndModelInfoLlmIntegrationsGetSecurity$Outbound,
    GetIntegrationsAndModelInfoLlmIntegrationsGetSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
      });
    }),
  );

export function getIntegrationsAndModelInfoLlmIntegrationsGetSecurityToJSON(
  getIntegrationsAndModelInfoLlmIntegrationsGetSecurity:
    GetIntegrationsAndModelInfoLlmIntegrationsGetSecurity,
): string {
  return JSON.stringify(
    GetIntegrationsAndModelInfoLlmIntegrationsGetSecurity$outboundSchema.parse(
      getIntegrationsAndModelInfoLlmIntegrationsGetSecurity,
    ),
  );
}

/** @internal */
export type GetIntegrationsAndModelInfoLlmIntegrationsGetRequest$Outbound = {
  multimodal_capabilities?: Array<string> | null | undefined;
};

/** @internal */
export const GetIntegrationsAndModelInfoLlmIntegrationsGetRequest$outboundSchema:
  z.ZodMiniType<
    GetIntegrationsAndModelInfoLlmIntegrationsGetRequest$Outbound,
    GetIntegrationsAndModelInfoLlmIntegrationsGetRequest
  > = z.pipe(
    z.object({
      multimodalCapabilities: z.optional(
        z.nullable(z.array(models.MultimodalCapability$outboundSchema)),
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        multimodalCapabilities: "multimodal_capabilities",
      });
    }),
  );

export function getIntegrationsAndModelInfoLlmIntegrationsGetRequestToJSON(
  getIntegrationsAndModelInfoLlmIntegrationsGetRequest:
    GetIntegrationsAndModelInfoLlmIntegrationsGetRequest,
): string {
  return JSON.stringify(
    GetIntegrationsAndModelInfoLlmIntegrationsGetRequest$outboundSchema.parse(
      getIntegrationsAndModelInfoLlmIntegrationsGetRequest,
    ),
  );
}
