/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: db41786b3c01
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type GetSessionProjectsProjectIdSessionsSessionIdGetSecurity = {
  apiKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type GetSessionProjectsProjectIdSessionsSessionIdGetRequest = {
  sessionId: string;
  projectId: string;
};

/** @internal */
export type GetSessionProjectsProjectIdSessionsSessionIdGetSecurity$Outbound = {
  APIKeyHeader?: string | undefined;
  OAuth2PasswordBearer?: models.OAuth2PasswordBearerInput$Outbound | undefined;
  HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
};

/** @internal */
export const GetSessionProjectsProjectIdSessionsSessionIdGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetSessionProjectsProjectIdSessionsSessionIdGetSecurity$Outbound,
    GetSessionProjectsProjectIdSessionsSessionIdGetSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function getSessionProjectsProjectIdSessionsSessionIdGetSecurityToJSON(
  getSessionProjectsProjectIdSessionsSessionIdGetSecurity:
    GetSessionProjectsProjectIdSessionsSessionIdGetSecurity,
): string {
  return JSON.stringify(
    GetSessionProjectsProjectIdSessionsSessionIdGetSecurity$outboundSchema
      .parse(getSessionProjectsProjectIdSessionsSessionIdGetSecurity),
  );
}

/** @internal */
export type GetSessionProjectsProjectIdSessionsSessionIdGetRequest$Outbound = {
  session_id: string;
  project_id: string;
};

/** @internal */
export const GetSessionProjectsProjectIdSessionsSessionIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetSessionProjectsProjectIdSessionsSessionIdGetRequest$Outbound,
    GetSessionProjectsProjectIdSessionsSessionIdGetRequest
  > = z.pipe(
    z.object({
      sessionId: z.string(),
      projectId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        sessionId: "session_id",
        projectId: "project_id",
      });
    }),
  );

export function getSessionProjectsProjectIdSessionsSessionIdGetRequestToJSON(
  getSessionProjectsProjectIdSessionsSessionIdGetRequest:
    GetSessionProjectsProjectIdSessionsSessionIdGetRequest,
): string {
  return JSON.stringify(
    GetSessionProjectsProjectIdSessionsSessionIdGetRequest$outboundSchema.parse(
      getSessionProjectsProjectIdSessionsSessionIdGetRequest,
    ),
  );
}
