/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4bb9bee4f280
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type GetScorerVersionOrLatestScorersScorerIdVersionGetSecurity = {
  classicAPIKeyHeader?: string | undefined;
  apiKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type GetScorerVersionOrLatestScorersScorerIdVersionGetRequest = {
  scorerId: string;
  version?: number | undefined;
};

/** @internal */
export type GetScorerVersionOrLatestScorersScorerIdVersionGetSecurity$Outbound =
  {
    ClassicAPIKeyHeader?: string | undefined;
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const GetScorerVersionOrLatestScorersScorerIdVersionGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetScorerVersionOrLatestScorersScorerIdVersionGetSecurity$Outbound,
    GetScorerVersionOrLatestScorersScorerIdVersionGetSecurity
  > = z.pipe(
    z.object({
      classicAPIKeyHeader: z.optional(z.string()),
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function getScorerVersionOrLatestScorersScorerIdVersionGetSecurityToJSON(
  getScorerVersionOrLatestScorersScorerIdVersionGetSecurity:
    GetScorerVersionOrLatestScorersScorerIdVersionGetSecurity,
): string {
  return JSON.stringify(
    GetScorerVersionOrLatestScorersScorerIdVersionGetSecurity$outboundSchema
      .parse(getScorerVersionOrLatestScorersScorerIdVersionGetSecurity),
  );
}

/** @internal */
export type GetScorerVersionOrLatestScorersScorerIdVersionGetRequest$Outbound =
  {
    scorer_id: string;
    version?: number | undefined;
  };

/** @internal */
export const GetScorerVersionOrLatestScorersScorerIdVersionGetRequest$outboundSchema:
  z.ZodMiniType<
    GetScorerVersionOrLatestScorersScorerIdVersionGetRequest$Outbound,
    GetScorerVersionOrLatestScorersScorerIdVersionGetRequest
  > = z.pipe(
    z.object({
      scorerId: z.string(),
      version: z.optional(z.int()),
    }),
    z.transform((v) => {
      return remap$(v, {
        scorerId: "scorer_id",
      });
    }),
  );

export function getScorerVersionOrLatestScorersScorerIdVersionGetRequestToJSON(
  getScorerVersionOrLatestScorersScorerIdVersionGetRequest:
    GetScorerVersionOrLatestScorersScorerIdVersionGetRequest,
): string {
  return JSON.stringify(
    GetScorerVersionOrLatestScorersScorerIdVersionGetRequest$outboundSchema
      .parse(getScorerVersionOrLatestScorersScorerIdVersionGetRequest),
  );
}
