/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b1d26c622c28
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type GetScorerHealthScoresScorersScorerIdHealthScoresGetSecurity = {
  apiKeyHeader?: string | undefined;
  classicAPIKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type GetScorerHealthScoresScorersScorerIdHealthScoresGetRequest = {
  scorerId: string;
  datasetId: string;
};

/** @internal */
export type GetScorerHealthScoresScorersScorerIdHealthScoresGetSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    ClassicAPIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const GetScorerHealthScoresScorersScorerIdHealthScoresGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetScorerHealthScoresScorersScorerIdHealthScoresGetSecurity$Outbound,
    GetScorerHealthScoresScorersScorerIdHealthScoresGetSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      classicAPIKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function getScorerHealthScoresScorersScorerIdHealthScoresGetSecurityToJSON(
  getScorerHealthScoresScorersScorerIdHealthScoresGetSecurity:
    GetScorerHealthScoresScorersScorerIdHealthScoresGetSecurity,
): string {
  return JSON.stringify(
    GetScorerHealthScoresScorersScorerIdHealthScoresGetSecurity$outboundSchema
      .parse(getScorerHealthScoresScorersScorerIdHealthScoresGetSecurity),
  );
}

/** @internal */
export type GetScorerHealthScoresScorersScorerIdHealthScoresGetRequest$Outbound =
  {
    scorer_id: string;
    dataset_id: string;
  };

/** @internal */
export const GetScorerHealthScoresScorersScorerIdHealthScoresGetRequest$outboundSchema:
  z.ZodMiniType<
    GetScorerHealthScoresScorersScorerIdHealthScoresGetRequest$Outbound,
    GetScorerHealthScoresScorersScorerIdHealthScoresGetRequest
  > = z.pipe(
    z.object({
      scorerId: z.string(),
      datasetId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        scorerId: "scorer_id",
        datasetId: "dataset_id",
      });
    }),
  );

export function getScorerHealthScoresScorersScorerIdHealthScoresGetRequestToJSON(
  getScorerHealthScoresScorersScorerIdHealthScoresGetRequest:
    GetScorerHealthScoresScorersScorerIdHealthScoresGetRequest,
): string {
  return JSON.stringify(
    GetScorerHealthScoresScorersScorerIdHealthScoresGetRequest$outboundSchema
      .parse(getScorerHealthScoresScorersScorerIdHealthScoresGetRequest),
  );
}
