/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2a30de2c51f2
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type GetTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetSecurity =
  {
    classicAPIKeyHeader?: string | undefined;
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type GetTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetRequest =
  {
    templateId: string;
    projectId: string;
  };

/** @internal */
export type GetTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetSecurity$Outbound =
  {
    ClassicAPIKeyHeader?: string | undefined;
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const GetTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetSecurity$Outbound,
    GetTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetSecurity
  > = z.pipe(
    z.object({
      classicAPIKeyHeader: z.optional(z.string()),
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function getTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetSecurityToJSON(
  getTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetSecurity:
    GetTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetSecurity,
): string {
  return JSON.stringify(
    GetTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetSecurity$outboundSchema
      .parse(
        getTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetSecurity,
      ),
  );
}

/** @internal */
export type GetTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetRequest$Outbound =
  {
    template_id: string;
    project_id: string;
  };

/** @internal */
export const GetTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetRequest$Outbound,
    GetTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetRequest
  > = z.pipe(
    z.object({
      templateId: z.string(),
      projectId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        templateId: "template_id",
        projectId: "project_id",
      });
    }),
  );

export function getTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetRequestToJSON(
  getTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetRequest:
    GetTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetRequest,
): string {
  return JSON.stringify(
    GetTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetRequest$outboundSchema
      .parse(
        getTemplateFromProjectProjectsProjectIdTemplatesTemplateIdGetRequest,
      ),
  );
}
