/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c4c64e3e6251
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type GetValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetSecurity =
  {
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  };

export type GetValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetRequest =
  {
    taskId: string;
  };

/** @internal */
export type GetValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
  };

/** @internal */
export const GetValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetSecurity$Outbound,
    GetValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
      });
    }),
  );

export function getValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetSecurityToJSON(
  getValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetSecurity:
    GetValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetSecurity,
): string {
  return JSON.stringify(
    GetValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetSecurity$outboundSchema
      .parse(
        getValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetSecurity,
      ),
  );
}

/** @internal */
export type GetValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetRequest$Outbound =
  {
    task_id: string;
  };

/** @internal */
export const GetValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetRequest$Outbound,
    GetValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetRequest
  > = z.pipe(
    z.object({
      taskId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        taskId: "task_id",
      });
    }),
  );

export function getValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetRequestToJSON(
  getValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetRequest:
    GetValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetRequest,
): string {
  return JSON.stringify(
    GetValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetRequest$outboundSchema
      .parse(
        getValidateCodeScorerTaskResultScorersCodeValidateTaskIdGetRequest,
      ),
  );
}
