/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 76c2539416e2
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ListUserDatasetCollaboratorsDatasetsDatasetIdUsersGetSecurity = {
  apiKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type ListUserDatasetCollaboratorsDatasetsDatasetIdUsersGetRequest = {
  datasetId: string;
  startingToken?: number | undefined;
  limit?: number | undefined;
};

/** @internal */
export type ListUserDatasetCollaboratorsDatasetsDatasetIdUsersGetSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const ListUserDatasetCollaboratorsDatasetsDatasetIdUsersGetSecurity$outboundSchema:
  z.ZodMiniType<
    ListUserDatasetCollaboratorsDatasetsDatasetIdUsersGetSecurity$Outbound,
    ListUserDatasetCollaboratorsDatasetsDatasetIdUsersGetSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function listUserDatasetCollaboratorsDatasetsDatasetIdUsersGetSecurityToJSON(
  listUserDatasetCollaboratorsDatasetsDatasetIdUsersGetSecurity:
    ListUserDatasetCollaboratorsDatasetsDatasetIdUsersGetSecurity,
): string {
  return JSON.stringify(
    ListUserDatasetCollaboratorsDatasetsDatasetIdUsersGetSecurity$outboundSchema
      .parse(listUserDatasetCollaboratorsDatasetsDatasetIdUsersGetSecurity),
  );
}

/** @internal */
export type ListUserDatasetCollaboratorsDatasetsDatasetIdUsersGetRequest$Outbound =
  {
    dataset_id: string;
    starting_token: number;
    limit: number;
  };

/** @internal */
export const ListUserDatasetCollaboratorsDatasetsDatasetIdUsersGetRequest$outboundSchema:
  z.ZodMiniType<
    ListUserDatasetCollaboratorsDatasetsDatasetIdUsersGetRequest$Outbound,
    ListUserDatasetCollaboratorsDatasetsDatasetIdUsersGetRequest
  > = z.pipe(
    z.object({
      datasetId: z.string(),
      startingToken: z._default(z.int(), 0),
      limit: z._default(z.int(), 100),
    }),
    z.transform((v) => {
      return remap$(v, {
        datasetId: "dataset_id",
        startingToken: "starting_token",
      });
    }),
  );

export function listUserDatasetCollaboratorsDatasetsDatasetIdUsersGetRequestToJSON(
  listUserDatasetCollaboratorsDatasetsDatasetIdUsersGetRequest:
    ListUserDatasetCollaboratorsDatasetsDatasetIdUsersGetRequest,
): string {
  return JSON.stringify(
    ListUserDatasetCollaboratorsDatasetsDatasetIdUsersGetRequest$outboundSchema
      .parse(listUserDatasetCollaboratorsDatasetsDatasetIdUsersGetRequest),
  );
}
