/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d187d915baee
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ListProjectsForScorerRouteScorersScorerIdProjectsGetSecurity = {
  apiKeyHeader?: string | undefined;
  classicAPIKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type ListProjectsForScorerRouteScorersScorerIdProjectsGetRequest = {
  scorerId: string;
  startingToken?: number | undefined;
  limit?: number | undefined;
};

/** @internal */
export type ListProjectsForScorerRouteScorersScorerIdProjectsGetSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    ClassicAPIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const ListProjectsForScorerRouteScorersScorerIdProjectsGetSecurity$outboundSchema:
  z.ZodMiniType<
    ListProjectsForScorerRouteScorersScorerIdProjectsGetSecurity$Outbound,
    ListProjectsForScorerRouteScorersScorerIdProjectsGetSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      classicAPIKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function listProjectsForScorerRouteScorersScorerIdProjectsGetSecurityToJSON(
  listProjectsForScorerRouteScorersScorerIdProjectsGetSecurity:
    ListProjectsForScorerRouteScorersScorerIdProjectsGetSecurity,
): string {
  return JSON.stringify(
    ListProjectsForScorerRouteScorersScorerIdProjectsGetSecurity$outboundSchema
      .parse(listProjectsForScorerRouteScorersScorerIdProjectsGetSecurity),
  );
}

/** @internal */
export type ListProjectsForScorerRouteScorersScorerIdProjectsGetRequest$Outbound =
  {
    scorer_id: string;
    starting_token: number;
    limit: number;
  };

/** @internal */
export const ListProjectsForScorerRouteScorersScorerIdProjectsGetRequest$outboundSchema:
  z.ZodMiniType<
    ListProjectsForScorerRouteScorersScorerIdProjectsGetRequest$Outbound,
    ListProjectsForScorerRouteScorersScorerIdProjectsGetRequest
  > = z.pipe(
    z.object({
      scorerId: z.string(),
      startingToken: z._default(z.int(), 0),
      limit: z._default(z.int(), 100),
    }),
    z.transform((v) => {
      return remap$(v, {
        scorerId: "scorer_id",
        startingToken: "starting_token",
      });
    }),
  );

export function listProjectsForScorerRouteScorersScorerIdProjectsGetRequestToJSON(
  listProjectsForScorerRouteScorersScorerIdProjectsGetRequest:
    ListProjectsForScorerRouteScorersScorerIdProjectsGetRequest,
): string {
  return JSON.stringify(
    ListProjectsForScorerRouteScorersScorerIdProjectsGetRequest$outboundSchema
      .parse(listProjectsForScorerRouteScorersScorerIdProjectsGetRequest),
  );
}
