/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a85ede941d79
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ListDatasetProjectsDatasetsDatasetIdProjectsGetSecurity = {
  apiKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type ListDatasetProjectsDatasetsDatasetIdProjectsGetRequest = {
  datasetId: string;
  startingToken?: number | undefined;
  limit?: number | undefined;
};

/** @internal */
export type ListDatasetProjectsDatasetsDatasetIdProjectsGetSecurity$Outbound = {
  APIKeyHeader?: string | undefined;
  OAuth2PasswordBearer?: models.OAuth2PasswordBearerInput$Outbound | undefined;
  HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
};

/** @internal */
export const ListDatasetProjectsDatasetsDatasetIdProjectsGetSecurity$outboundSchema:
  z.ZodMiniType<
    ListDatasetProjectsDatasetsDatasetIdProjectsGetSecurity$Outbound,
    ListDatasetProjectsDatasetsDatasetIdProjectsGetSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function listDatasetProjectsDatasetsDatasetIdProjectsGetSecurityToJSON(
  listDatasetProjectsDatasetsDatasetIdProjectsGetSecurity:
    ListDatasetProjectsDatasetsDatasetIdProjectsGetSecurity,
): string {
  return JSON.stringify(
    ListDatasetProjectsDatasetsDatasetIdProjectsGetSecurity$outboundSchema
      .parse(listDatasetProjectsDatasetsDatasetIdProjectsGetSecurity),
  );
}

/** @internal */
export type ListDatasetProjectsDatasetsDatasetIdProjectsGetRequest$Outbound = {
  dataset_id: string;
  starting_token: number;
  limit: number;
};

/** @internal */
export const ListDatasetProjectsDatasetsDatasetIdProjectsGetRequest$outboundSchema:
  z.ZodMiniType<
    ListDatasetProjectsDatasetsDatasetIdProjectsGetRequest$Outbound,
    ListDatasetProjectsDatasetsDatasetIdProjectsGetRequest
  > = z.pipe(
    z.object({
      datasetId: z.string(),
      startingToken: z._default(z.int(), 0),
      limit: z._default(z.int(), 100),
    }),
    z.transform((v) => {
      return remap$(v, {
        datasetId: "dataset_id",
        startingToken: "starting_token",
      });
    }),
  );

export function listDatasetProjectsDatasetsDatasetIdProjectsGetRequestToJSON(
  listDatasetProjectsDatasetsDatasetIdProjectsGetRequest:
    ListDatasetProjectsDatasetsDatasetIdProjectsGetRequest,
): string {
  return JSON.stringify(
    ListDatasetProjectsDatasetsDatasetIdProjectsGetRequest$outboundSchema.parse(
      listDatasetProjectsDatasetsDatasetIdProjectsGetRequest,
    ),
  );
}
