/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e802c5e22b9d
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type PauseStageProjectsProjectIdStagesStageIdPutSecurity = {
  classicAPIKeyHeader?: string | undefined;
  apiKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type PauseStageProjectsProjectIdStagesStageIdPutRequest = {
  stageId: string;
  projectId: string;
  pause?: boolean | undefined;
};

/** @internal */
export type PauseStageProjectsProjectIdStagesStageIdPutSecurity$Outbound = {
  ClassicAPIKeyHeader?: string | undefined;
  APIKeyHeader?: string | undefined;
  OAuth2PasswordBearer?: models.OAuth2PasswordBearerInput$Outbound | undefined;
  HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
};

/** @internal */
export const PauseStageProjectsProjectIdStagesStageIdPutSecurity$outboundSchema:
  z.ZodMiniType<
    PauseStageProjectsProjectIdStagesStageIdPutSecurity$Outbound,
    PauseStageProjectsProjectIdStagesStageIdPutSecurity
  > = z.pipe(
    z.object({
      classicAPIKeyHeader: z.optional(z.string()),
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function pauseStageProjectsProjectIdStagesStageIdPutSecurityToJSON(
  pauseStageProjectsProjectIdStagesStageIdPutSecurity:
    PauseStageProjectsProjectIdStagesStageIdPutSecurity,
): string {
  return JSON.stringify(
    PauseStageProjectsProjectIdStagesStageIdPutSecurity$outboundSchema.parse(
      pauseStageProjectsProjectIdStagesStageIdPutSecurity,
    ),
  );
}

/** @internal */
export type PauseStageProjectsProjectIdStagesStageIdPutRequest$Outbound = {
  stage_id: string;
  project_id: string;
  pause: boolean;
};

/** @internal */
export const PauseStageProjectsProjectIdStagesStageIdPutRequest$outboundSchema:
  z.ZodMiniType<
    PauseStageProjectsProjectIdStagesStageIdPutRequest$Outbound,
    PauseStageProjectsProjectIdStagesStageIdPutRequest
  > = z.pipe(
    z.object({
      stageId: z.string(),
      projectId: z.string(),
      pause: z._default(z.boolean(), false),
    }),
    z.transform((v) => {
      return remap$(v, {
        stageId: "stage_id",
        projectId: "project_id",
      });
    }),
  );

export function pauseStageProjectsProjectIdStagesStageIdPutRequestToJSON(
  pauseStageProjectsProjectIdStagesStageIdPutRequest:
    PauseStageProjectsProjectIdStagesStageIdPutRequest,
): string {
  return JSON.stringify(
    PauseStageProjectsProjectIdStagesStageIdPutRequest$outboundSchema.parse(
      pauseStageProjectsProjectIdStagesStageIdPutRequest,
    ),
  );
}
