/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e4889e68ea55
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type QueryPartialSpansProjectsProjectIdSpansPartialSearchPostSecurity = {
  classicAPIKeyHeader?: string | undefined;
  apiKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type QueryPartialSpansProjectsProjectIdSpansPartialSearchPostRequest = {
  projectId: string;
  body: models.LogRecordsPartialQueryRequest;
};

/** @internal */
export type QueryPartialSpansProjectsProjectIdSpansPartialSearchPostSecurity$Outbound =
  {
    ClassicAPIKeyHeader?: string | undefined;
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const QueryPartialSpansProjectsProjectIdSpansPartialSearchPostSecurity$outboundSchema:
  z.ZodMiniType<
    QueryPartialSpansProjectsProjectIdSpansPartialSearchPostSecurity$Outbound,
    QueryPartialSpansProjectsProjectIdSpansPartialSearchPostSecurity
  > = z.pipe(
    z.object({
      classicAPIKeyHeader: z.optional(z.string()),
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function queryPartialSpansProjectsProjectIdSpansPartialSearchPostSecurityToJSON(
  queryPartialSpansProjectsProjectIdSpansPartialSearchPostSecurity:
    QueryPartialSpansProjectsProjectIdSpansPartialSearchPostSecurity,
): string {
  return JSON.stringify(
    QueryPartialSpansProjectsProjectIdSpansPartialSearchPostSecurity$outboundSchema
      .parse(queryPartialSpansProjectsProjectIdSpansPartialSearchPostSecurity),
  );
}

/** @internal */
export type QueryPartialSpansProjectsProjectIdSpansPartialSearchPostRequest$Outbound =
  {
    project_id: string;
    body: models.LogRecordsPartialQueryRequest$Outbound;
  };

/** @internal */
export const QueryPartialSpansProjectsProjectIdSpansPartialSearchPostRequest$outboundSchema:
  z.ZodMiniType<
    QueryPartialSpansProjectsProjectIdSpansPartialSearchPostRequest$Outbound,
    QueryPartialSpansProjectsProjectIdSpansPartialSearchPostRequest
  > = z.pipe(
    z.object({
      projectId: z.string(),
      body: models.LogRecordsPartialQueryRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
      });
    }),
  );

export function queryPartialSpansProjectsProjectIdSpansPartialSearchPostRequestToJSON(
  queryPartialSpansProjectsProjectIdSpansPartialSearchPostRequest:
    QueryPartialSpansProjectsProjectIdSpansPartialSearchPostRequest,
): string {
  return JSON.stringify(
    QueryPartialSpansProjectsProjectIdSpansPartialSearchPostRequest$outboundSchema
      .parse(queryPartialSpansProjectsProjectIdSpansPartialSearchPostRequest),
  );
}
