/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type QueryTemplatesTemplatesQueryPostSecurity = {
  apiKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type QueryTemplatesTemplatesQueryPostRequest = {
  startingToken?: number | undefined;
  limit?: number | undefined;
  body?: models.ListPromptTemplateParams | undefined;
};

/** @internal */
export type QueryTemplatesTemplatesQueryPostSecurity$Outbound = {
  APIKeyHeader?: string | undefined;
  OAuth2PasswordBearer?: models.OAuth2PasswordBearerInput$Outbound | undefined;
  HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
};

/** @internal */
export const QueryTemplatesTemplatesQueryPostSecurity$outboundSchema:
  z.ZodMiniType<
    QueryTemplatesTemplatesQueryPostSecurity$Outbound,
    QueryTemplatesTemplatesQueryPostSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function queryTemplatesTemplatesQueryPostSecurityToJSON(
  queryTemplatesTemplatesQueryPostSecurity:
    QueryTemplatesTemplatesQueryPostSecurity,
): string {
  return JSON.stringify(
    QueryTemplatesTemplatesQueryPostSecurity$outboundSchema.parse(
      queryTemplatesTemplatesQueryPostSecurity,
    ),
  );
}

/** @internal */
export type QueryTemplatesTemplatesQueryPostRequest$Outbound = {
  starting_token: number;
  limit: number;
  body?: models.ListPromptTemplateParams$Outbound | undefined;
};

/** @internal */
export const QueryTemplatesTemplatesQueryPostRequest$outboundSchema:
  z.ZodMiniType<
    QueryTemplatesTemplatesQueryPostRequest$Outbound,
    QueryTemplatesTemplatesQueryPostRequest
  > = z.pipe(
    z.object({
      startingToken: z._default(z.int(), 0),
      limit: z._default(z.int(), 100),
      body: z.optional(models.ListPromptTemplateParams$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        startingToken: "starting_token",
      });
    }),
  );

export function queryTemplatesTemplatesQueryPostRequestToJSON(
  queryTemplatesTemplatesQueryPostRequest:
    QueryTemplatesTemplatesQueryPostRequest,
): string {
  return JSON.stringify(
    QueryTemplatesTemplatesQueryPostRequest$outboundSchema.parse(
      queryTemplatesTemplatesQueryPostRequest,
    ),
  );
}
