/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 01aa8456c123
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type QueryTemplateVersionsTemplatesTemplateIdVersionsQueryPostSecurity =
  {
    apiKeyHeader?: string | undefined;
    classicAPIKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type QueryTemplateVersionsTemplatesTemplateIdVersionsQueryPostRequest = {
  templateId: string;
  startingToken?: number | undefined;
  limit?: number | undefined;
  body?: models.ListPromptTemplateVersionParams | undefined;
};

/** @internal */
export type QueryTemplateVersionsTemplatesTemplateIdVersionsQueryPostSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    ClassicAPIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const QueryTemplateVersionsTemplatesTemplateIdVersionsQueryPostSecurity$outboundSchema:
  z.ZodMiniType<
    QueryTemplateVersionsTemplatesTemplateIdVersionsQueryPostSecurity$Outbound,
    QueryTemplateVersionsTemplatesTemplateIdVersionsQueryPostSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      classicAPIKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function queryTemplateVersionsTemplatesTemplateIdVersionsQueryPostSecurityToJSON(
  queryTemplateVersionsTemplatesTemplateIdVersionsQueryPostSecurity:
    QueryTemplateVersionsTemplatesTemplateIdVersionsQueryPostSecurity,
): string {
  return JSON.stringify(
    QueryTemplateVersionsTemplatesTemplateIdVersionsQueryPostSecurity$outboundSchema
      .parse(queryTemplateVersionsTemplatesTemplateIdVersionsQueryPostSecurity),
  );
}

/** @internal */
export type QueryTemplateVersionsTemplatesTemplateIdVersionsQueryPostRequest$Outbound =
  {
    template_id: string;
    starting_token: number;
    limit: number;
    body?: models.ListPromptTemplateVersionParams$Outbound | undefined;
  };

/** @internal */
export const QueryTemplateVersionsTemplatesTemplateIdVersionsQueryPostRequest$outboundSchema:
  z.ZodMiniType<
    QueryTemplateVersionsTemplatesTemplateIdVersionsQueryPostRequest$Outbound,
    QueryTemplateVersionsTemplatesTemplateIdVersionsQueryPostRequest
  > = z.pipe(
    z.object({
      templateId: z.string(),
      startingToken: z._default(z.int(), 0),
      limit: z._default(z.int(), 100),
      body: z.optional(models.ListPromptTemplateVersionParams$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        templateId: "template_id",
        startingToken: "starting_token",
      });
    }),
  );

export function queryTemplateVersionsTemplatesTemplateIdVersionsQueryPostRequestToJSON(
  queryTemplateVersionsTemplatesTemplateIdVersionsQueryPostRequest:
    QueryTemplateVersionsTemplatesTemplateIdVersionsQueryPostRequest,
): string {
  return JSON.stringify(
    QueryTemplateVersionsTemplatesTemplateIdVersionsQueryPostRequest$outboundSchema
      .parse(queryTemplateVersionsTemplatesTemplateIdVersionsQueryPostRequest),
  );
}
