/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1b3c58c58e5e
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type QueryPartialSessionsProjectsProjectIdSessionsPartialSearchPostSecurity =
  {
    apiKeyHeader?: string | undefined;
    classicAPIKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type QueryPartialSessionsProjectsProjectIdSessionsPartialSearchPostRequest =
  {
    projectId: string;
    body: models.LogRecordsPartialQueryRequest;
  };

/** @internal */
export type QueryPartialSessionsProjectsProjectIdSessionsPartialSearchPostSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    ClassicAPIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const QueryPartialSessionsProjectsProjectIdSessionsPartialSearchPostSecurity$outboundSchema:
  z.ZodMiniType<
    QueryPartialSessionsProjectsProjectIdSessionsPartialSearchPostSecurity$Outbound,
    QueryPartialSessionsProjectsProjectIdSessionsPartialSearchPostSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      classicAPIKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function queryPartialSessionsProjectsProjectIdSessionsPartialSearchPostSecurityToJSON(
  queryPartialSessionsProjectsProjectIdSessionsPartialSearchPostSecurity:
    QueryPartialSessionsProjectsProjectIdSessionsPartialSearchPostSecurity,
): string {
  return JSON.stringify(
    QueryPartialSessionsProjectsProjectIdSessionsPartialSearchPostSecurity$outboundSchema
      .parse(
        queryPartialSessionsProjectsProjectIdSessionsPartialSearchPostSecurity,
      ),
  );
}

/** @internal */
export type QueryPartialSessionsProjectsProjectIdSessionsPartialSearchPostRequest$Outbound =
  {
    project_id: string;
    body: models.LogRecordsPartialQueryRequest$Outbound;
  };

/** @internal */
export const QueryPartialSessionsProjectsProjectIdSessionsPartialSearchPostRequest$outboundSchema:
  z.ZodMiniType<
    QueryPartialSessionsProjectsProjectIdSessionsPartialSearchPostRequest$Outbound,
    QueryPartialSessionsProjectsProjectIdSessionsPartialSearchPostRequest
  > = z.pipe(
    z.object({
      projectId: z.string(),
      body: models.LogRecordsPartialQueryRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
      });
    }),
  );

export function queryPartialSessionsProjectsProjectIdSessionsPartialSearchPostRequestToJSON(
  queryPartialSessionsProjectsProjectIdSessionsPartialSearchPostRequest:
    QueryPartialSessionsProjectsProjectIdSessionsPartialSearchPostRequest,
): string {
  return JSON.stringify(
    QueryPartialSessionsProjectsProjectIdSessionsPartialSearchPostRequest$outboundSchema
      .parse(
        queryPartialSessionsProjectsProjectIdSessionsPartialSearchPostRequest,
      ),
  );
}
