/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 700981b051b7
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type SessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostSecurity =
  {
    classicAPIKeyHeader?: string | undefined;
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type SessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostRequest =
  {
    projectId: string;
    body: models.LogRecordsAvailableColumnsRequest;
  };

/** @internal */
export type SessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostSecurity$Outbound =
  {
    ClassicAPIKeyHeader?: string | undefined;
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const SessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostSecurity$outboundSchema:
  z.ZodMiniType<
    SessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostSecurity$Outbound,
    SessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostSecurity
  > = z.pipe(
    z.object({
      classicAPIKeyHeader: z.optional(z.string()),
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        classicAPIKeyHeader: "ClassicAPIKeyHeader",
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function sessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostSecurityToJSON(
  sessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostSecurity:
    SessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostSecurity,
): string {
  return JSON.stringify(
    SessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostSecurity$outboundSchema
      .parse(
        sessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostSecurity,
      ),
  );
}

/** @internal */
export type SessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostRequest$Outbound =
  {
    project_id: string;
    body: models.LogRecordsAvailableColumnsRequest$Outbound;
  };

/** @internal */
export const SessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostRequest$outboundSchema:
  z.ZodMiniType<
    SessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostRequest$Outbound,
    SessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostRequest
  > = z.pipe(
    z.object({
      projectId: z.string(),
      body: models.LogRecordsAvailableColumnsRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
      });
    }),
  );

export function sessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostRequestToJSON(
  sessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostRequest:
    SessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostRequest,
): string {
  return JSON.stringify(
    SessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostRequest$outboundSchema
      .parse(
        sessionsAvailableColumnsProjectsProjectIdSessionsAvailableColumnsPostRequest,
      ),
  );
}
