/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type SetTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostSecurity =
  {
    apiKeyHeader?: string | undefined;
    oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
    httpBasic?: models.SchemeHTTPBasic | undefined;
  };

export type SetTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostRequest =
  {
    projectId: string;
    experimentId: string;
    body: models.RunTagCreateRequest;
  };

/** @internal */
export type SetTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
    HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
  };

/** @internal */
export const SetTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostSecurity$outboundSchema:
  z.ZodMiniType<
    SetTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostSecurity$Outbound,
    SetTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function setTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostSecurityToJSON(
  setTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostSecurity:
    SetTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostSecurity,
): string {
  return JSON.stringify(
    SetTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostSecurity$outboundSchema
      .parse(
        setTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostSecurity,
      ),
  );
}

/** @internal */
export type SetTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostRequest$Outbound =
  {
    project_id: string;
    experiment_id: string;
    body: models.RunTagCreateRequest$Outbound;
  };

/** @internal */
export const SetTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostRequest$outboundSchema:
  z.ZodMiniType<
    SetTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostRequest$Outbound,
    SetTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostRequest
  > = z.pipe(
    z.object({
      projectId: z.string(),
      experimentId: z.string(),
      body: models.RunTagCreateRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
        experimentId: "experiment_id",
      });
    }),
  );

export function setTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostRequestToJSON(
  setTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostRequest:
    SetTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostRequest,
): string {
  return JSON.stringify(
    SetTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostRequest$outboundSchema
      .parse(
        setTagForExperimentProjectsProjectIdExperimentsExperimentIdTagsPostRequest,
      ),
  );
}
