/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateSpanProjectsProjectIdSpansSpanIdPatchSecurity = {
  apiKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
  httpBasic?: models.SchemeHTTPBasic | undefined;
};

export type UpdateSpanProjectsProjectIdSpansSpanIdPatchRequest = {
  spanId: string;
  projectId: string;
  body: models.LogSpanUpdateRequest;
};

/** @internal */
export type UpdateSpanProjectsProjectIdSpansSpanIdPatchSecurity$Outbound = {
  APIKeyHeader?: string | undefined;
  OAuth2PasswordBearer?: models.OAuth2PasswordBearerInput$Outbound | undefined;
  HTTPBasic?: models.SchemeHTTPBasic$Outbound | undefined;
};

/** @internal */
export const UpdateSpanProjectsProjectIdSpansSpanIdPatchSecurity$outboundSchema:
  z.ZodMiniType<
    UpdateSpanProjectsProjectIdSpansSpanIdPatchSecurity$Outbound,
    UpdateSpanProjectsProjectIdSpansSpanIdPatchSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
      httpBasic: z.optional(models.SchemeHTTPBasic$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
        httpBasic: "HTTPBasic",
      });
    }),
  );

export function updateSpanProjectsProjectIdSpansSpanIdPatchSecurityToJSON(
  updateSpanProjectsProjectIdSpansSpanIdPatchSecurity:
    UpdateSpanProjectsProjectIdSpansSpanIdPatchSecurity,
): string {
  return JSON.stringify(
    UpdateSpanProjectsProjectIdSpansSpanIdPatchSecurity$outboundSchema.parse(
      updateSpanProjectsProjectIdSpansSpanIdPatchSecurity,
    ),
  );
}

/** @internal */
export type UpdateSpanProjectsProjectIdSpansSpanIdPatchRequest$Outbound = {
  span_id: string;
  project_id: string;
  body: models.LogSpanUpdateRequest$Outbound;
};

/** @internal */
export const UpdateSpanProjectsProjectIdSpansSpanIdPatchRequest$outboundSchema:
  z.ZodMiniType<
    UpdateSpanProjectsProjectIdSpansSpanIdPatchRequest$Outbound,
    UpdateSpanProjectsProjectIdSpansSpanIdPatchRequest
  > = z.pipe(
    z.object({
      spanId: z.string(),
      projectId: z.string(),
      body: models.LogSpanUpdateRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        spanId: "span_id",
        projectId: "project_id",
      });
    }),
  );

export function updateSpanProjectsProjectIdSpansSpanIdPatchRequestToJSON(
  updateSpanProjectsProjectIdSpansSpanIdPatchRequest:
    UpdateSpanProjectsProjectIdSpansSpanIdPatchRequest,
): string {
  return JSON.stringify(
    UpdateSpanProjectsProjectIdSpansSpanIdPatchRequest$outboundSchema.parse(
      updateSpanProjectsProjectIdSpansSpanIdPatchRequest,
    ),
  );
}
