/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d16184ee94c2
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ValidateCodeScorerDatasetScorersCodeValidateDatasetPostSecurity = {
  apiKeyHeader?: string | undefined;
  oAuth2PasswordBearer?: models.OAuth2PasswordBearerInput | undefined;
};

/** @internal */
export type ValidateCodeScorerDatasetScorersCodeValidateDatasetPostSecurity$Outbound =
  {
    APIKeyHeader?: string | undefined;
    OAuth2PasswordBearer?:
      | models.OAuth2PasswordBearerInput$Outbound
      | undefined;
  };

/** @internal */
export const ValidateCodeScorerDatasetScorersCodeValidateDatasetPostSecurity$outboundSchema:
  z.ZodMiniType<
    ValidateCodeScorerDatasetScorersCodeValidateDatasetPostSecurity$Outbound,
    ValidateCodeScorerDatasetScorersCodeValidateDatasetPostSecurity
  > = z.pipe(
    z.object({
      apiKeyHeader: z.optional(z.string()),
      oAuth2PasswordBearer: z.optional(
        models.OAuth2PasswordBearerInput$outboundSchema,
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKeyHeader: "APIKeyHeader",
        oAuth2PasswordBearer: "OAuth2PasswordBearer",
      });
    }),
  );

export function validateCodeScorerDatasetScorersCodeValidateDatasetPostSecurityToJSON(
  validateCodeScorerDatasetScorersCodeValidateDatasetPostSecurity:
    ValidateCodeScorerDatasetScorersCodeValidateDatasetPostSecurity,
): string {
  return JSON.stringify(
    ValidateCodeScorerDatasetScorersCodeValidateDatasetPostSecurity$outboundSchema
      .parse(validateCodeScorerDatasetScorersCodeValidateDatasetPostSecurity),
  );
}
