/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cc00339f60fb
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  AnnotationQueueRecordsByFilterTree,
  AnnotationQueueRecordsByFilterTree$Outbound,
  AnnotationQueueRecordsByFilterTree$outboundSchema,
} from "./annotationqueuerecordsbyfiltertree.js";
import {
  AnnotationQueueRecordsByRecordIDs,
  AnnotationQueueRecordsByRecordIDs$Outbound,
  AnnotationQueueRecordsByRecordIDs$outboundSchema,
} from "./annotationqueuerecordsbyrecordids.js";

/**
 * Selector to specify which records to add (either by record IDs or filter tree)
 */
export type AddRecordsToQueueRequestRecordSelector =
  | AnnotationQueueRecordsByFilterTree
  | AnnotationQueueRecordsByRecordIDs;

/**
 * Request to add records to an annotation queue.
 */
export type AddRecordsToQueueRequest = {
  /**
   * Project ID containing the records
   */
  projectId: string;
  /**
   * Run ID (log stream, experiment, or metrics testing) containing the records
   */
  runId: string;
  /**
   * Selector to specify which records to add (either by record IDs or filter tree)
   */
  recordSelector:
    | AnnotationQueueRecordsByFilterTree
    | AnnotationQueueRecordsByRecordIDs;
};

/** @internal */
export type AddRecordsToQueueRequestRecordSelector$Outbound =
  | AnnotationQueueRecordsByFilterTree$Outbound
  | AnnotationQueueRecordsByRecordIDs$Outbound;

/** @internal */
export const AddRecordsToQueueRequestRecordSelector$outboundSchema:
  z.ZodMiniType<
    AddRecordsToQueueRequestRecordSelector$Outbound,
    AddRecordsToQueueRequestRecordSelector
  > = z.union([
    AnnotationQueueRecordsByFilterTree$outboundSchema,
    AnnotationQueueRecordsByRecordIDs$outboundSchema,
  ]);

export function addRecordsToQueueRequestRecordSelectorToJSON(
  addRecordsToQueueRequestRecordSelector:
    AddRecordsToQueueRequestRecordSelector,
): string {
  return JSON.stringify(
    AddRecordsToQueueRequestRecordSelector$outboundSchema.parse(
      addRecordsToQueueRequestRecordSelector,
    ),
  );
}

/** @internal */
export type AddRecordsToQueueRequest$Outbound = {
  project_id: string;
  run_id: string;
  record_selector:
    | AnnotationQueueRecordsByFilterTree$Outbound
    | AnnotationQueueRecordsByRecordIDs$Outbound;
};

/** @internal */
export const AddRecordsToQueueRequest$outboundSchema: z.ZodMiniType<
  AddRecordsToQueueRequest$Outbound,
  AddRecordsToQueueRequest
> = z.pipe(
  z.object({
    projectId: z.string(),
    runId: z.string(),
    recordSelector: z.union([
      AnnotationQueueRecordsByFilterTree$outboundSchema,
      AnnotationQueueRecordsByRecordIDs$outboundSchema,
    ]),
  }),
  z.transform((v) => {
    return remap$(v, {
      projectId: "project_id",
      runId: "run_id",
      recordSelector: "record_selector",
    });
  }),
);

export function addRecordsToQueueRequestToJSON(
  addRecordsToQueueRequest: AddRecordsToQueueRequest,
): string {
  return JSON.stringify(
    AddRecordsToQueueRequest$outboundSchema.parse(addRecordsToQueueRequest),
  );
}
