/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { AgentType, AgentType$outboundSchema } from "./agenttype.js";
import {
  Document,
  Document$Outbound,
  Document$outboundSchema,
} from "./document.js";
import {
  GalileoCoreSchemasLoggingLlmMessage,
  GalileoCoreSchemasLoggingLlmMessage$Outbound,
  GalileoCoreSchemasLoggingLlmMessage$outboundSchema,
} from "./galileocoreschemasloggingllmmessage.js";
import {
  LlmSpan,
  LlmSpan$Outbound,
  LlmSpan$outboundSchema,
} from "./llmspan.js";
import {
  Metrics,
  Metrics$Outbound,
  Metrics$outboundSchema,
} from "./metrics.js";
import {
  RetrieverSpan,
  RetrieverSpan$Outbound,
  RetrieverSpan$outboundSchema,
} from "./retrieverspan.js";
import {
  ToolSpan,
  ToolSpan$Outbound,
  ToolSpan$outboundSchema,
} from "./toolspan.js";
import {
  WorkflowSpan,
  WorkflowSpan$Outbound,
  WorkflowSpan$outboundSchema,
} from "./workflowspan.js";

/**
 * Input to the trace or span.
 */
export type AgentSpanInput =
  | string
  | Array<GalileoCoreSchemasLoggingLlmMessage>;

/**
 * Redacted input of the trace or span.
 */
export type AgentSpanRedactedInput =
  | string
  | Array<GalileoCoreSchemasLoggingLlmMessage>;

/**
 * Output of the trace or span.
 */
export type AgentSpanOutput =
  | GalileoCoreSchemasLoggingLlmMessage
  | string
  | Array<Document>;

/**
 * Redacted output of the trace or span.
 */
export type AgentSpanRedactedOutput =
  | GalileoCoreSchemasLoggingLlmMessage
  | string
  | Array<Document>;

export type AgentSpan = {
  /**
   * Type of the trace, span or session.
   */
  type: "agent";
  /**
   * Input to the trace or span.
   */
  input?: string | Array<GalileoCoreSchemasLoggingLlmMessage> | undefined;
  /**
   * Redacted input of the trace or span.
   */
  redactedInput?:
    | string
    | Array<GalileoCoreSchemasLoggingLlmMessage>
    | null
    | undefined;
  /**
   * Output of the trace or span.
   */
  output?:
    | GalileoCoreSchemasLoggingLlmMessage
    | string
    | Array<Document>
    | null
    | undefined;
  /**
   * Redacted output of the trace or span.
   */
  redactedOutput?:
    | GalileoCoreSchemasLoggingLlmMessage
    | string
    | Array<Document>
    | null
    | undefined;
  /**
   * Name of the trace, span or session.
   */
  name?: string | undefined;
  /**
   * Timestamp of the trace or span's creation.
   */
  createdAt?: Date | undefined;
  /**
   * Metadata associated with this trace or span.
   */
  userMetadata?: { [k: string]: string } | undefined;
  /**
   * Tags associated with this trace or span.
   */
  tags?: Array<string> | undefined;
  /**
   * Status code of the trace or span. Used for logging failure or error states.
   */
  statusCode?: number | null | undefined;
  metrics?: Metrics | undefined;
  /**
   * A user-provided session, trace or span ID.
   */
  externalId?: string | null | undefined;
  /**
   * Input to the dataset associated with this trace
   */
  datasetInput?: string | null | undefined;
  /**
   * Output from the dataset associated with this trace
   */
  datasetOutput?: string | null | undefined;
  /**
   * Metadata from the dataset associated with this trace
   */
  datasetMetadata?: { [k: string]: string } | undefined;
  /**
   * Galileo ID of the session, trace or span
   */
  id?: string | null | undefined;
  /**
   * Galileo ID of the session containing the trace or span or session
   */
  sessionId?: string | null | undefined;
  /**
   * Galileo ID of the trace containing the span (or the same value as id for a trace)
   */
  traceId?: string | null | undefined;
  /**
   * Topological step number of the span.
   */
  stepNumber?: number | null | undefined;
  /**
   * Galileo ID of the parent of this span
   */
  parentId?: string | null | undefined;
  /**
   * Child spans.
   */
  spans?:
    | Array<AgentSpan | LlmSpan | RetrieverSpan | ToolSpan | WorkflowSpan>
    | undefined;
  agentType?: AgentType | undefined;
};

export type AgentSpanSpan =
  | AgentSpan
  | LlmSpan
  | RetrieverSpan
  | ToolSpan
  | WorkflowSpan;

/** @internal */
export type AgentSpanInput$Outbound =
  | string
  | Array<GalileoCoreSchemasLoggingLlmMessage$Outbound>;

/** @internal */
export const AgentSpanInput$outboundSchema: z.ZodMiniType<
  AgentSpanInput$Outbound,
  AgentSpanInput
> = smartUnion([
  z.string(),
  z.array(GalileoCoreSchemasLoggingLlmMessage$outboundSchema),
]);

export function agentSpanInputToJSON(agentSpanInput: AgentSpanInput): string {
  return JSON.stringify(AgentSpanInput$outboundSchema.parse(agentSpanInput));
}

/** @internal */
export type AgentSpanRedactedInput$Outbound =
  | string
  | Array<GalileoCoreSchemasLoggingLlmMessage$Outbound>;

/** @internal */
export const AgentSpanRedactedInput$outboundSchema: z.ZodMiniType<
  AgentSpanRedactedInput$Outbound,
  AgentSpanRedactedInput
> = smartUnion([
  z.string(),
  z.array(GalileoCoreSchemasLoggingLlmMessage$outboundSchema),
]);

export function agentSpanRedactedInputToJSON(
  agentSpanRedactedInput: AgentSpanRedactedInput,
): string {
  return JSON.stringify(
    AgentSpanRedactedInput$outboundSchema.parse(agentSpanRedactedInput),
  );
}

/** @internal */
export type AgentSpanOutput$Outbound =
  | GalileoCoreSchemasLoggingLlmMessage$Outbound
  | string
  | Array<Document$Outbound>;

/** @internal */
export const AgentSpanOutput$outboundSchema: z.ZodMiniType<
  AgentSpanOutput$Outbound,
  AgentSpanOutput
> = smartUnion([
  GalileoCoreSchemasLoggingLlmMessage$outboundSchema,
  z.string(),
  z.array(Document$outboundSchema),
]);

export function agentSpanOutputToJSON(
  agentSpanOutput: AgentSpanOutput,
): string {
  return JSON.stringify(AgentSpanOutput$outboundSchema.parse(agentSpanOutput));
}

/** @internal */
export type AgentSpanRedactedOutput$Outbound =
  | GalileoCoreSchemasLoggingLlmMessage$Outbound
  | string
  | Array<Document$Outbound>;

/** @internal */
export const AgentSpanRedactedOutput$outboundSchema: z.ZodMiniType<
  AgentSpanRedactedOutput$Outbound,
  AgentSpanRedactedOutput
> = smartUnion([
  GalileoCoreSchemasLoggingLlmMessage$outboundSchema,
  z.string(),
  z.array(Document$outboundSchema),
]);

export function agentSpanRedactedOutputToJSON(
  agentSpanRedactedOutput: AgentSpanRedactedOutput,
): string {
  return JSON.stringify(
    AgentSpanRedactedOutput$outboundSchema.parse(agentSpanRedactedOutput),
  );
}

/** @internal */
export type AgentSpan$Outbound = {
  type: "agent";
  input?:
    | string
    | Array<GalileoCoreSchemasLoggingLlmMessage$Outbound>
    | undefined;
  redacted_input?:
    | string
    | Array<GalileoCoreSchemasLoggingLlmMessage$Outbound>
    | null
    | undefined;
  output?:
    | GalileoCoreSchemasLoggingLlmMessage$Outbound
    | string
    | Array<Document$Outbound>
    | null
    | undefined;
  redacted_output?:
    | GalileoCoreSchemasLoggingLlmMessage$Outbound
    | string
    | Array<Document$Outbound>
    | null
    | undefined;
  name: string;
  created_at?: string | undefined;
  user_metadata?: { [k: string]: string } | undefined;
  tags?: Array<string> | undefined;
  status_code?: number | null | undefined;
  metrics?: Metrics$Outbound | undefined;
  external_id?: string | null | undefined;
  dataset_input?: string | null | undefined;
  dataset_output?: string | null | undefined;
  dataset_metadata?: { [k: string]: string } | undefined;
  id?: string | null | undefined;
  session_id?: string | null | undefined;
  trace_id?: string | null | undefined;
  step_number?: number | null | undefined;
  parent_id?: string | null | undefined;
  spans?:
    | Array<
      | AgentSpan$Outbound
      | LlmSpan$Outbound
      | RetrieverSpan$Outbound
      | ToolSpan$Outbound
      | WorkflowSpan$Outbound
    >
    | undefined;
  agent_type?: string | undefined;
};

/** @internal */
export const AgentSpan$outboundSchema: z.ZodMiniType<
  AgentSpan$Outbound,
  AgentSpan
> = z.pipe(
  z.object({
    type: z.literal("agent"),
    input: z.optional(
      smartUnion([
        z.string(),
        z.array(GalileoCoreSchemasLoggingLlmMessage$outboundSchema),
      ]),
    ),
    redactedInput: z.optional(
      z.nullable(
        smartUnion([
          z.string(),
          z.array(GalileoCoreSchemasLoggingLlmMessage$outboundSchema),
        ]),
      ),
    ),
    output: z.optional(
      z.nullable(
        smartUnion([
          GalileoCoreSchemasLoggingLlmMessage$outboundSchema,
          z.string(),
          z.array(Document$outboundSchema),
        ]),
      ),
    ),
    redactedOutput: z.optional(
      z.nullable(
        smartUnion([
          GalileoCoreSchemasLoggingLlmMessage$outboundSchema,
          z.string(),
          z.array(Document$outboundSchema),
        ]),
      ),
    ),
    name: z._default(z.string(), ""),
    createdAt: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    userMetadata: z.optional(z.record(z.string(), z.string())),
    tags: z.optional(z.array(z.string())),
    statusCode: z.optional(z.nullable(z.int())),
    metrics: z.optional(Metrics$outboundSchema),
    externalId: z.optional(z.nullable(z.string())),
    datasetInput: z.optional(z.nullable(z.string())),
    datasetOutput: z.optional(z.nullable(z.string())),
    datasetMetadata: z.optional(z.record(z.string(), z.string())),
    id: z.optional(z.nullable(z.string())),
    sessionId: z.optional(z.nullable(z.string())),
    traceId: z.optional(z.nullable(z.string())),
    stepNumber: z.optional(z.nullable(z.int())),
    parentId: z.optional(z.nullable(z.string())),
    spans: z.optional(z.array(z.union([
      z.lazy(() => AgentSpan$outboundSchema),
      LlmSpan$outboundSchema,
      z.lazy(() => RetrieverSpan$outboundSchema),
      z.lazy(() =>
        ToolSpan$outboundSchema
      ),
      z.lazy(() => WorkflowSpan$outboundSchema),
    ]))),
    agentType: z.optional(AgentType$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      redactedInput: "redacted_input",
      redactedOutput: "redacted_output",
      createdAt: "created_at",
      userMetadata: "user_metadata",
      statusCode: "status_code",
      externalId: "external_id",
      datasetInput: "dataset_input",
      datasetOutput: "dataset_output",
      datasetMetadata: "dataset_metadata",
      sessionId: "session_id",
      traceId: "trace_id",
      stepNumber: "step_number",
      parentId: "parent_id",
      agentType: "agent_type",
    });
  }),
);

export function agentSpanToJSON(agentSpan: AgentSpan): string {
  return JSON.stringify(AgentSpan$outboundSchema.parse(agentSpan));
}

/** @internal */
export type AgentSpanSpan$Outbound =
  | AgentSpan$Outbound
  | LlmSpan$Outbound
  | RetrieverSpan$Outbound
  | ToolSpan$Outbound
  | WorkflowSpan$Outbound;

/** @internal */
export const AgentSpanSpan$outboundSchema: z.ZodMiniType<
  AgentSpanSpan$Outbound,
  AgentSpanSpan
> = z.union([
  z.lazy(() => AgentSpan$outboundSchema),
  LlmSpan$outboundSchema,
  z.lazy(() => RetrieverSpan$outboundSchema),
  z.lazy(() => ToolSpan$outboundSchema),
  z.lazy(() => WorkflowSpan$outboundSchema),
]);

export function agentSpanSpanToJSON(agentSpanSpan: AgentSpanSpan): string {
  return JSON.stringify(AgentSpanSpan$outboundSchema.parse(agentSpanSpan));
}
