/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AggregatedTraceViewGraph,
  AggregatedTraceViewGraph$inboundSchema,
} from "./aggregatedtraceviewgraph.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AggregatedTraceViewResponse = {
  graph: AggregatedTraceViewGraph;
  /**
   * Number of traces in the aggregated view
   */
  numTraces: number;
  /**
   * Number of sessions in the aggregated view
   */
  numSessions: number;
  /**
   * created_at of earliest record of the aggregated view
   */
  startTime?: Date | null | undefined;
  /**
   * created_at of latest record of the aggregated view
   */
  endTime?: Date | null | undefined;
  /**
   * Whether all traces were returned
   */
  hasAllTraces: boolean;
};

/** @internal */
export const AggregatedTraceViewResponse$inboundSchema: z.ZodMiniType<
  AggregatedTraceViewResponse,
  unknown
> = z.pipe(
  z.object({
    graph: AggregatedTraceViewGraph$inboundSchema,
    num_traces: types.number(),
    num_sessions: types.number(),
    start_time: z.optional(z.nullable(types.date())),
    end_time: z.optional(z.nullable(types.date())),
    has_all_traces: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "num_traces": "numTraces",
      "num_sessions": "numSessions",
      "start_time": "startTime",
      "end_time": "endTime",
      "has_all_traces": "hasAllTraces",
    });
  }),
);

export function aggregatedTraceViewResponseFromJSON(
  jsonString: string,
): SafeParseResult<AggregatedTraceViewResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AggregatedTraceViewResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AggregatedTraceViewResponse' from JSON`,
  );
}
