/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 96c372b9a676
 */

import * as z from "zod/v4-mini";
import {
  ApiSchemasAnnotationChoiceRating,
  ApiSchemasAnnotationChoiceRating$Outbound,
  ApiSchemasAnnotationChoiceRating$outboundSchema,
} from "./apischemasannotationchoicerating.js";
import {
  ApiSchemasAnnotationLikeDislikeRating,
  ApiSchemasAnnotationLikeDislikeRating$Outbound,
  ApiSchemasAnnotationLikeDislikeRating$outboundSchema,
} from "./apischemasannotationlikedislikerating.js";
import {
  ApiSchemasAnnotationScoreRating,
  ApiSchemasAnnotationScoreRating$Outbound,
  ApiSchemasAnnotationScoreRating$outboundSchema,
} from "./apischemasannotationscorerating.js";
import {
  ApiSchemasAnnotationStarRating,
  ApiSchemasAnnotationStarRating$Outbound,
  ApiSchemasAnnotationStarRating$outboundSchema,
} from "./apischemasannotationstarrating.js";
import {
  ApiSchemasAnnotationTagsRating,
  ApiSchemasAnnotationTagsRating$Outbound,
  ApiSchemasAnnotationTagsRating$outboundSchema,
} from "./apischemasannotationtagsrating.js";
import {
  ApiSchemasAnnotationTextRating,
  ApiSchemasAnnotationTextRating$Outbound,
  ApiSchemasAnnotationTextRating$outboundSchema,
} from "./apischemasannotationtextrating.js";
import {
  ApiSchemasAnnotationTreeChoiceRating,
  ApiSchemasAnnotationTreeChoiceRating$Outbound,
  ApiSchemasAnnotationTreeChoiceRating$outboundSchema,
} from "./apischemasannotationtreechoicerating.js";

export type AnnotationRatingCreateRating =
  | ApiSchemasAnnotationChoiceRating
  | ApiSchemasAnnotationLikeDislikeRating
  | ApiSchemasAnnotationScoreRating
  | ApiSchemasAnnotationStarRating
  | ApiSchemasAnnotationTagsRating
  | ApiSchemasAnnotationTextRating
  | ApiSchemasAnnotationTreeChoiceRating;

export type AnnotationRatingCreate = {
  explanation?: string | null | undefined;
  rating:
    | ApiSchemasAnnotationChoiceRating
    | ApiSchemasAnnotationLikeDislikeRating
    | ApiSchemasAnnotationScoreRating
    | ApiSchemasAnnotationStarRating
    | ApiSchemasAnnotationTagsRating
    | ApiSchemasAnnotationTextRating
    | ApiSchemasAnnotationTreeChoiceRating;
};

/** @internal */
export type AnnotationRatingCreateRating$Outbound =
  | ApiSchemasAnnotationChoiceRating$Outbound
  | ApiSchemasAnnotationLikeDislikeRating$Outbound
  | ApiSchemasAnnotationScoreRating$Outbound
  | ApiSchemasAnnotationStarRating$Outbound
  | ApiSchemasAnnotationTagsRating$Outbound
  | ApiSchemasAnnotationTextRating$Outbound
  | ApiSchemasAnnotationTreeChoiceRating$Outbound;

/** @internal */
export const AnnotationRatingCreateRating$outboundSchema: z.ZodMiniType<
  AnnotationRatingCreateRating$Outbound,
  AnnotationRatingCreateRating
> = z.union([
  ApiSchemasAnnotationChoiceRating$outboundSchema,
  ApiSchemasAnnotationLikeDislikeRating$outboundSchema,
  ApiSchemasAnnotationScoreRating$outboundSchema,
  ApiSchemasAnnotationStarRating$outboundSchema,
  ApiSchemasAnnotationTagsRating$outboundSchema,
  ApiSchemasAnnotationTextRating$outboundSchema,
  ApiSchemasAnnotationTreeChoiceRating$outboundSchema,
]);

export function annotationRatingCreateRatingToJSON(
  annotationRatingCreateRating: AnnotationRatingCreateRating,
): string {
  return JSON.stringify(
    AnnotationRatingCreateRating$outboundSchema.parse(
      annotationRatingCreateRating,
    ),
  );
}

/** @internal */
export type AnnotationRatingCreate$Outbound = {
  explanation?: string | null | undefined;
  rating:
    | ApiSchemasAnnotationChoiceRating$Outbound
    | ApiSchemasAnnotationLikeDislikeRating$Outbound
    | ApiSchemasAnnotationScoreRating$Outbound
    | ApiSchemasAnnotationStarRating$Outbound
    | ApiSchemasAnnotationTagsRating$Outbound
    | ApiSchemasAnnotationTextRating$Outbound
    | ApiSchemasAnnotationTreeChoiceRating$Outbound;
};

/** @internal */
export const AnnotationRatingCreate$outboundSchema: z.ZodMiniType<
  AnnotationRatingCreate$Outbound,
  AnnotationRatingCreate
> = z.object({
  explanation: z.optional(z.nullable(z.string())),
  rating: z.union([
    ApiSchemasAnnotationChoiceRating$outboundSchema,
    ApiSchemasAnnotationLikeDislikeRating$outboundSchema,
    ApiSchemasAnnotationScoreRating$outboundSchema,
    ApiSchemasAnnotationStarRating$outboundSchema,
    ApiSchemasAnnotationTagsRating$outboundSchema,
    ApiSchemasAnnotationTextRating$outboundSchema,
    ApiSchemasAnnotationTreeChoiceRating$outboundSchema,
  ]),
});

export function annotationRatingCreateToJSON(
  annotationRatingCreate: AnnotationRatingCreate,
): string {
  return JSON.stringify(
    AnnotationRatingCreate$outboundSchema.parse(annotationRatingCreate),
  );
}
