/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 857f6b8f207d
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type AnnotationQueueNumUsersSort = {
  name: "num_users";
  ascending?: boolean | undefined;
  sortType?: "column" | undefined;
};

/** @internal */
export type AnnotationQueueNumUsersSort$Outbound = {
  name: "num_users";
  ascending: boolean;
  sort_type: "column";
};

/** @internal */
export const AnnotationQueueNumUsersSort$outboundSchema: z.ZodMiniType<
  AnnotationQueueNumUsersSort$Outbound,
  AnnotationQueueNumUsersSort
> = z.pipe(
  z.object({
    name: z.literal("num_users"),
    ascending: z._default(z.boolean(), true),
    sortType: z._default(z.literal("column"), "column" as const),
  }),
  z.transform((v) => {
    return remap$(v, {
      sortType: "sort_type",
    });
  }),
);

export function annotationQueueNumUsersSortToJSON(
  annotationQueueNumUsersSort: AnnotationQueueNumUsersSort,
): string {
  return JSON.stringify(
    AnnotationQueueNumUsersSort$outboundSchema.parse(
      annotationQueueNumUsersSort,
    ),
  );
}
