/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 35cdeac05fb5
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AnnotationChoiceAggregate,
  AnnotationChoiceAggregate$inboundSchema,
} from "./annotationchoiceaggregate.js";
import {
  AnnotationLikeDislikeAggregate,
  AnnotationLikeDislikeAggregate$inboundSchema,
} from "./annotationlikedislikeaggregate.js";
import {
  AnnotationScoreAggregate,
  AnnotationScoreAggregate$inboundSchema,
} from "./annotationscoreaggregate.js";
import {
  AnnotationStarAggregate,
  AnnotationStarAggregate$inboundSchema,
} from "./annotationstaraggregate.js";
import {
  AnnotationTagsAggregate,
  AnnotationTagsAggregate$inboundSchema,
} from "./annotationtagsaggregate.js";
import {
  AnnotationTextAggregate,
  AnnotationTextAggregate$inboundSchema,
} from "./annotationtextaggregate.js";
import {
  AnnotationTreeChoiceAggregate,
  AnnotationTreeChoiceAggregate$inboundSchema,
} from "./annotationtreechoiceaggregate.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AnnotationAggregateAggregate =
  | AnnotationChoiceAggregate
  | AnnotationLikeDislikeAggregate
  | AnnotationScoreAggregate
  | AnnotationStarAggregate
  | AnnotationTagsAggregate
  | AnnotationTextAggregate
  | AnnotationTreeChoiceAggregate
  | discriminatedUnionTypes.Unknown<"annotationType">;

export type AnnotationAggregate = {
  aggregate:
    | AnnotationChoiceAggregate
    | AnnotationLikeDislikeAggregate
    | AnnotationScoreAggregate
    | AnnotationStarAggregate
    | AnnotationTagsAggregate
    | AnnotationTextAggregate
    | AnnotationTreeChoiceAggregate
    | discriminatedUnionTypes.Unknown<"annotationType">;
};

/** @internal */
export const AnnotationAggregateAggregate$inboundSchema: z.ZodMiniType<
  AnnotationAggregateAggregate,
  unknown
> = discriminatedUnion("annotation_type", {
  choice: AnnotationChoiceAggregate$inboundSchema,
  like_dislike: AnnotationLikeDislikeAggregate$inboundSchema,
  score: AnnotationScoreAggregate$inboundSchema,
  star: AnnotationStarAggregate$inboundSchema,
  tags: AnnotationTagsAggregate$inboundSchema,
  text: AnnotationTextAggregate$inboundSchema,
  tree_choice: AnnotationTreeChoiceAggregate$inboundSchema,
}, { outputPropertyName: "annotationType" });

export function annotationAggregateAggregateFromJSON(
  jsonString: string,
): SafeParseResult<AnnotationAggregateAggregate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnnotationAggregateAggregate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnnotationAggregateAggregate' from JSON`,
  );
}

/** @internal */
export const AnnotationAggregate$inboundSchema: z.ZodMiniType<
  AnnotationAggregate,
  unknown
> = z.object({
  aggregate: discriminatedUnion("annotation_type", {
    choice: AnnotationChoiceAggregate$inboundSchema,
    like_dislike: AnnotationLikeDislikeAggregate$inboundSchema,
    score: AnnotationScoreAggregate$inboundSchema,
    star: AnnotationStarAggregate$inboundSchema,
    tags: AnnotationTagsAggregate$inboundSchema,
    text: AnnotationTextAggregate$inboundSchema,
    tree_choice: AnnotationTreeChoiceAggregate$inboundSchema,
  }, { outputPropertyName: "annotationType" }),
});

export function annotationAggregateFromJSON(
  jsonString: string,
): SafeParseResult<AnnotationAggregate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnnotationAggregate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnnotationAggregate' from JSON`,
  );
}
