/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fb1d9cb563fc
 */

import * as z from "zod/v4-mini";

/**
 * Request to re-order the annotation templates of a project.
 *
 * @remarks
 *
 * - Expects a list of strings where each string is the ID of a template in the project in the order
 * we want the templates to appear in.
 * - Expects the list to be complete list of all template IDs.
 */
export type AnnotationTemplateReorder = {
  ordering: Array<string>;
};

/** @internal */
export type AnnotationTemplateReorder$Outbound = {
  ordering: Array<string>;
};

/** @internal */
export const AnnotationTemplateReorder$outboundSchema: z.ZodMiniType<
  AnnotationTemplateReorder$Outbound,
  AnnotationTemplateReorder
> = z.object({
  ordering: z.array(z.string()),
});

export function annotationTemplateReorderToJSON(
  annotationTemplateReorder: AnnotationTemplateReorder,
): string {
  return JSON.stringify(
    AnnotationTemplateReorder$outboundSchema.parse(annotationTemplateReorder),
  );
}
