/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Roll up methods for aggregating numeric metrics up the session/trace/span hierarchy.
 */
export const ApiSchemasMetricRollUpNumericRollUpMethod = {
  Average: "average",
  Sum: "sum",
  Max: "max",
  Min: "min",
} as const;
/**
 * Roll up methods for aggregating numeric metrics up the session/trace/span hierarchy.
 */
export type ApiSchemasMetricRollUpNumericRollUpMethod = OpenEnum<
  typeof ApiSchemasMetricRollUpNumericRollUpMethod
>;

/** @internal */
export const ApiSchemasMetricRollUpNumericRollUpMethod$inboundSchema:
  z.ZodMiniType<ApiSchemasMetricRollUpNumericRollUpMethod, unknown> = openEnums
    .inboundSchema(ApiSchemasMetricRollUpNumericRollUpMethod);
/** @internal */
export const ApiSchemasMetricRollUpNumericRollUpMethod$outboundSchema:
  z.ZodMiniType<string, ApiSchemasMetricRollUpNumericRollUpMethod> = openEnums
    .outboundSchema(ApiSchemasMetricRollUpNumericRollUpMethod);
