/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fe3422247e8a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { ProjectItem, ProjectItem$inboundSchema } from "./projectitem.js";

/**
 * Response model for the V2 projects paginated endpoint.
 */
export type ApiSchemasProjectV2GetProjectsPaginatedResponse = {
  startingToken: number;
  limit: number;
  paginated: boolean;
  nextStartingToken?: number | null | undefined;
  projects: Array<ProjectItem>;
  /**
   * Total number of projects matching the filters.
   */
  totalCount: number;
};

/** @internal */
export const ApiSchemasProjectV2GetProjectsPaginatedResponse$inboundSchema:
  z.ZodMiniType<ApiSchemasProjectV2GetProjectsPaginatedResponse, unknown> = z
    .pipe(
      z.object({
        starting_token: z._default(types.number(), 0),
        limit: z._default(types.number(), 100),
        paginated: z._default(types.boolean(), false),
        next_starting_token: z.optional(z.nullable(types.number())),
        projects: z.array(ProjectItem$inboundSchema),
        total_count: types.number(),
      }),
      z.transform((v) => {
        return remap$(v, {
          "starting_token": "startingToken",
          "next_starting_token": "nextStartingToken",
          "total_count": "totalCount",
        });
      }),
    );

export function apiSchemasProjectV2GetProjectsPaginatedResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiSchemasProjectV2GetProjectsPaginatedResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSchemasProjectV2GetProjectsPaginatedResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiSchemasProjectV2GetProjectsPaginatedResponse' from JSON`,
  );
}
