/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Details about a failed deletion.
 */
export type ApiSchemasContentDatasetBulkDeleteFailure = {
  datasetId: string;
  datasetName: string;
  reason: string;
};

/** @internal */
export const ApiSchemasContentDatasetBulkDeleteFailure$inboundSchema:
  z.ZodMiniType<ApiSchemasContentDatasetBulkDeleteFailure, unknown> = z.pipe(
    z.object({
      dataset_id: types.string(),
      dataset_name: types.string(),
      reason: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "dataset_id": "datasetId",
        "dataset_name": "datasetName",
      });
    }),
  );

export function apiSchemasContentDatasetBulkDeleteFailureFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiSchemasContentDatasetBulkDeleteFailure,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSchemasContentDatasetBulkDeleteFailure$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiSchemasContentDatasetBulkDeleteFailure' from JSON`,
  );
}
