/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: afb6966760fd
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ApiSchemasAnnotationTextRating = {
  annotationType: "text";
  value: string;
};

/** @internal */
export const ApiSchemasAnnotationTextRating$inboundSchema: z.ZodMiniType<
  ApiSchemasAnnotationTextRating,
  unknown
> = z.pipe(
  z.object({
    annotation_type: types.literal("text"),
    value: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "annotation_type": "annotationType",
    });
  }),
);
/** @internal */
export type ApiSchemasAnnotationTextRating$Outbound = {
  annotation_type: "text";
  value: string;
};

/** @internal */
export const ApiSchemasAnnotationTextRating$outboundSchema: z.ZodMiniType<
  ApiSchemasAnnotationTextRating$Outbound,
  ApiSchemasAnnotationTextRating
> = z.pipe(
  z.object({
    annotationType: z.literal("text"),
    value: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      annotationType: "annotation_type",
    });
  }),
);

export function apiSchemasAnnotationTextRatingToJSON(
  apiSchemasAnnotationTextRating: ApiSchemasAnnotationTextRating,
): string {
  return JSON.stringify(
    ApiSchemasAnnotationTextRating$outboundSchema.parse(
      apiSchemasAnnotationTextRating,
    ),
  );
}
export function apiSchemasAnnotationTextRatingFromJSON(
  jsonString: string,
): SafeParseResult<ApiSchemasAnnotationTextRating, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSchemasAnnotationTextRating$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSchemasAnnotationTextRating' from JSON`,
  );
}
