/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8c8342da9701
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ApiSchemasAnnotationChoiceRating = {
  annotationType: "choice";
  value: string;
};

/** @internal */
export const ApiSchemasAnnotationChoiceRating$inboundSchema: z.ZodMiniType<
  ApiSchemasAnnotationChoiceRating,
  unknown
> = z.pipe(
  z.object({
    annotation_type: types.literal("choice"),
    value: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "annotation_type": "annotationType",
    });
  }),
);
/** @internal */
export type ApiSchemasAnnotationChoiceRating$Outbound = {
  annotation_type: "choice";
  value: string;
};

/** @internal */
export const ApiSchemasAnnotationChoiceRating$outboundSchema: z.ZodMiniType<
  ApiSchemasAnnotationChoiceRating$Outbound,
  ApiSchemasAnnotationChoiceRating
> = z.pipe(
  z.object({
    annotationType: z.literal("choice"),
    value: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      annotationType: "annotation_type",
    });
  }),
);

export function apiSchemasAnnotationChoiceRatingToJSON(
  apiSchemasAnnotationChoiceRating: ApiSchemasAnnotationChoiceRating,
): string {
  return JSON.stringify(
    ApiSchemasAnnotationChoiceRating$outboundSchema.parse(
      apiSchemasAnnotationChoiceRating,
    ),
  );
}
export function apiSchemasAnnotationChoiceRatingFromJSON(
  jsonString: string,
): SafeParseResult<ApiSchemasAnnotationChoiceRating, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSchemasAnnotationChoiceRating$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSchemasAnnotationChoiceRating' from JSON`,
  );
}
