/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4da550e749ae
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ApiSchemasAnnotationStarRating = {
  annotationType: "star";
  value: number;
};

/** @internal */
export const ApiSchemasAnnotationStarRating$inboundSchema: z.ZodMiniType<
  ApiSchemasAnnotationStarRating,
  unknown
> = z.pipe(
  z.object({
    annotation_type: types.literal("star"),
    value: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "annotation_type": "annotationType",
    });
  }),
);
/** @internal */
export type ApiSchemasAnnotationStarRating$Outbound = {
  annotation_type: "star";
  value: number;
};

/** @internal */
export const ApiSchemasAnnotationStarRating$outboundSchema: z.ZodMiniType<
  ApiSchemasAnnotationStarRating$Outbound,
  ApiSchemasAnnotationStarRating
> = z.pipe(
  z.object({
    annotationType: z.literal("star"),
    value: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      annotationType: "annotation_type",
    });
  }),
);

export function apiSchemasAnnotationStarRatingToJSON(
  apiSchemasAnnotationStarRating: ApiSchemasAnnotationStarRating,
): string {
  return JSON.stringify(
    ApiSchemasAnnotationStarRating$outboundSchema.parse(
      apiSchemasAnnotationStarRating,
    ),
  );
}
export function apiSchemasAnnotationStarRatingFromJSON(
  jsonString: string,
): SafeParseResult<ApiSchemasAnnotationStarRating, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSchemasAnnotationStarRating$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSchemasAnnotationStarRating' from JSON`,
  );
}
