/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8f1e8d93d366
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AwsCredentialType,
  AwsCredentialType$inboundSchema,
} from "./awscredentialtype.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AwsBedrockIntegration = {
  credentialType?: AwsCredentialType | undefined;
  region: string;
  /**
   * Mapping from model name (Foundation model ID) to inference profile ARN or ID
   */
  inferenceProfiles?: { [k: string]: string } | undefined;
  id?: string | null | undefined;
  name: "aws_bedrock";
  extra?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const AwsBedrockIntegration$inboundSchema: z.ZodMiniType<
  AwsBedrockIntegration,
  unknown
> = z.pipe(
  z.object({
    credential_type: types.optional(AwsCredentialType$inboundSchema),
    region: z._default(types.string(), "us-west-2"),
    inference_profiles: types.optional(z.record(z.string(), types.string())),
    id: z.optional(z.nullable(types.string())),
    name: types.literal("aws_bedrock"),
    extra: z.optional(z.nullable(z.record(z.string(), z.any()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "credential_type": "credentialType",
      "inference_profiles": "inferenceProfiles",
    });
  }),
);

export function awsBedrockIntegrationFromJSON(
  jsonString: string,
): SafeParseResult<AwsBedrockIntegration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AwsBedrockIntegration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AwsBedrockIntegration' from JSON`,
  );
}
