/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8ec2e6815ff3
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  AwsCredentialType,
  AwsCredentialType$outboundSchema,
} from "./awscredentialtype.js";
import { Model, Model$Outbound, Model$outboundSchema } from "./model.js";

export type AwsSageMakerIntegrationCreate = {
  models?: Array<Model> | undefined;
  credentialType?: AwsCredentialType | undefined;
  region?: string | undefined;
  /**
   * Mapping from model name (Foundation model ID) to inference profile ARN or ID
   */
  inferenceProfiles?: { [k: string]: string } | undefined;
  token: { [k: string]: string };
};

/** @internal */
export type AwsSageMakerIntegrationCreate$Outbound = {
  models?: Array<Model$Outbound> | undefined;
  credential_type?: string | undefined;
  region: string;
  inference_profiles?: { [k: string]: string } | undefined;
  token: { [k: string]: string };
};

/** @internal */
export const AwsSageMakerIntegrationCreate$outboundSchema: z.ZodMiniType<
  AwsSageMakerIntegrationCreate$Outbound,
  AwsSageMakerIntegrationCreate
> = z.pipe(
  z.object({
    models: z.optional(z.array(Model$outboundSchema)),
    credentialType: z.optional(AwsCredentialType$outboundSchema),
    region: z._default(z.string(), "us-west-2"),
    inferenceProfiles: z.optional(z.record(z.string(), z.string())),
    token: z.record(z.string(), z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      credentialType: "credential_type",
      inferenceProfiles: "inference_profiles",
    });
  }),
);

export function awsSageMakerIntegrationCreateToJSON(
  awsSageMakerIntegrationCreate: AwsSageMakerIntegrationCreate,
): string {
  return JSON.stringify(
    AwsSageMakerIntegrationCreate$outboundSchema.parse(
      awsSageMakerIntegrationCreate,
    ),
  );
}
