/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 86cb0ea77a01
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  CategoricalRollUpMethod,
  CategoricalRollUpMethod$inboundSchema,
  CategoricalRollUpMethod$outboundSchema,
} from "./categoricalrollupmethod.js";
import {
  ChainPollTemplate,
  ChainPollTemplate$inboundSchema,
  ChainPollTemplate$Outbound,
  ChainPollTemplate$outboundSchema,
} from "./chainpolltemplate.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  InputTypeEnum,
  InputTypeEnum$inboundSchema,
  InputTypeEnum$outboundSchema,
} from "./inputtypeenum.js";
import {
  LunaInputTypeEnum,
  LunaInputTypeEnum$inboundSchema,
  LunaInputTypeEnum$outboundSchema,
} from "./lunainputtypeenum.js";
import {
  LunaOutputTypeEnum,
  LunaOutputTypeEnum$inboundSchema,
  LunaOutputTypeEnum$outboundSchema,
} from "./lunaoutputtypeenum.js";
import {
  MetadataFilter,
  MetadataFilter$inboundSchema,
  MetadataFilter$Outbound,
  MetadataFilter$outboundSchema,
} from "./metadatafilter.js";
import {
  ModalityFilter,
  ModalityFilter$inboundSchema,
  ModalityFilter$Outbound,
  ModalityFilter$outboundSchema,
} from "./modalityfilter.js";
import {
  MultimodalCapability,
  MultimodalCapability$inboundSchema,
  MultimodalCapability$outboundSchema,
} from "./multimodalcapability.js";
import {
  NodeNameFilter,
  NodeNameFilter$inboundSchema,
  NodeNameFilter$Outbound,
  NodeNameFilter$outboundSchema,
} from "./nodenamefilter.js";
import {
  NodeType,
  NodeType$inboundSchema,
  NodeType$outboundSchema,
} from "./nodetype.js";
import {
  NumericRollUpMethod,
  NumericRollUpMethod$inboundSchema,
  NumericRollUpMethod$outboundSchema,
} from "./numericrollupmethod.js";
import {
  OutputTypeEnum,
  OutputTypeEnum$inboundSchema,
  OutputTypeEnum$outboundSchema,
} from "./outputtypeenum.js";
import {
  PromptgalileoSchemasScorerNameScorerName,
  PromptgalileoSchemasScorerNameScorerName$inboundSchema,
  PromptgalileoSchemasScorerNameScorerName$outboundSchema,
} from "./promptgalileoschemasscorernamescorername.js";
import {
  RollUpStrategy,
  RollUpStrategy$inboundSchema,
  RollUpStrategy$outboundSchema,
} from "./rollupstrategy.js";

export type BaseScorerFilter =
  | MetadataFilter
  | ModalityFilter
  | NodeNameFilter
  | discriminatedUnionTypes.Unknown<"name">;

export type BaseScorerRollUpMethods =
  | Array<NumericRollUpMethod>
  | Array<CategoricalRollUpMethod>;

export type BaseScorerClassNameToVocabIx = { [k: string]: Array<number> } | {
  [k: string]: number;
};

export type BaseScorer = {
  scorerName?: string | undefined;
  name?: string | undefined;
  scores?: Array<any> | null | undefined;
  indices?: Array<number> | null | undefined;
  aggregates?: { [k: string]: any } | null | undefined;
  aggregateKeys?: Array<string> | null | undefined;
  extra?: { [k: string]: any } | null | undefined;
  subScorers?: Array<PromptgalileoSchemasScorerNameScorerName> | undefined;
  filters?:
    | Array<
      | MetadataFilter
      | ModalityFilter
      | NodeNameFilter
      | discriminatedUnionTypes.Unknown<"name">
    >
    | null
    | undefined;
  metricName?: string | null | undefined;
  description?: string | null | undefined;
  chainpollTemplate?: ChainPollTemplate | null | undefined;
  modelAlias?: string | null | undefined;
  numJudges?: number | null | undefined;
  defaultModelAlias?: string | null | undefined;
  groundTruth?: boolean | null | undefined;
  regexField?: string | undefined;
  registeredScorerId?: string | null | undefined;
  generatedScorerId?: string | null | undefined;
  scorerVersionId?: string | null | undefined;
  userCode?: string | null | undefined;
  canCopyToLlm?: boolean | null | undefined;
  scoreableNodeTypes?: Array<NodeType> | null | undefined;
  cotEnabled?: boolean | null | undefined;
  outputType?: OutputTypeEnum | null | undefined;
  inputType?: InputTypeEnum | null | undefined;
  multimodalCapabilities?: Array<MultimodalCapability> | null | undefined;
  requiredScorers?: Array<string> | null | undefined;
  requiredMetricIds?: Array<string> | null | undefined;
  rollUpStrategy?: RollUpStrategy | null | undefined;
  rollUpMethods?:
    | Array<NumericRollUpMethod>
    | Array<CategoricalRollUpMethod>
    | null
    | undefined;
  prompt?: string | null | undefined;
  loraTaskId?: number | null | undefined;
  loraWeightsPath?: string | null | undefined;
  lunaInputType?: LunaInputTypeEnum | null | undefined;
  lunaOutputType?: LunaOutputTypeEnum | null | undefined;
  classNameToVocabIx?:
    | { [k: string]: Array<number> }
    | { [k: string]: number }
    | null
    | undefined;
};

/** @internal */
export const BaseScorerFilter$inboundSchema: z.ZodMiniType<
  BaseScorerFilter,
  unknown
> = discriminatedUnion("name", {
  metadata: MetadataFilter$inboundSchema,
  modality: ModalityFilter$inboundSchema,
  node_name: NodeNameFilter$inboundSchema,
});
/** @internal */
export type BaseScorerFilter$Outbound =
  | MetadataFilter$Outbound
  | ModalityFilter$Outbound
  | NodeNameFilter$Outbound;

/** @internal */
export const BaseScorerFilter$outboundSchema: z.ZodMiniType<
  BaseScorerFilter$Outbound,
  BaseScorerFilter
> = z.union([
  MetadataFilter$outboundSchema,
  ModalityFilter$outboundSchema,
  NodeNameFilter$outboundSchema,
]);

export function baseScorerFilterToJSON(
  baseScorerFilter: BaseScorerFilter,
): string {
  return JSON.stringify(
    BaseScorerFilter$outboundSchema.parse(baseScorerFilter),
  );
}
export function baseScorerFilterFromJSON(
  jsonString: string,
): SafeParseResult<BaseScorerFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaseScorerFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaseScorerFilter' from JSON`,
  );
}

/** @internal */
export const BaseScorerRollUpMethods$inboundSchema: z.ZodMiniType<
  BaseScorerRollUpMethods,
  unknown
> = smartUnion([
  z.array(NumericRollUpMethod$inboundSchema),
  z.array(CategoricalRollUpMethod$inboundSchema),
]);
/** @internal */
export type BaseScorerRollUpMethods$Outbound = Array<string> | Array<string>;

/** @internal */
export const BaseScorerRollUpMethods$outboundSchema: z.ZodMiniType<
  BaseScorerRollUpMethods$Outbound,
  BaseScorerRollUpMethods
> = smartUnion([
  z.array(NumericRollUpMethod$outboundSchema),
  z.array(CategoricalRollUpMethod$outboundSchema),
]);

export function baseScorerRollUpMethodsToJSON(
  baseScorerRollUpMethods: BaseScorerRollUpMethods,
): string {
  return JSON.stringify(
    BaseScorerRollUpMethods$outboundSchema.parse(baseScorerRollUpMethods),
  );
}
export function baseScorerRollUpMethodsFromJSON(
  jsonString: string,
): SafeParseResult<BaseScorerRollUpMethods, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaseScorerRollUpMethods$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaseScorerRollUpMethods' from JSON`,
  );
}

/** @internal */
export const BaseScorerClassNameToVocabIx$inboundSchema: z.ZodMiniType<
  BaseScorerClassNameToVocabIx,
  unknown
> = smartUnion([
  z.record(z.string(), z.array(types.number())),
  z.record(z.string(), types.number()),
]);
/** @internal */
export type BaseScorerClassNameToVocabIx$Outbound = {
  [k: string]: Array<number>;
} | { [k: string]: number };

/** @internal */
export const BaseScorerClassNameToVocabIx$outboundSchema: z.ZodMiniType<
  BaseScorerClassNameToVocabIx$Outbound,
  BaseScorerClassNameToVocabIx
> = smartUnion([
  z.record(z.string(), z.array(z.int())),
  z.record(z.string(), z.int()),
]);

export function baseScorerClassNameToVocabIxToJSON(
  baseScorerClassNameToVocabIx: BaseScorerClassNameToVocabIx,
): string {
  return JSON.stringify(
    BaseScorerClassNameToVocabIx$outboundSchema.parse(
      baseScorerClassNameToVocabIx,
    ),
  );
}
export function baseScorerClassNameToVocabIxFromJSON(
  jsonString: string,
): SafeParseResult<BaseScorerClassNameToVocabIx, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaseScorerClassNameToVocabIx$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaseScorerClassNameToVocabIx' from JSON`,
  );
}

/** @internal */
export const BaseScorer$inboundSchema: z.ZodMiniType<BaseScorer, unknown> = z
  .pipe(
    z.object({
      scorer_name: z._default(types.string(), ""),
      name: z._default(types.string(), ""),
      scores: z.optional(z.nullable(z.array(z.any()))),
      indices: z.optional(z.nullable(z.array(types.number()))),
      aggregates: z.optional(z.nullable(z.record(z.string(), z.any()))),
      aggregate_keys: z.optional(z.nullable(z.array(types.string()))),
      extra: z.optional(z.nullable(z.record(z.string(), z.any()))),
      sub_scorers: types.optional(
        z.array(PromptgalileoSchemasScorerNameScorerName$inboundSchema),
      ),
      filters: z.optional(
        z.nullable(
          z.array(
            discriminatedUnion("name", {
              metadata: MetadataFilter$inboundSchema,
              modality: ModalityFilter$inboundSchema,
              node_name: NodeNameFilter$inboundSchema,
            }),
          ),
        ),
      ),
      metric_name: z.optional(z.nullable(types.string())),
      description: z.optional(z.nullable(types.string())),
      chainpoll_template: z.optional(
        z.nullable(ChainPollTemplate$inboundSchema),
      ),
      model_alias: z.optional(z.nullable(types.string())),
      num_judges: z.optional(z.nullable(types.number())),
      default_model_alias: z.optional(z.nullable(types.string())),
      ground_truth: z.optional(z.nullable(types.boolean())),
      regex_field: z._default(types.string(), ""),
      registered_scorer_id: z.optional(z.nullable(types.string())),
      generated_scorer_id: z.optional(z.nullable(types.string())),
      scorer_version_id: z.optional(z.nullable(types.string())),
      user_code: z.optional(z.nullable(types.string())),
      can_copy_to_llm: z.optional(z.nullable(types.boolean())),
      scoreable_node_types: z.optional(
        z.nullable(z.array(NodeType$inboundSchema)),
      ),
      cot_enabled: z.optional(z.nullable(types.boolean())),
      output_type: z.optional(z.nullable(OutputTypeEnum$inboundSchema)),
      input_type: z.optional(z.nullable(InputTypeEnum$inboundSchema)),
      multimodal_capabilities: z.optional(
        z.nullable(z.array(MultimodalCapability$inboundSchema)),
      ),
      required_scorers: z.optional(z.nullable(z.array(types.string()))),
      required_metric_ids: z.optional(z.nullable(z.array(types.string()))),
      roll_up_strategy: z.optional(z.nullable(RollUpStrategy$inboundSchema)),
      roll_up_methods: z.optional(
        z.nullable(
          smartUnion([
            z.array(NumericRollUpMethod$inboundSchema),
            z.array(CategoricalRollUpMethod$inboundSchema),
          ]),
        ),
      ),
      prompt: z.optional(z.nullable(types.string())),
      lora_task_id: z.optional(z.nullable(types.number())),
      lora_weights_path: z.optional(z.nullable(types.string())),
      luna_input_type: z.optional(z.nullable(LunaInputTypeEnum$inboundSchema)),
      luna_output_type: z.optional(
        z.nullable(LunaOutputTypeEnum$inboundSchema),
      ),
      class_name_to_vocab_ix: z.optional(
        z.nullable(
          smartUnion([
            z.record(z.string(), z.array(types.number())),
            z.record(z.string(), types.number()),
          ]),
        ),
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "scorer_name": "scorerName",
        "aggregate_keys": "aggregateKeys",
        "sub_scorers": "subScorers",
        "metric_name": "metricName",
        "chainpoll_template": "chainpollTemplate",
        "model_alias": "modelAlias",
        "num_judges": "numJudges",
        "default_model_alias": "defaultModelAlias",
        "ground_truth": "groundTruth",
        "regex_field": "regexField",
        "registered_scorer_id": "registeredScorerId",
        "generated_scorer_id": "generatedScorerId",
        "scorer_version_id": "scorerVersionId",
        "user_code": "userCode",
        "can_copy_to_llm": "canCopyToLlm",
        "scoreable_node_types": "scoreableNodeTypes",
        "cot_enabled": "cotEnabled",
        "output_type": "outputType",
        "input_type": "inputType",
        "multimodal_capabilities": "multimodalCapabilities",
        "required_scorers": "requiredScorers",
        "required_metric_ids": "requiredMetricIds",
        "roll_up_strategy": "rollUpStrategy",
        "roll_up_methods": "rollUpMethods",
        "lora_task_id": "loraTaskId",
        "lora_weights_path": "loraWeightsPath",
        "luna_input_type": "lunaInputType",
        "luna_output_type": "lunaOutputType",
        "class_name_to_vocab_ix": "classNameToVocabIx",
      });
    }),
  );
/** @internal */
export type BaseScorer$Outbound = {
  scorer_name: string;
  name: string;
  scores?: Array<any> | null | undefined;
  indices?: Array<number> | null | undefined;
  aggregates?: { [k: string]: any } | null | undefined;
  aggregate_keys?: Array<string> | null | undefined;
  extra?: { [k: string]: any } | null | undefined;
  sub_scorers?: Array<string> | undefined;
  filters?:
    | Array<
      | MetadataFilter$Outbound
      | ModalityFilter$Outbound
      | NodeNameFilter$Outbound
    >
    | null
    | undefined;
  metric_name?: string | null | undefined;
  description?: string | null | undefined;
  chainpoll_template?: ChainPollTemplate$Outbound | null | undefined;
  model_alias?: string | null | undefined;
  num_judges?: number | null | undefined;
  default_model_alias?: string | null | undefined;
  ground_truth?: boolean | null | undefined;
  regex_field: string;
  registered_scorer_id?: string | null | undefined;
  generated_scorer_id?: string | null | undefined;
  scorer_version_id?: string | null | undefined;
  user_code?: string | null | undefined;
  can_copy_to_llm?: boolean | null | undefined;
  scoreable_node_types?: Array<string> | null | undefined;
  cot_enabled?: boolean | null | undefined;
  output_type?: string | null | undefined;
  input_type?: string | null | undefined;
  multimodal_capabilities?: Array<string> | null | undefined;
  required_scorers?: Array<string> | null | undefined;
  required_metric_ids?: Array<string> | null | undefined;
  roll_up_strategy?: string | null | undefined;
  roll_up_methods?: Array<string> | Array<string> | null | undefined;
  prompt?: string | null | undefined;
  lora_task_id?: number | null | undefined;
  lora_weights_path?: string | null | undefined;
  luna_input_type?: string | null | undefined;
  luna_output_type?: string | null | undefined;
  class_name_to_vocab_ix?:
    | { [k: string]: Array<number> }
    | { [k: string]: number }
    | null
    | undefined;
};

/** @internal */
export const BaseScorer$outboundSchema: z.ZodMiniType<
  BaseScorer$Outbound,
  BaseScorer
> = z.pipe(
  z.object({
    scorerName: z._default(z.string(), ""),
    name: z._default(z.string(), ""),
    scores: z.optional(z.nullable(z.array(z.any()))),
    indices: z.optional(z.nullable(z.array(z.int()))),
    aggregates: z.optional(z.nullable(z.record(z.string(), z.any()))),
    aggregateKeys: z.optional(z.nullable(z.array(z.string()))),
    extra: z.optional(z.nullable(z.record(z.string(), z.any()))),
    subScorers: z.optional(
      z.array(PromptgalileoSchemasScorerNameScorerName$outboundSchema),
    ),
    filters: z.optional(
      z.nullable(
        z.array(
          z.union([
            MetadataFilter$outboundSchema,
            ModalityFilter$outboundSchema,
            NodeNameFilter$outboundSchema,
          ]),
        ),
      ),
    ),
    metricName: z.optional(z.nullable(z.string())),
    description: z.optional(z.nullable(z.string())),
    chainpollTemplate: z.optional(z.nullable(ChainPollTemplate$outboundSchema)),
    modelAlias: z.optional(z.nullable(z.string())),
    numJudges: z.optional(z.nullable(z.int())),
    defaultModelAlias: z.optional(z.nullable(z.string())),
    groundTruth: z.optional(z.nullable(z.boolean())),
    regexField: z._default(z.string(), ""),
    registeredScorerId: z.optional(z.nullable(z.string())),
    generatedScorerId: z.optional(z.nullable(z.string())),
    scorerVersionId: z.optional(z.nullable(z.string())),
    userCode: z.optional(z.nullable(z.string())),
    canCopyToLlm: z.optional(z.nullable(z.boolean())),
    scoreableNodeTypes: z.optional(
      z.nullable(z.array(NodeType$outboundSchema)),
    ),
    cotEnabled: z.optional(z.nullable(z.boolean())),
    outputType: z.optional(z.nullable(OutputTypeEnum$outboundSchema)),
    inputType: z.optional(z.nullable(InputTypeEnum$outboundSchema)),
    multimodalCapabilities: z.optional(
      z.nullable(z.array(MultimodalCapability$outboundSchema)),
    ),
    requiredScorers: z.optional(z.nullable(z.array(z.string()))),
    requiredMetricIds: z.optional(z.nullable(z.array(z.string()))),
    rollUpStrategy: z.optional(z.nullable(RollUpStrategy$outboundSchema)),
    rollUpMethods: z.optional(
      z.nullable(
        smartUnion([
          z.array(NumericRollUpMethod$outboundSchema),
          z.array(CategoricalRollUpMethod$outboundSchema),
        ]),
      ),
    ),
    prompt: z.optional(z.nullable(z.string())),
    loraTaskId: z.optional(z.nullable(z.int())),
    loraWeightsPath: z.optional(z.nullable(z.string())),
    lunaInputType: z.optional(z.nullable(LunaInputTypeEnum$outboundSchema)),
    lunaOutputType: z.optional(z.nullable(LunaOutputTypeEnum$outboundSchema)),
    classNameToVocabIx: z.optional(
      z.nullable(
        smartUnion([
          z.record(z.string(), z.array(z.int())),
          z.record(z.string(), z.int()),
        ]),
      ),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      scorerName: "scorer_name",
      aggregateKeys: "aggregate_keys",
      subScorers: "sub_scorers",
      metricName: "metric_name",
      chainpollTemplate: "chainpoll_template",
      modelAlias: "model_alias",
      numJudges: "num_judges",
      defaultModelAlias: "default_model_alias",
      groundTruth: "ground_truth",
      regexField: "regex_field",
      registeredScorerId: "registered_scorer_id",
      generatedScorerId: "generated_scorer_id",
      scorerVersionId: "scorer_version_id",
      userCode: "user_code",
      canCopyToLlm: "can_copy_to_llm",
      scoreableNodeTypes: "scoreable_node_types",
      cotEnabled: "cot_enabled",
      outputType: "output_type",
      inputType: "input_type",
      multimodalCapabilities: "multimodal_capabilities",
      requiredScorers: "required_scorers",
      requiredMetricIds: "required_metric_ids",
      rollUpStrategy: "roll_up_strategy",
      rollUpMethods: "roll_up_methods",
      loraTaskId: "lora_task_id",
      loraWeightsPath: "lora_weights_path",
      lunaInputType: "luna_input_type",
      lunaOutputType: "luna_output_type",
      classNameToVocabIx: "class_name_to_vocab_ix",
    });
  }),
);

export function baseScorerToJSON(baseScorer: BaseScorer): string {
  return JSON.stringify(BaseScorer$outboundSchema.parse(baseScorer));
}
export function baseScorerFromJSON(
  jsonString: string,
): SafeParseResult<BaseScorer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaseScorer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaseScorer' from JSON`,
  );
}
