/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 40d329a7d9fb
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { MetricColor, MetricColor$inboundSchema } from "./metriccolor.js";

/**
 * A color constraint for boolean metric values.
 *
 * @remarks
 *
 * Assigns a color when a boolean score equals the given value.
 *
 * Only the 'eq' operator is supported.
 *
 * Example:
 *     {"color": "green", "operator": "eq", "value": true}
 *     {"color": "red", "operator": "eq", "value": false}
 */
export type BooleanColorConstraint = {
  /**
   * Allowed colors for metric threshold visualization in the UI.
   */
  color: MetricColor;
  operator: "eq";
  value: boolean;
};

/** @internal */
export const BooleanColorConstraint$inboundSchema: z.ZodMiniType<
  BooleanColorConstraint,
  unknown
> = z.object({
  color: MetricColor$inboundSchema,
  operator: types.literal("eq"),
  value: types.boolean(),
});

export function booleanColorConstraintFromJSON(
  jsonString: string,
): SafeParseResult<BooleanColorConstraint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BooleanColorConstraint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BooleanColorConstraint' from JSON`,
  );
}
