/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ChainAggregationStrategy = {
  Sum: "sum",
  Average: "average",
  First: "first",
  Last: "last",
} as const;
export type ChainAggregationStrategy = OpenEnum<
  typeof ChainAggregationStrategy
>;

/** @internal */
export const ChainAggregationStrategy$inboundSchema: z.ZodMiniType<
  ChainAggregationStrategy,
  unknown
> = openEnums.inboundSchema(ChainAggregationStrategy);
