/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1f364ea1d64c
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ChoiceAggregate = {
  feedbackType: "choice";
  counts: { [k: string]: number };
  unratedCount: number;
};

/** @internal */
export const ChoiceAggregate$inboundSchema: z.ZodMiniType<
  ChoiceAggregate,
  unknown
> = z.pipe(
  z.object({
    feedback_type: types.literal("choice"),
    counts: z.record(z.string(), types.number()),
    unrated_count: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "feedback_type": "feedbackType",
      "unrated_count": "unratedCount",
    });
  }),
);

export function choiceAggregateFromJSON(
  jsonString: string,
): SafeParseResult<ChoiceAggregate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChoiceAggregate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChoiceAggregate' from JSON`,
  );
}
