/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ColumnMappingConfig = {
  columns: Array<string>;
  flatten?: boolean | undefined;
};

/** @internal */
export type ColumnMappingConfig$Outbound = {
  columns: Array<string>;
  flatten: boolean;
};

/** @internal */
export const ColumnMappingConfig$outboundSchema: z.ZodMiniType<
  ColumnMappingConfig$Outbound,
  ColumnMappingConfig
> = z.object({
  columns: z.array(z.string()),
  flatten: z._default(z.boolean(), false),
});

export function columnMappingConfigToJSON(
  columnMappingConfig: ColumnMappingConfig,
): string {
  return JSON.stringify(
    ColumnMappingConfig$outboundSchema.parse(columnMappingConfig),
  );
}
