/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ColumnCategory = {
  Standard: "standard",
  Metric: "metric",
  UserMetadata: "user_metadata",
  MetricStatus: "metric_status",
  DatasetMetadata: "dataset_metadata",
  Dataset: "dataset",
  Feedback: "feedback",
  Tags: "tags",
} as const;
export type ColumnCategory = OpenEnum<typeof ColumnCategory>;

/** @internal */
export const ColumnCategory$inboundSchema: z.ZodMiniType<
  ColumnCategory,
  unknown
> = openEnums.inboundSchema(ColumnCategory);
