/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b087bbe3724c
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  OutputTypeEnum,
  OutputTypeEnum$outboundSchema,
} from "./outputtypeenum.js";
import { StepType, StepType$outboundSchema } from "./steptype.js";

export type ComputeHealthScoreRequest = {
  scorerId: string;
  /**
   * Enumeration of output types.
   */
  outputType: OutputTypeEnum;
  /**
   * The scorer's scoreable_node_types. Determines which record type carries the score.
   */
  scoreableNodeTypes?: Array<StepType> | undefined;
  /**
   * Client-side pending MGT edits: {row_id: value}. Overrides committed dataset values.
   */
  mgtOverlay?: { [k: string]: string | null } | undefined;
};

/** @internal */
export type ComputeHealthScoreRequest$Outbound = {
  scorer_id: string;
  output_type: string;
  scoreable_node_types?: Array<string> | undefined;
  mgt_overlay?: { [k: string]: string | null } | undefined;
};

/** @internal */
export const ComputeHealthScoreRequest$outboundSchema: z.ZodMiniType<
  ComputeHealthScoreRequest$Outbound,
  ComputeHealthScoreRequest
> = z.pipe(
  z.object({
    scorerId: z.string(),
    outputType: OutputTypeEnum$outboundSchema,
    scoreableNodeTypes: z.optional(z.array(StepType$outboundSchema)),
    mgtOverlay: z.optional(z.record(z.string(), z.nullable(z.string()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      scorerId: "scorer_id",
      outputType: "output_type",
      scoreableNodeTypes: "scoreable_node_types",
      mgtOverlay: "mgt_overlay",
    });
  }),
);

export function computeHealthScoreRequestToJSON(
  computeHealthScoreRequest: ComputeHealthScoreRequest,
): string {
  return JSON.stringify(
    ComputeHealthScoreRequest$outboundSchema.parse(computeHealthScoreRequest),
  );
}
