/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 364a5a354d3c
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const ControlCheckStage = {
  Pre: "pre",
  Post: "post",
} as const;
export type ControlCheckStage = ClosedEnum<typeof ControlCheckStage>;

/** @internal */
export const ControlCheckStage$outboundSchema: z.ZodMiniEnum<
  typeof ControlCheckStage
> = z.enum(ControlCheckStage);
