/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4d394f5622ba
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  AnnotationTemplateCreate,
  AnnotationTemplateCreate$Outbound,
  AnnotationTemplateCreate$outboundSchema,
} from "./annotationtemplatecreate.js";

/**
 * Request to create templates in an annotation queue.
 *
 * @remarks
 *
 * Supports two scenarios:
 * 1. Create a single template (template field)
 * 2. Copy all templates from a source queue (copy_from_queue_id field)
 */
export type CreateQueueTemplateRequest = {
  /**
   * Template to create. Required if copy_from_queue_id is not provided.
   */
  template?: AnnotationTemplateCreate | null | undefined;
  /**
   * Source queue ID to copy all templates from. Required if template is not provided.
   */
  copyFromQueueId?: string | null | undefined;
};

/** @internal */
export type CreateQueueTemplateRequest$Outbound = {
  template?: AnnotationTemplateCreate$Outbound | null | undefined;
  copy_from_queue_id?: string | null | undefined;
};

/** @internal */
export const CreateQueueTemplateRequest$outboundSchema: z.ZodMiniType<
  CreateQueueTemplateRequest$Outbound,
  CreateQueueTemplateRequest
> = z.pipe(
  z.object({
    template: z.optional(z.nullable(AnnotationTemplateCreate$outboundSchema)),
    copyFromQueueId: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      copyFromQueueId: "copy_from_queue_id",
    });
  }),
);

export function createQueueTemplateRequestToJSON(
  createQueueTemplateRequest: CreateQueueTemplateRequest,
): string {
  return JSON.stringify(
    CreateQueueTemplateRequest$outboundSchema.parse(createQueueTemplateRequest),
  );
}
