/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b9f85ff2da7d
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  CustomAuthenticationType,
  CustomAuthenticationType$outboundSchema,
} from "./customauthenticationtype.js";

export type CustomIntegrationCreate = {
  authenticationType?: CustomAuthenticationType | undefined;
  /**
   * List of model names for the custom integration
   */
  models: Array<string>;
  /**
   * Default model to use. If not provided, defaults to the first model in the models list.
   */
  defaultModel?: string | null | undefined;
  /**
   * Endpoint URL for the custom integration.
   */
  endpoint: string;
  /**
   * Optional scope for OAuth2 authentication.
   */
  authenticationScope?: string | null | undefined;
  /**
   * OAuth2 token URL for custom OAuth2 authentication. If not provided, defaults to the endpoint.
   */
  oauth2TokenUrl?: string | null | undefined;
  token?: string | null | undefined;
};

/** @internal */
export type CustomIntegrationCreate$Outbound = {
  authentication_type?: string | undefined;
  models: Array<string>;
  default_model?: string | null | undefined;
  endpoint: string;
  authentication_scope?: string | null | undefined;
  oauth2_token_url?: string | null | undefined;
  token?: string | null | undefined;
};

/** @internal */
export const CustomIntegrationCreate$outboundSchema: z.ZodMiniType<
  CustomIntegrationCreate$Outbound,
  CustomIntegrationCreate
> = z.pipe(
  z.object({
    authenticationType: z.optional(CustomAuthenticationType$outboundSchema),
    models: z.array(z.string()),
    defaultModel: z.optional(z.nullable(z.string())),
    endpoint: z.string(),
    authenticationScope: z.optional(z.nullable(z.string())),
    oauth2TokenUrl: z.optional(z.nullable(z.string())),
    token: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      authenticationType: "authentication_type",
      defaultModel: "default_model",
      authenticationScope: "authentication_scope",
      oauth2TokenUrl: "oauth2_token_url",
    });
  }),
);

export function customIntegrationCreateToJSON(
  customIntegrationCreate: CustomIntegrationCreate,
): string {
  return JSON.stringify(
    CustomIntegrationCreate$outboundSchema.parse(customIntegrationCreate),
  );
}
