/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const DataUnit = {
  Percentage: "percentage",
  NanoSeconds: "nano_seconds",
  MilliSeconds: "milli_seconds",
  Dollars: "dollars",
  CountAndTotal: "count_and_total",
} as const;
export type DataUnit = OpenEnum<typeof DataUnit>;

/** @internal */
export const DataUnit$inboundSchema: z.ZodMiniType<DataUnit, unknown> =
  openEnums.inboundSchema(DataUnit);
