/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c79fbcc06e3e
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const DatasetContentFilterOperator = {
  Eq: "eq",
  Ne: "ne",
  Contains: "contains",
} as const;
export type DatasetContentFilterOperator = ClosedEnum<
  typeof DatasetContentFilterOperator
>;

/** @internal */
export const DatasetContentFilterOperator$outboundSchema: z.ZodMiniEnum<
  typeof DatasetContentFilterOperator
> = z.enum(DatasetContentFilterOperator);
