/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 80fea099b794
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  EditOverride,
  EditOverride$Outbound,
  EditOverride$outboundSchema,
} from "./editoverride.js";
import { FileType, FileType$outboundSchema } from "./filetype.js";
import {
  FilterParams,
  FilterParams$Outbound,
  FilterParams$outboundSchema,
} from "./filterparams.js";
import { Split, Split$outboundSchema } from "./split.js";
import {
  TaggingSchema,
  TaggingSchema$outboundSchema,
} from "./taggingschema.js";

export type DatabricksUnityCatalogEditExportRequest = {
  task?: string | null | undefined;
  filterParams?: FilterParams | undefined;
  compareTo?: Split | null | undefined;
  mapThreshold?: number | undefined;
  allBut?: boolean | undefined;
  fileType?: FileType | undefined;
  includeCols?: Array<string> | null | undefined;
  colMapping?: { [k: string]: string } | null | undefined;
  hfFormat?: boolean | undefined;
  taggingSchema?: TaggingSchema | null | undefined;
  editIds: Array<string>;
  editOverrides?: Array<EditOverride> | null | undefined;
  onlyExportEdited?: boolean | null | undefined;
  minReviews?: number | null | undefined;
  catalogName: string;
  schemaName: string;
  pslContentFileName: string;
  tableName: string;
};

/** @internal */
export type DatabricksUnityCatalogEditExportRequest$Outbound = {
  task?: string | null | undefined;
  filter_params?: FilterParams$Outbound | undefined;
  compare_to?: string | null | undefined;
  map_threshold: number;
  all_but: boolean;
  file_type?: string | undefined;
  include_cols?: Array<string> | null | undefined;
  col_mapping?: { [k: string]: string } | null | undefined;
  hf_format: boolean;
  tagging_schema?: string | null | undefined;
  edit_ids: Array<string>;
  edit_overrides?: Array<EditOverride$Outbound> | null | undefined;
  only_export_edited?: boolean | null | undefined;
  min_reviews?: number | null | undefined;
  catalog_name: string;
  schema_name: string;
  psl_content_file_name: string;
  table_name: string;
};

/** @internal */
export const DatabricksUnityCatalogEditExportRequest$outboundSchema:
  z.ZodMiniType<
    DatabricksUnityCatalogEditExportRequest$Outbound,
    DatabricksUnityCatalogEditExportRequest
  > = z.pipe(
    z.object({
      task: z.optional(z.nullable(z.string())),
      filterParams: z.optional(FilterParams$outboundSchema),
      compareTo: z.optional(z.nullable(Split$outboundSchema)),
      mapThreshold: z._default(z.number(), 0.5),
      allBut: z._default(z.boolean(), false),
      fileType: z.optional(FileType$outboundSchema),
      includeCols: z.optional(z.nullable(z.array(z.string()))),
      colMapping: z.optional(z.nullable(z.record(z.string(), z.string()))),
      hfFormat: z._default(z.boolean(), false),
      taggingSchema: z.optional(z.nullable(TaggingSchema$outboundSchema)),
      editIds: z.array(z.string()),
      editOverrides: z.optional(
        z.nullable(z.array(EditOverride$outboundSchema)),
      ),
      onlyExportEdited: z.optional(z.nullable(z.boolean())),
      minReviews: z.optional(z.nullable(z.int())),
      catalogName: z.string(),
      schemaName: z.string(),
      pslContentFileName: z.string(),
      tableName: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        filterParams: "filter_params",
        compareTo: "compare_to",
        mapThreshold: "map_threshold",
        allBut: "all_but",
        fileType: "file_type",
        includeCols: "include_cols",
        colMapping: "col_mapping",
        hfFormat: "hf_format",
        taggingSchema: "tagging_schema",
        editIds: "edit_ids",
        editOverrides: "edit_overrides",
        onlyExportEdited: "only_export_edited",
        minReviews: "min_reviews",
        catalogName: "catalog_name",
        schemaName: "schema_name",
        pslContentFileName: "psl_content_file_name",
        tableName: "table_name",
      });
    }),
  );

export function databricksUnityCatalogEditExportRequestToJSON(
  databricksUnityCatalogEditExportRequest:
    DatabricksUnityCatalogEditExportRequest,
): string {
  return JSON.stringify(
    DatabricksUnityCatalogEditExportRequest$outboundSchema.parse(
      databricksUnityCatalogEditExportRequest,
    ),
  );
}
