/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 36b4546a69a7
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { UserInfo, UserInfo$inboundSchema } from "./userinfo.js";

export type DatasetProject = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  name: string;
  createdByUser: UserInfo | null;
};

/** @internal */
export const DatasetProject$inboundSchema: z.ZodMiniType<
  DatasetProject,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    created_at: types.date(),
    updated_at: types.date(),
    name: types.string(),
    created_by_user: types.nullable(UserInfo$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "created_by_user": "createdByUser",
    });
  }),
);

export function datasetProjectFromJSON(
  jsonString: string,
): SafeParseResult<DatasetProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatasetProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatasetProject' from JSON`,
  );
}
