/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3d4193c04328
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ExperimentDatasetRequest = {
  datasetId: string;
  versionIndex: number;
};

/** @internal */
export type ExperimentDatasetRequest$Outbound = {
  dataset_id: string;
  version_index: number;
};

/** @internal */
export const ExperimentDatasetRequest$outboundSchema: z.ZodMiniType<
  ExperimentDatasetRequest$Outbound,
  ExperimentDatasetRequest
> = z.pipe(
  z.object({
    datasetId: z.string(),
    versionIndex: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      datasetId: "dataset_id",
      versionIndex: "version_index",
    });
  }),
);

export function experimentDatasetRequestToJSON(
  experimentDatasetRequest: ExperimentDatasetRequest,
): string {
  return JSON.stringify(
    ExperimentDatasetRequest$outboundSchema.parse(experimentDatasetRequest),
  );
}
