/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d3ebf9621153
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ColumnInfo, ColumnInfo$inboundSchema } from "./columninfo.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ExperimentsAvailableColumnsResponse = {
  columns?: Array<ColumnInfo> | undefined;
};

/** @internal */
export const ExperimentsAvailableColumnsResponse$inboundSchema: z.ZodMiniType<
  ExperimentsAvailableColumnsResponse,
  unknown
> = z.object({
  columns: types.optional(z.array(ColumnInfo$inboundSchema)),
});

export function experimentsAvailableColumnsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExperimentsAvailableColumnsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExperimentsAvailableColumnsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExperimentsAvailableColumnsResponse' from JSON`,
  );
}
