/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0f7fac605508
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smartUnion.js";

export const ExperimentGroupNameFilterOperator = {
  Eq: "eq",
  Ne: "ne",
  Contains: "contains",
  OneOf: "one_of",
  NotIn: "not_in",
} as const;
export type ExperimentGroupNameFilterOperator = ClosedEnum<
  typeof ExperimentGroupNameFilterOperator
>;

export type ExperimentGroupNameFilterValue = string | Array<string>;

export type ExperimentGroupNameFilter = {
  name: "experiment_group_name";
  operator: ExperimentGroupNameFilterOperator;
  value: string | Array<string>;
  caseSensitive?: boolean | undefined;
};

/** @internal */
export const ExperimentGroupNameFilterOperator$outboundSchema: z.ZodMiniEnum<
  typeof ExperimentGroupNameFilterOperator
> = z.enum(ExperimentGroupNameFilterOperator);

/** @internal */
export type ExperimentGroupNameFilterValue$Outbound = string | Array<string>;

/** @internal */
export const ExperimentGroupNameFilterValue$outboundSchema: z.ZodMiniType<
  ExperimentGroupNameFilterValue$Outbound,
  ExperimentGroupNameFilterValue
> = smartUnion([z.string(), z.array(z.string())]);

export function experimentGroupNameFilterValueToJSON(
  experimentGroupNameFilterValue: ExperimentGroupNameFilterValue,
): string {
  return JSON.stringify(
    ExperimentGroupNameFilterValue$outboundSchema.parse(
      experimentGroupNameFilterValue,
    ),
  );
}

/** @internal */
export type ExperimentGroupNameFilter$Outbound = {
  name: "experiment_group_name";
  operator: string;
  value: string | Array<string>;
  case_sensitive: boolean;
};

/** @internal */
export const ExperimentGroupNameFilter$outboundSchema: z.ZodMiniType<
  ExperimentGroupNameFilter$Outbound,
  ExperimentGroupNameFilter
> = z.pipe(
  z.object({
    name: z.literal("experiment_group_name"),
    operator: ExperimentGroupNameFilterOperator$outboundSchema,
    value: smartUnion([z.string(), z.array(z.string())]),
    caseSensitive: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      caseSensitive: "case_sensitive",
    });
  }),
);

export function experimentGroupNameFilterToJSON(
  experimentGroupNameFilter: ExperimentGroupNameFilter,
): string {
  return JSON.stringify(
    ExperimentGroupNameFilter$outboundSchema.parse(experimentGroupNameFilter),
  );
}
