/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { Document, Document$inboundSchema } from "./document.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ExtendedAgentSpanRecordWithChildren,
  ExtendedAgentSpanRecordWithChildren$inboundSchema,
} from "./extendedagentspanrecordwithchildren.js";
import {
  ExtendedLlmSpanRecord,
  ExtendedLlmSpanRecord$inboundSchema,
} from "./extendedllmspanrecord.js";
import {
  ExtendedToolSpanRecordWithChildren,
  ExtendedToolSpanRecordWithChildren$inboundSchema,
} from "./extendedtoolspanrecordwithchildren.js";
import {
  ExtendedWorkflowSpanRecordWithChildren,
  ExtendedWorkflowSpanRecordWithChildren$inboundSchema,
} from "./extendedworkflowspanrecordwithchildren.js";
import {
  FeedbackRatingInfo,
  FeedbackRatingInfo$inboundSchema,
} from "./feedbackratinginfo.js";
import {
  MetricComputing,
  MetricComputing$inboundSchema,
} from "./metriccomputing.js";
import { MetricError, MetricError$inboundSchema } from "./metricerror.js";
import { MetricFailed, MetricFailed$inboundSchema } from "./metricfailed.js";
import {
  MetricNotApplicable,
  MetricNotApplicable$inboundSchema,
} from "./metricnotapplicable.js";
import {
  MetricNotComputed,
  MetricNotComputed$inboundSchema,
} from "./metricnotcomputed.js";
import { MetricPending, MetricPending$inboundSchema } from "./metricpending.js";
import { MetricRollUp, MetricRollUp$inboundSchema } from "./metricrollup.js";
import { Metrics, Metrics$inboundSchema } from "./metrics.js";
import { MetricSuccess, MetricSuccess$inboundSchema } from "./metricsuccess.js";

export type ExtendedRetrieverSpanRecordWithChildrenMetricInfo =
  | MetricComputing
  | MetricError
  | MetricFailed
  | MetricNotApplicable
  | MetricNotComputed
  | MetricPending
  | MetricRollUp
  | MetricSuccess
  | discriminatedUnionTypes.Unknown<"statusType">;

export type ExtendedRetrieverSpanRecordWithChildren = {
  spans?:
    | Array<
      | ExtendedAgentSpanRecordWithChildren
      | ExtendedLlmSpanRecord
      | ExtendedRetrieverSpanRecordWithChildren
      | ExtendedToolSpanRecordWithChildren
      | ExtendedWorkflowSpanRecordWithChildren
      | discriminatedUnionTypes.Unknown<"type">
    >
    | undefined;
  /**
   * Type of the trace, span or session.
   */
  type: "retriever";
  /**
   * Input to the trace or span.
   */
  input: string;
  /**
   * Redacted input of the trace or span.
   */
  redactedInput?: string | null | undefined;
  /**
   * Output of the trace or span.
   */
  output?: Array<Document> | undefined;
  /**
   * Redacted output of the trace or span.
   */
  redactedOutput?: Array<Document> | null | undefined;
  /**
   * Name of the trace, span or session.
   */
  name: string;
  /**
   * Timestamp of the trace or span's creation.
   */
  createdAt?: Date | undefined;
  /**
   * Metadata associated with this trace or span.
   */
  userMetadata?: { [k: string]: string } | undefined;
  /**
   * Tags associated with this trace or span.
   */
  tags?: Array<string> | undefined;
  /**
   * Status code of the trace or span. Used for logging failure or error states.
   */
  statusCode?: number | null | undefined;
  metrics?: Metrics | undefined;
  /**
   * A user-provided session, trace or span ID.
   */
  externalId?: string | null | undefined;
  /**
   * Input to the dataset associated with this trace
   */
  datasetInput?: string | null | undefined;
  /**
   * Output from the dataset associated with this trace
   */
  datasetOutput?: string | null | undefined;
  /**
   * Metadata from the dataset associated with this trace
   */
  datasetMetadata?: { [k: string]: string } | undefined;
  /**
   * Galileo ID of the session, trace or span
   */
  id: string;
  /**
   * Galileo ID of the session containing the trace (or the same value as id for a trace)
   */
  sessionId: string;
  /**
   * Galileo ID of the trace containing the span (or the same value as id for a trace)
   */
  traceId?: string | null | undefined;
  /**
   * Galileo ID of the project associated with this trace or span
   */
  projectId: string;
  /**
   * Galileo ID of the run (log stream or experiment) associated with this trace or span
   */
  runId: string;
  /**
   * Timestamp of the session or trace or span's last update
   */
  updatedAt?: Date | null | undefined;
  /**
   * Whether or not this trace or span has child spans
   */
  hasChildren?: boolean | null | undefined;
  /**
   * Galileo ID of the metrics batch associated with this trace or span
   */
  metricsBatchId?: string | null | undefined;
  /**
   * Galileo ID of the metrics batch associated with this trace or span
   */
  sessionBatchId?: string | null | undefined;
  /**
   * Feedback information related to the record
   */
  feedbackRatingInfo?: { [k: string]: FeedbackRatingInfo } | undefined;
  /**
   * Detailed information about the metrics associated with this trace or span
   */
  metricInfo?:
    | {
      [k: string]:
        | MetricComputing
        | MetricError
        | MetricFailed
        | MetricNotApplicable
        | MetricNotComputed
        | MetricPending
        | MetricRollUp
        | MetricSuccess
        | discriminatedUnionTypes.Unknown<"statusType">;
    }
    | null
    | undefined;
  /**
   * Galileo ID of the parent of this span
   */
  parentId: string;
  /**
   * Whether the parent trace is complete or not
   */
  isComplete: boolean;
  /**
   * Topological step number of the span.
   */
  stepNumber?: number | null | undefined;
};

export type ExtendedRetrieverSpanRecordWithChildrenSpan =
  | ExtendedAgentSpanRecordWithChildren
  | ExtendedLlmSpanRecord
  | ExtendedRetrieverSpanRecordWithChildren
  | ExtendedToolSpanRecordWithChildren
  | ExtendedWorkflowSpanRecordWithChildren
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const ExtendedRetrieverSpanRecordWithChildrenMetricInfo$inboundSchema:
  z.ZodMiniType<ExtendedRetrieverSpanRecordWithChildrenMetricInfo, unknown> =
    discriminatedUnion("status_type", {
      computing: MetricComputing$inboundSchema,
      error: MetricError$inboundSchema,
      failed: MetricFailed$inboundSchema,
      not_applicable: MetricNotApplicable$inboundSchema,
      not_computed: MetricNotComputed$inboundSchema,
      pending: MetricPending$inboundSchema,
      roll_up: MetricRollUp$inboundSchema,
      success: MetricSuccess$inboundSchema,
    }, { outputPropertyName: "statusType" });

export function extendedRetrieverSpanRecordWithChildrenMetricInfoFromJSON(
  jsonString: string,
): SafeParseResult<
  ExtendedRetrieverSpanRecordWithChildrenMetricInfo,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ExtendedRetrieverSpanRecordWithChildrenMetricInfo$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ExtendedRetrieverSpanRecordWithChildrenMetricInfo' from JSON`,
  );
}

/** @internal */
export const ExtendedRetrieverSpanRecordWithChildren$inboundSchema:
  z.ZodMiniType<ExtendedRetrieverSpanRecordWithChildren, unknown> = z.pipe(
    z.object({
      spans: types.optional(z.array(discriminatedUnion("type", {
        agent: z.lazy(() => ExtendedAgentSpanRecordWithChildren$inboundSchema),
        llm: ExtendedLlmSpanRecord$inboundSchema,
        retriever: z.lazy(() =>
          ExtendedRetrieverSpanRecordWithChildren$inboundSchema
        ),
        tool: z.lazy(() => ExtendedToolSpanRecordWithChildren$inboundSchema),
        workflow: z.lazy(() =>
          ExtendedWorkflowSpanRecordWithChildren$inboundSchema
        ),
      }))),
      type: types.literal("retriever"),
      input: z._default(types.string(), ""),
      redacted_input: z.optional(z.nullable(types.string())),
      output: types.optional(z.array(Document$inboundSchema)),
      redacted_output: z.optional(z.nullable(z.array(Document$inboundSchema))),
      name: z._default(types.string(), ""),
      created_at: types.optional(types.date()),
      user_metadata: types.optional(z.record(z.string(), types.string())),
      tags: types.optional(z.array(types.string())),
      status_code: z.optional(z.nullable(types.number())),
      metrics: types.optional(Metrics$inboundSchema),
      external_id: z.optional(z.nullable(types.string())),
      dataset_input: z.optional(z.nullable(types.string())),
      dataset_output: z.optional(z.nullable(types.string())),
      dataset_metadata: types.optional(z.record(z.string(), types.string())),
      id: types.string(),
      session_id: types.string(),
      trace_id: z.optional(z.nullable(types.string())),
      project_id: types.string(),
      run_id: types.string(),
      updated_at: z.optional(z.nullable(types.date())),
      has_children: z.optional(z.nullable(types.boolean())),
      metrics_batch_id: z.optional(z.nullable(types.string())),
      session_batch_id: z.optional(z.nullable(types.string())),
      feedback_rating_info: types.optional(
        z.record(z.string(), FeedbackRatingInfo$inboundSchema),
      ),
      metric_info: z.optional(
        z.nullable(z.record(
          z.string(),
          discriminatedUnion("status_type", {
            computing: MetricComputing$inboundSchema,
            error: MetricError$inboundSchema,
            failed: MetricFailed$inboundSchema,
            not_applicable: MetricNotApplicable$inboundSchema,
            not_computed: MetricNotComputed$inboundSchema,
            pending: MetricPending$inboundSchema,
            roll_up: MetricRollUp$inboundSchema,
            success: MetricSuccess$inboundSchema,
          }, { outputPropertyName: "statusType" }),
        )),
      ),
      parent_id: types.string(),
      is_complete: z._default(types.boolean(), true),
      step_number: z.optional(z.nullable(types.number())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "redacted_input": "redactedInput",
        "redacted_output": "redactedOutput",
        "created_at": "createdAt",
        "user_metadata": "userMetadata",
        "status_code": "statusCode",
        "external_id": "externalId",
        "dataset_input": "datasetInput",
        "dataset_output": "datasetOutput",
        "dataset_metadata": "datasetMetadata",
        "session_id": "sessionId",
        "trace_id": "traceId",
        "project_id": "projectId",
        "run_id": "runId",
        "updated_at": "updatedAt",
        "has_children": "hasChildren",
        "metrics_batch_id": "metricsBatchId",
        "session_batch_id": "sessionBatchId",
        "feedback_rating_info": "feedbackRatingInfo",
        "metric_info": "metricInfo",
        "parent_id": "parentId",
        "is_complete": "isComplete",
        "step_number": "stepNumber",
      });
    }),
  );

export function extendedRetrieverSpanRecordWithChildrenFromJSON(
  jsonString: string,
): SafeParseResult<
  ExtendedRetrieverSpanRecordWithChildren,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ExtendedRetrieverSpanRecordWithChildren$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ExtendedRetrieverSpanRecordWithChildren' from JSON`,
  );
}

/** @internal */
export const ExtendedRetrieverSpanRecordWithChildrenSpan$inboundSchema:
  z.ZodMiniType<ExtendedRetrieverSpanRecordWithChildrenSpan, unknown> =
    discriminatedUnion("type", {
      agent: z.lazy(() => ExtendedAgentSpanRecordWithChildren$inboundSchema),
      llm: ExtendedLlmSpanRecord$inboundSchema,
      retriever: z.lazy(() =>
        ExtendedRetrieverSpanRecordWithChildren$inboundSchema
      ),
      tool: z.lazy(() => ExtendedToolSpanRecordWithChildren$inboundSchema),
      workflow: z.lazy(() =>
        ExtendedWorkflowSpanRecordWithChildren$inboundSchema
      ),
    });

export function extendedRetrieverSpanRecordWithChildrenSpanFromJSON(
  jsonString: string,
): SafeParseResult<
  ExtendedRetrieverSpanRecordWithChildrenSpan,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ExtendedRetrieverSpanRecordWithChildrenSpan$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ExtendedRetrieverSpanRecordWithChildrenSpan' from JSON`,
  );
}
