/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ba08b05df535
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  AnnotationAggregate,
  AnnotationAggregate$inboundSchema,
} from "./annotationaggregate.js";
import {
  AnnotationRatingInfo,
  AnnotationRatingInfo$inboundSchema,
} from "./annotationratinginfo.js";
import {
  ContentModality,
  ContentModality$inboundSchema,
} from "./contentmodality.js";
import { ControlResult, ControlResult$inboundSchema } from "./controlresult.js";
import { Document, Document$inboundSchema } from "./document.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  FeedbackRatingInfo,
  FeedbackRatingInfo$inboundSchema,
} from "./feedbackratinginfo.js";
import {
  FileContentPart,
  FileContentPart$inboundSchema,
} from "./filecontentpart.js";
import { FileMetadata, FileMetadata$inboundSchema } from "./filemetadata.js";
import {
  GalileoCoreSchemasLoggingLlmMessage,
  GalileoCoreSchemasLoggingLlmMessage$inboundSchema,
} from "./galileocoreschemasloggingllmmessage.js";
import {
  MetricComputing,
  MetricComputing$inboundSchema,
} from "./metriccomputing.js";
import { MetricError, MetricError$inboundSchema } from "./metricerror.js";
import { MetricFailed, MetricFailed$inboundSchema } from "./metricfailed.js";
import {
  MetricNotApplicable,
  MetricNotApplicable$inboundSchema,
} from "./metricnotapplicable.js";
import {
  MetricNotComputed,
  MetricNotComputed$inboundSchema,
} from "./metricnotcomputed.js";
import { MetricPending, MetricPending$inboundSchema } from "./metricpending.js";
import { MetricRollUp, MetricRollUp$inboundSchema } from "./metricrollup.js";
import { Metrics, Metrics$inboundSchema } from "./metrics.js";
import { MetricSuccess, MetricSuccess$inboundSchema } from "./metricsuccess.js";
import {
  TextContentPart,
  TextContentPart$inboundSchema,
} from "./textcontentpart.js";

export type ExtendedSessionRecordInput1 =
  | FileContentPart
  | TextContentPart
  | discriminatedUnionTypes.Unknown<"type">;

export type ExtendedSessionRecordInput2 =
  | string
  | Array<GalileoCoreSchemasLoggingLlmMessage>
  | Array<
    FileContentPart | TextContentPart | discriminatedUnionTypes.Unknown<"type">
  >;

export type ExtendedSessionRecordRedactedInput1 =
  | FileContentPart
  | TextContentPart
  | discriminatedUnionTypes.Unknown<"type">;

/**
 * Redacted input of the trace or span.
 */
export type ExtendedSessionRecordRedactedInput2 =
  | string
  | Array<GalileoCoreSchemasLoggingLlmMessage>
  | Array<
    FileContentPart | TextContentPart | discriminatedUnionTypes.Unknown<"type">
  >;

export type ExtendedSessionRecordOutput1 =
  | FileContentPart
  | TextContentPart
  | discriminatedUnionTypes.Unknown<"type">;

/**
 * Output of the trace or span.
 */
export type ExtendedSessionRecordOutput2 =
  | GalileoCoreSchemasLoggingLlmMessage
  | ControlResult
  | string
  | Array<Document>
  | Array<
    FileContentPart | TextContentPart | discriminatedUnionTypes.Unknown<"type">
  >;

export type ExtendedSessionRecordRedactedOutput1 =
  | FileContentPart
  | TextContentPart
  | discriminatedUnionTypes.Unknown<"type">;

/**
 * Redacted output of the trace or span.
 */
export type ExtendedSessionRecordRedactedOutput2 =
  | GalileoCoreSchemasLoggingLlmMessage
  | ControlResult
  | string
  | Array<Document>
  | Array<
    FileContentPart | TextContentPart | discriminatedUnionTypes.Unknown<"type">
  >;

export type ExtendedSessionRecordMetricInfo =
  | MetricComputing
  | MetricError
  | MetricFailed
  | MetricNotApplicable
  | MetricNotComputed
  | MetricPending
  | MetricRollUp
  | MetricSuccess
  | discriminatedUnionTypes.Unknown<"statusType">;

export type ExtendedSessionRecord = {
  /**
   * Type of the trace, span or session.
   */
  type: "session";
  input?:
    | string
    | Array<GalileoCoreSchemasLoggingLlmMessage>
    | Array<
      | FileContentPart
      | TextContentPart
      | discriminatedUnionTypes.Unknown<"type">
    >
    | undefined;
  /**
   * Redacted input of the trace or span.
   */
  redactedInput?:
    | string
    | Array<GalileoCoreSchemasLoggingLlmMessage>
    | Array<
      | FileContentPart
      | TextContentPart
      | discriminatedUnionTypes.Unknown<"type">
    >
    | null
    | undefined;
  /**
   * Output of the trace or span.
   */
  output?:
    | GalileoCoreSchemasLoggingLlmMessage
    | ControlResult
    | string
    | Array<Document>
    | Array<
      | FileContentPart
      | TextContentPart
      | discriminatedUnionTypes.Unknown<"type">
    >
    | null
    | undefined;
  /**
   * Redacted output of the trace or span.
   */
  redactedOutput?:
    | GalileoCoreSchemasLoggingLlmMessage
    | ControlResult
    | string
    | Array<Document>
    | Array<
      | FileContentPart
      | TextContentPart
      | discriminatedUnionTypes.Unknown<"type">
    >
    | null
    | undefined;
  /**
   * Name of the trace, span or session.
   */
  name: string;
  /**
   * Timestamp of the trace or span's creation.
   */
  createdAt?: Date | undefined;
  /**
   * Metadata associated with this trace or span.
   */
  userMetadata?: { [k: string]: string } | undefined;
  /**
   * Tags associated with this trace or span.
   */
  tags?: Array<string> | undefined;
  /**
   * Status code of the trace or span. Used for logging failure or error states.
   */
  statusCode?: number | null | undefined;
  metrics?: Metrics | undefined;
  /**
   * A user-provided session, trace or span ID.
   */
  externalId?: string | null | undefined;
  /**
   * Input to the dataset associated with this trace
   */
  datasetInput?: string | null | undefined;
  /**
   * Output from the dataset associated with this trace
   */
  datasetOutput?: string | null | undefined;
  /**
   * Metadata from the dataset associated with this trace
   */
  datasetMetadata?: { [k: string]: string } | undefined;
  /**
   * Galileo ID of the session
   */
  id: string;
  /**
   * Galileo ID of the session containing the trace or span or session
   */
  sessionId?: string | null | undefined;
  /**
   * Galileo ID of the trace containing the span (or the same value as id for a trace)
   */
  traceId?: string | null | undefined;
  /**
   * Galileo ID of the project associated with this trace or span
   */
  projectId: string;
  /**
   * Galileo ID of the run (log stream or experiment) associated with this trace or span
   */
  runId: string;
  /**
   * Timestamp of the session or trace or span's last update
   */
  updatedAt?: Date | null | undefined;
  /**
   * Whether or not this trace or span has child spans
   */
  hasChildren?: boolean | null | undefined;
  /**
   * Galileo ID of the metrics batch associated with this trace or span
   */
  metricsBatchId?: string | null | undefined;
  /**
   * Galileo ID of the metrics batch associated with this trace or span
   */
  sessionBatchId?: string | null | undefined;
  /**
   * Feedback information related to the record
   */
  feedbackRatingInfo?: { [k: string]: FeedbackRatingInfo } | undefined;
  /**
   * Annotations keyed by template ID and annotator ID
   */
  annotations?:
    | { [k: string]: { [k: string]: AnnotationRatingInfo } }
    | undefined;
  /**
   * IDs of files associated with this record
   */
  fileIds?: Array<string> | undefined;
  /**
   * Modalities of files associated with this record
   */
  fileModalities?: Array<ContentModality> | undefined;
  /**
   * Annotation aggregate information keyed by template ID
   */
  annotationAggregates?: { [k: string]: AnnotationAggregate } | undefined;
  /**
   * IDs of annotation queues this record is in
   */
  annotationQueueIds?: Array<string> | undefined;
  /**
   * Detailed information about the metrics associated with this trace or span
   */
  metricInfo?:
    | {
      [k: string]:
        | MetricComputing
        | MetricError
        | MetricFailed
        | MetricNotApplicable
        | MetricNotComputed
        | MetricPending
        | MetricRollUp
        | MetricSuccess
        | discriminatedUnionTypes.Unknown<"statusType">;
    }
    | null
    | undefined;
  /**
   * File metadata keyed by file ID for files associated with this record
   */
  files?: { [k: string]: FileMetadata } | null | undefined;
  previousSessionId?: string | null | undefined;
  numTraces?: number | null | undefined;
};

/** @internal */
export const ExtendedSessionRecordInput1$inboundSchema: z.ZodMiniType<
  ExtendedSessionRecordInput1,
  unknown
> = discriminatedUnion("type", {
  file: FileContentPart$inboundSchema,
  text: TextContentPart$inboundSchema,
});

export function extendedSessionRecordInput1FromJSON(
  jsonString: string,
): SafeParseResult<ExtendedSessionRecordInput1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExtendedSessionRecordInput1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtendedSessionRecordInput1' from JSON`,
  );
}

/** @internal */
export const ExtendedSessionRecordInput2$inboundSchema: z.ZodMiniType<
  ExtendedSessionRecordInput2,
  unknown
> = smartUnion([
  types.string(),
  z.array(GalileoCoreSchemasLoggingLlmMessage$inboundSchema),
  z.array(
    discriminatedUnion("type", {
      file: FileContentPart$inboundSchema,
      text: TextContentPart$inboundSchema,
    }),
  ),
]);

export function extendedSessionRecordInput2FromJSON(
  jsonString: string,
): SafeParseResult<ExtendedSessionRecordInput2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExtendedSessionRecordInput2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtendedSessionRecordInput2' from JSON`,
  );
}

/** @internal */
export const ExtendedSessionRecordRedactedInput1$inboundSchema: z.ZodMiniType<
  ExtendedSessionRecordRedactedInput1,
  unknown
> = discriminatedUnion("type", {
  file: FileContentPart$inboundSchema,
  text: TextContentPart$inboundSchema,
});

export function extendedSessionRecordRedactedInput1FromJSON(
  jsonString: string,
): SafeParseResult<ExtendedSessionRecordRedactedInput1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExtendedSessionRecordRedactedInput1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtendedSessionRecordRedactedInput1' from JSON`,
  );
}

/** @internal */
export const ExtendedSessionRecordRedactedInput2$inboundSchema: z.ZodMiniType<
  ExtendedSessionRecordRedactedInput2,
  unknown
> = smartUnion([
  types.string(),
  z.array(GalileoCoreSchemasLoggingLlmMessage$inboundSchema),
  z.array(
    discriminatedUnion("type", {
      file: FileContentPart$inboundSchema,
      text: TextContentPart$inboundSchema,
    }),
  ),
]);

export function extendedSessionRecordRedactedInput2FromJSON(
  jsonString: string,
): SafeParseResult<ExtendedSessionRecordRedactedInput2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExtendedSessionRecordRedactedInput2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtendedSessionRecordRedactedInput2' from JSON`,
  );
}

/** @internal */
export const ExtendedSessionRecordOutput1$inboundSchema: z.ZodMiniType<
  ExtendedSessionRecordOutput1,
  unknown
> = discriminatedUnion("type", {
  file: FileContentPart$inboundSchema,
  text: TextContentPart$inboundSchema,
});

export function extendedSessionRecordOutput1FromJSON(
  jsonString: string,
): SafeParseResult<ExtendedSessionRecordOutput1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExtendedSessionRecordOutput1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtendedSessionRecordOutput1' from JSON`,
  );
}

/** @internal */
export const ExtendedSessionRecordOutput2$inboundSchema: z.ZodMiniType<
  ExtendedSessionRecordOutput2,
  unknown
> = smartUnion([
  GalileoCoreSchemasLoggingLlmMessage$inboundSchema,
  ControlResult$inboundSchema,
  types.string(),
  z.array(Document$inboundSchema),
  z.array(
    discriminatedUnion("type", {
      file: FileContentPart$inboundSchema,
      text: TextContentPart$inboundSchema,
    }),
  ),
]);

export function extendedSessionRecordOutput2FromJSON(
  jsonString: string,
): SafeParseResult<ExtendedSessionRecordOutput2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExtendedSessionRecordOutput2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtendedSessionRecordOutput2' from JSON`,
  );
}

/** @internal */
export const ExtendedSessionRecordRedactedOutput1$inboundSchema: z.ZodMiniType<
  ExtendedSessionRecordRedactedOutput1,
  unknown
> = discriminatedUnion("type", {
  file: FileContentPart$inboundSchema,
  text: TextContentPart$inboundSchema,
});

export function extendedSessionRecordRedactedOutput1FromJSON(
  jsonString: string,
): SafeParseResult<ExtendedSessionRecordRedactedOutput1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExtendedSessionRecordRedactedOutput1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtendedSessionRecordRedactedOutput1' from JSON`,
  );
}

/** @internal */
export const ExtendedSessionRecordRedactedOutput2$inboundSchema: z.ZodMiniType<
  ExtendedSessionRecordRedactedOutput2,
  unknown
> = smartUnion([
  GalileoCoreSchemasLoggingLlmMessage$inboundSchema,
  ControlResult$inboundSchema,
  types.string(),
  z.array(Document$inboundSchema),
  z.array(
    discriminatedUnion("type", {
      file: FileContentPart$inboundSchema,
      text: TextContentPart$inboundSchema,
    }),
  ),
]);

export function extendedSessionRecordRedactedOutput2FromJSON(
  jsonString: string,
): SafeParseResult<ExtendedSessionRecordRedactedOutput2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExtendedSessionRecordRedactedOutput2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtendedSessionRecordRedactedOutput2' from JSON`,
  );
}

/** @internal */
export const ExtendedSessionRecordMetricInfo$inboundSchema: z.ZodMiniType<
  ExtendedSessionRecordMetricInfo,
  unknown
> = discriminatedUnion("status_type", {
  computing: MetricComputing$inboundSchema,
  error: MetricError$inboundSchema,
  failed: MetricFailed$inboundSchema,
  not_applicable: MetricNotApplicable$inboundSchema,
  not_computed: MetricNotComputed$inboundSchema,
  pending: MetricPending$inboundSchema,
  roll_up: MetricRollUp$inboundSchema,
  success: MetricSuccess$inboundSchema,
}, { outputPropertyName: "statusType" });

export function extendedSessionRecordMetricInfoFromJSON(
  jsonString: string,
): SafeParseResult<ExtendedSessionRecordMetricInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExtendedSessionRecordMetricInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtendedSessionRecordMetricInfo' from JSON`,
  );
}

/** @internal */
export const ExtendedSessionRecord$inboundSchema: z.ZodMiniType<
  ExtendedSessionRecord,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("session"),
    input: types.optional(
      smartUnion([
        types.string(),
        z.array(GalileoCoreSchemasLoggingLlmMessage$inboundSchema),
        z.array(
          discriminatedUnion("type", {
            file: FileContentPart$inboundSchema,
            text: TextContentPart$inboundSchema,
          }),
        ),
      ]),
    ),
    redacted_input: z.optional(
      z.nullable(
        smartUnion([
          types.string(),
          z.array(GalileoCoreSchemasLoggingLlmMessage$inboundSchema),
          z.array(
            discriminatedUnion("type", {
              file: FileContentPart$inboundSchema,
              text: TextContentPart$inboundSchema,
            }),
          ),
        ]),
      ),
    ),
    output: z.optional(
      z.nullable(
        smartUnion([
          GalileoCoreSchemasLoggingLlmMessage$inboundSchema,
          ControlResult$inboundSchema,
          types.string(),
          z.array(Document$inboundSchema),
          z.array(
            discriminatedUnion("type", {
              file: FileContentPart$inboundSchema,
              text: TextContentPart$inboundSchema,
            }),
          ),
        ]),
      ),
    ),
    redacted_output: z.optional(
      z.nullable(
        smartUnion([
          GalileoCoreSchemasLoggingLlmMessage$inboundSchema,
          ControlResult$inboundSchema,
          types.string(),
          z.array(Document$inboundSchema),
          z.array(
            discriminatedUnion("type", {
              file: FileContentPart$inboundSchema,
              text: TextContentPart$inboundSchema,
            }),
          ),
        ]),
      ),
    ),
    name: z._default(types.string(), ""),
    created_at: types.optional(types.date()),
    user_metadata: types.optional(z.record(z.string(), types.string())),
    tags: types.optional(z.array(types.string())),
    status_code: z.optional(z.nullable(types.number())),
    metrics: types.optional(Metrics$inboundSchema),
    external_id: z.optional(z.nullable(types.string())),
    dataset_input: z.optional(z.nullable(types.string())),
    dataset_output: z.optional(z.nullable(types.string())),
    dataset_metadata: types.optional(z.record(z.string(), types.string())),
    id: types.string(),
    session_id: z.optional(z.nullable(types.string())),
    trace_id: z.optional(z.nullable(types.string())),
    project_id: types.string(),
    run_id: types.string(),
    updated_at: z.optional(z.nullable(types.date())),
    has_children: z.optional(z.nullable(types.boolean())),
    metrics_batch_id: z.optional(z.nullable(types.string())),
    session_batch_id: z.optional(z.nullable(types.string())),
    feedback_rating_info: types.optional(
      z.record(z.string(), FeedbackRatingInfo$inboundSchema),
    ),
    annotations: types.optional(
      z.record(
        z.string(),
        z.record(z.string(), AnnotationRatingInfo$inboundSchema),
      ),
    ),
    file_ids: types.optional(z.array(types.string())),
    file_modalities: types.optional(z.array(ContentModality$inboundSchema)),
    annotation_aggregates: types.optional(
      z.record(z.string(), AnnotationAggregate$inboundSchema),
    ),
    annotation_queue_ids: types.optional(z.array(types.string())),
    metric_info: z.optional(
      z.nullable(z.record(
        z.string(),
        discriminatedUnion("status_type", {
          computing: MetricComputing$inboundSchema,
          error: MetricError$inboundSchema,
          failed: MetricFailed$inboundSchema,
          not_applicable: MetricNotApplicable$inboundSchema,
          not_computed: MetricNotComputed$inboundSchema,
          pending: MetricPending$inboundSchema,
          roll_up: MetricRollUp$inboundSchema,
          success: MetricSuccess$inboundSchema,
        }, { outputPropertyName: "statusType" }),
      )),
    ),
    files: z.optional(
      z.nullable(z.record(z.string(), FileMetadata$inboundSchema)),
    ),
    previous_session_id: z.optional(z.nullable(types.string())),
    num_traces: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "redacted_input": "redactedInput",
      "redacted_output": "redactedOutput",
      "created_at": "createdAt",
      "user_metadata": "userMetadata",
      "status_code": "statusCode",
      "external_id": "externalId",
      "dataset_input": "datasetInput",
      "dataset_output": "datasetOutput",
      "dataset_metadata": "datasetMetadata",
      "session_id": "sessionId",
      "trace_id": "traceId",
      "project_id": "projectId",
      "run_id": "runId",
      "updated_at": "updatedAt",
      "has_children": "hasChildren",
      "metrics_batch_id": "metricsBatchId",
      "session_batch_id": "sessionBatchId",
      "feedback_rating_info": "feedbackRatingInfo",
      "file_ids": "fileIds",
      "file_modalities": "fileModalities",
      "annotation_aggregates": "annotationAggregates",
      "annotation_queue_ids": "annotationQueueIds",
      "metric_info": "metricInfo",
      "previous_session_id": "previousSessionId",
      "num_traces": "numTraces",
    });
  }),
);

export function extendedSessionRecordFromJSON(
  jsonString: string,
): SafeParseResult<ExtendedSessionRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExtendedSessionRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtendedSessionRecord' from JSON`,
  );
}
