/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7a5c3a86d7a2
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ContentModality,
  ContentModality$inboundSchema,
} from "./contentmodality.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { FileSource, FileSource$inboundSchema } from "./filesource.js";
import { FileStatus, FileStatus$inboundSchema } from "./filestatus.js";

/**
 * Enriched file metadata returned to UI/SDK.
 *
 * @remarks
 *
 * Contains presigned URLs and properties for displaying multimodal
 * content in the Galileo console and SDKs.
 */
export type FileMetadata = {
  fileId: string;
  /**
   * Classification of content modality
   */
  modality: ContentModality;
  contentType?: string | null | undefined;
  /**
   * Presigned S3 URL or external URL
   */
  url?: string | null | undefined;
  /**
   * Expiration time
   */
  urlExpiresAt?: Date | null | undefined;
  sizeBytes?: number | null | undefined;
  filename?: string | null | undefined;
  /**
   * Source of the file data.
   */
  source: FileSource;
  /**
   * Processing status of the file.
   */
  status: FileStatus;
};

/** @internal */
export const FileMetadata$inboundSchema: z.ZodMiniType<FileMetadata, unknown> =
  z.pipe(
    z.object({
      file_id: types.string(),
      modality: ContentModality$inboundSchema,
      content_type: z.optional(z.nullable(types.string())),
      url: z.optional(z.nullable(types.string())),
      url_expires_at: z.optional(z.nullable(types.date())),
      size_bytes: z.optional(z.nullable(types.number())),
      filename: z.optional(z.nullable(types.string())),
      source: FileSource$inboundSchema,
      status: FileStatus$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "file_id": "fileId",
        "content_type": "contentType",
        "url_expires_at": "urlExpiresAt",
        "size_bytes": "sizeBytes",
      });
    }),
  );

export function fileMetadataFromJSON(
  jsonString: string,
): SafeParseResult<FileMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileMetadata' from JSON`,
  );
}
