/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const FineTunedScorerAction = {
  Update: "update",
  Delete: "delete",
} as const;
export type FineTunedScorerAction = OpenEnum<typeof FineTunedScorerAction>;

/** @internal */
export const FineTunedScorerAction$inboundSchema: z.ZodMiniType<
  FineTunedScorerAction,
  unknown
> = openEnums.inboundSchema(FineTunedScorerAction);
