/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e558e0724ab9
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OutputTypeEnum,
  OutputTypeEnum$inboundSchema,
} from "./outputtypeenum.js";

export type GeneratedScorerConfiguration = {
  modelAlias: string;
  numJudges: number;
  /**
   * Enumeration of output types.
   */
  outputType?: OutputTypeEnum | undefined;
  /**
   * Types of nodes that can be scored by this scorer.
   */
  scoreableNodeTypes?: Array<string> | undefined;
  /**
   * Whether chain of thought is enabled for this scorer.
   */
  cotEnabled: boolean;
  /**
   * Whether ground truth is enabled for this scorer.
   */
  groundTruth: boolean;
};

/** @internal */
export const GeneratedScorerConfiguration$inboundSchema: z.ZodMiniType<
  GeneratedScorerConfiguration,
  unknown
> = z.pipe(
  z.object({
    model_alias: z._default(types.string(), "gpt-4.1-mini"),
    num_judges: z._default(types.number(), 3),
    output_type: types.optional(OutputTypeEnum$inboundSchema),
    scoreable_node_types: types.optional(z.array(types.string())),
    cot_enabled: z._default(types.boolean(), false),
    ground_truth: z._default(types.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      "model_alias": "modelAlias",
      "num_judges": "numJudges",
      "output_type": "outputType",
      "scoreable_node_types": "scoreableNodeTypes",
      "cot_enabled": "cotEnabled",
      "ground_truth": "groundTruth",
    });
  }),
);

export function generatedScorerConfigurationFromJSON(
  jsonString: string,
): SafeParseResult<GeneratedScorerConfiguration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeneratedScorerConfiguration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeneratedScorerConfiguration' from JSON`,
  );
}
