/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7e9592f13d2c
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type JobProgress = {
  progressMessage?: string | null | undefined;
  stepsCompleted?: number | null | undefined;
  stepsTotal?: number | null | undefined;
};

/** @internal */
export const JobProgress$inboundSchema: z.ZodMiniType<JobProgress, unknown> = z
  .pipe(
    z.object({
      progress_message: z.optional(z.nullable(types.string())),
      steps_completed: z.optional(z.nullable(types.number())),
      steps_total: z.optional(z.nullable(types.number())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "progress_message": "progressMessage",
        "steps_completed": "stepsCompleted",
        "steps_total": "stepsTotal",
      });
    }),
  );

export function jobProgressFromJSON(
  jsonString: string,
): SafeParseResult<JobProgress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JobProgress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JobProgress' from JSON`,
  );
}
