/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 649b12f16ef7
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type LibsPythonSchemasLogRecordsFeedbackChoiceRating = {
  feedbackType: "choice";
  value: string;
};

/** @internal */
export const LibsPythonSchemasLogRecordsFeedbackChoiceRating$inboundSchema:
  z.ZodMiniType<LibsPythonSchemasLogRecordsFeedbackChoiceRating, unknown> = z
    .pipe(
      z.object({
        feedback_type: types.literal("choice"),
        value: types.string(),
      }),
      z.transform((v) => {
        return remap$(v, {
          "feedback_type": "feedbackType",
        });
      }),
    );

export function libsPythonSchemasLogRecordsFeedbackChoiceRatingFromJSON(
  jsonString: string,
): SafeParseResult<
  LibsPythonSchemasLogRecordsFeedbackChoiceRating,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      LibsPythonSchemasLogRecordsFeedbackChoiceRating$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'LibsPythonSchemasLogRecordsFeedbackChoiceRating' from JSON`,
  );
}
