/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PromptDatasetDB,
  PromptDatasetDB$inboundSchema,
} from "./promptdatasetdb.js";

export type ListPromptDatasetResponse = {
  startingToken: number;
  limit: number;
  paginated: boolean;
  nextStartingToken?: number | null | undefined;
  datasets?: Array<PromptDatasetDB> | undefined;
};

/** @internal */
export const ListPromptDatasetResponse$inboundSchema: z.ZodMiniType<
  ListPromptDatasetResponse,
  unknown
> = z.pipe(
  z.object({
    starting_token: z._default(types.number(), 0),
    limit: z._default(types.number(), 100),
    paginated: z._default(types.boolean(), false),
    next_starting_token: z.optional(z.nullable(types.number())),
    datasets: types.optional(z.array(PromptDatasetDB$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "starting_token": "startingToken",
      "next_starting_token": "nextStartingToken",
    });
  }),
);

export function listPromptDatasetResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPromptDatasetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPromptDatasetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPromptDatasetResponse' from JSON`,
  );
}
