/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smartUnion.js";

export const LogRecordsCollectionFilterOperator = {
  Eq: "eq",
  Contains: "contains",
  NotIn: "not_in",
} as const;
export type LogRecordsCollectionFilterOperator = ClosedEnum<
  typeof LogRecordsCollectionFilterOperator
>;

export type LogRecordsCollectionFilterValue = string | Array<string>;

export type LogRecordsCollectionFilter = {
  /**
   * ID of the column to filter.
   */
  columnId: string;
  operator: LogRecordsCollectionFilterOperator;
  value: string | Array<string>;
  caseSensitive?: boolean | undefined;
  type: "collection";
};

/** @internal */
export const LogRecordsCollectionFilterOperator$outboundSchema: z.ZodMiniEnum<
  typeof LogRecordsCollectionFilterOperator
> = z.enum(LogRecordsCollectionFilterOperator);

/** @internal */
export type LogRecordsCollectionFilterValue$Outbound = string | Array<string>;

/** @internal */
export const LogRecordsCollectionFilterValue$outboundSchema: z.ZodMiniType<
  LogRecordsCollectionFilterValue$Outbound,
  LogRecordsCollectionFilterValue
> = smartUnion([z.string(), z.array(z.string())]);

export function logRecordsCollectionFilterValueToJSON(
  logRecordsCollectionFilterValue: LogRecordsCollectionFilterValue,
): string {
  return JSON.stringify(
    LogRecordsCollectionFilterValue$outboundSchema.parse(
      logRecordsCollectionFilterValue,
    ),
  );
}

/** @internal */
export type LogRecordsCollectionFilter$Outbound = {
  column_id: string;
  operator: string;
  value: string | Array<string>;
  case_sensitive: boolean;
  type: "collection";
};

/** @internal */
export const LogRecordsCollectionFilter$outboundSchema: z.ZodMiniType<
  LogRecordsCollectionFilter$Outbound,
  LogRecordsCollectionFilter
> = z.pipe(
  z.object({
    columnId: z.string(),
    operator: LogRecordsCollectionFilterOperator$outboundSchema,
    value: smartUnion([z.string(), z.array(z.string())]),
    caseSensitive: z._default(z.boolean(), true),
    type: z.literal("collection"),
  }),
  z.transform((v) => {
    return remap$(v, {
      columnId: "column_id",
      caseSensitive: "case_sensitive",
    });
  }),
);

export function logRecordsCollectionFilterToJSON(
  logRecordsCollectionFilter: LogRecordsCollectionFilter,
): string {
  return JSON.stringify(
    LogRecordsCollectionFilter$outboundSchema.parse(logRecordsCollectionFilter),
  );
}
