/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType,
  FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType$Outbound,
  FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType$outboundSchema,
} from "./filterexpressionannotatedunionlogrecordsidfilterlogrecordsdatefilterlogrecordsnumberfilterlogrecordsbooleanfilterlogrecordscollectionfilterlogrecordstextfilterfieldinfoannotationnonetyperequiredtruediscriminatortype.js";
import {
  LogRecordsBooleanFilter,
  LogRecordsBooleanFilter$Outbound,
  LogRecordsBooleanFilter$outboundSchema,
} from "./logrecordsbooleanfilter.js";
import {
  LogRecordsCollectionFilter,
  LogRecordsCollectionFilter$Outbound,
  LogRecordsCollectionFilter$outboundSchema,
} from "./logrecordscollectionfilter.js";
import {
  LogRecordsDateFilter,
  LogRecordsDateFilter$Outbound,
  LogRecordsDateFilter$outboundSchema,
} from "./logrecordsdatefilter.js";
import {
  LogRecordsIDFilter,
  LogRecordsIDFilter$Outbound,
  LogRecordsIDFilter$outboundSchema,
} from "./logrecordsidfilter.js";
import {
  LogRecordsNumberFilter,
  LogRecordsNumberFilter$Outbound,
  LogRecordsNumberFilter$outboundSchema,
} from "./logrecordsnumberfilter.js";
import {
  LogRecordsSortClause,
  LogRecordsSortClause$Outbound,
  LogRecordsSortClause$outboundSchema,
} from "./logrecordssortclause.js";
import {
  LogRecordsTextFilter,
  LogRecordsTextFilter$Outbound,
  LogRecordsTextFilter$outboundSchema,
} from "./logrecordstextfilter.js";

export type LogRecordsQueryRequestFilter =
  | LogRecordsBooleanFilter
  | LogRecordsCollectionFilter
  | LogRecordsDateFilter
  | LogRecordsIDFilter
  | LogRecordsNumberFilter
  | LogRecordsTextFilter;

export type LogRecordsQueryRequest = {
  startingToken?: number | undefined;
  limit?: number | undefined;
  previousLastRowId?: string | null | undefined;
  /**
   * Log stream id associated with the traces.
   */
  logStreamId?: string | null | undefined;
  /**
   * Experiment id associated with the traces.
   */
  experimentId?: string | null | undefined;
  /**
   * Metrics testing id associated with the traces.
   */
  metricsTestingId?: string | null | undefined;
  filters?:
    | Array<
      | LogRecordsBooleanFilter
      | LogRecordsCollectionFilter
      | LogRecordsDateFilter
      | LogRecordsIDFilter
      | LogRecordsNumberFilter
      | LogRecordsTextFilter
    >
    | undefined;
  filterTree?:
    | FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType
    | null
    | undefined;
  /**
   * Sort for the query.  Defaults to native sort (created_at, id descending).
   */
  sort?: LogRecordsSortClause | null | undefined;
  truncateFields?: boolean | undefined;
  /**
   * If True, include computed child counts (e.g., num_traces for sessions, num_spans for traces).
   */
  includeCounts?: boolean | undefined;
};

/** @internal */
export type LogRecordsQueryRequestFilter$Outbound =
  | LogRecordsBooleanFilter$Outbound
  | LogRecordsCollectionFilter$Outbound
  | LogRecordsDateFilter$Outbound
  | LogRecordsIDFilter$Outbound
  | LogRecordsNumberFilter$Outbound
  | LogRecordsTextFilter$Outbound;

/** @internal */
export const LogRecordsQueryRequestFilter$outboundSchema: z.ZodMiniType<
  LogRecordsQueryRequestFilter$Outbound,
  LogRecordsQueryRequestFilter
> = z.union([
  LogRecordsBooleanFilter$outboundSchema,
  LogRecordsCollectionFilter$outboundSchema,
  LogRecordsDateFilter$outboundSchema,
  LogRecordsIDFilter$outboundSchema,
  LogRecordsNumberFilter$outboundSchema,
  LogRecordsTextFilter$outboundSchema,
]);

export function logRecordsQueryRequestFilterToJSON(
  logRecordsQueryRequestFilter: LogRecordsQueryRequestFilter,
): string {
  return JSON.stringify(
    LogRecordsQueryRequestFilter$outboundSchema.parse(
      logRecordsQueryRequestFilter,
    ),
  );
}

/** @internal */
export type LogRecordsQueryRequest$Outbound = {
  starting_token: number;
  limit: number;
  previous_last_row_id?: string | null | undefined;
  log_stream_id?: string | null | undefined;
  experiment_id?: string | null | undefined;
  metrics_testing_id?: string | null | undefined;
  filters?:
    | Array<
      | LogRecordsBooleanFilter$Outbound
      | LogRecordsCollectionFilter$Outbound
      | LogRecordsDateFilter$Outbound
      | LogRecordsIDFilter$Outbound
      | LogRecordsNumberFilter$Outbound
      | LogRecordsTextFilter$Outbound
    >
    | undefined;
  filter_tree?:
    | FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType$Outbound
    | null
    | undefined;
  sort?: LogRecordsSortClause$Outbound | null | undefined;
  truncate_fields: boolean;
  include_counts: boolean;
};

/** @internal */
export const LogRecordsQueryRequest$outboundSchema: z.ZodMiniType<
  LogRecordsQueryRequest$Outbound,
  LogRecordsQueryRequest
> = z.pipe(
  z.object({
    startingToken: z._default(z.int(), 0),
    limit: z._default(z.int(), 100),
    previousLastRowId: z.optional(z.nullable(z.string())),
    logStreamId: z.optional(z.nullable(z.string())),
    experimentId: z.optional(z.nullable(z.string())),
    metricsTestingId: z.optional(z.nullable(z.string())),
    filters: z.optional(
      z.array(
        z.union([
          LogRecordsBooleanFilter$outboundSchema,
          LogRecordsCollectionFilter$outboundSchema,
          LogRecordsDateFilter$outboundSchema,
          LogRecordsIDFilter$outboundSchema,
          LogRecordsNumberFilter$outboundSchema,
          LogRecordsTextFilter$outboundSchema,
        ]),
      ),
    ),
    filterTree: z.optional(
      z.nullable(
        FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType$outboundSchema,
      ),
    ),
    sort: z.optional(z.nullable(LogRecordsSortClause$outboundSchema)),
    truncateFields: z._default(z.boolean(), false),
    includeCounts: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      startingToken: "starting_token",
      previousLastRowId: "previous_last_row_id",
      logStreamId: "log_stream_id",
      experimentId: "experiment_id",
      metricsTestingId: "metrics_testing_id",
      filterTree: "filter_tree",
      truncateFields: "truncate_fields",
      includeCounts: "include_counts",
    });
  }),
);

export function logRecordsQueryRequestToJSON(
  logRecordsQueryRequest: LogRecordsQueryRequest,
): string {
  return JSON.stringify(
    LogRecordsQueryRequest$outboundSchema.parse(logRecordsQueryRequest),
  );
}
