/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4ef5b95b1792
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type LogRecordsAvailableColumnsRequest = {
  /**
   * Log stream id associated with the traces.
   */
  logStreamId?: string | null | undefined;
  /**
   * Experiment id associated with the traces.
   */
  experimentId?: string | null | undefined;
  /**
   * Metrics testing id associated with the traces.
   */
  metricsTestingId?: string | null | undefined;
  startTime?: Date | null | undefined;
  endTime?: Date | null | undefined;
};

/** @internal */
export type LogRecordsAvailableColumnsRequest$Outbound = {
  log_stream_id?: string | null | undefined;
  experiment_id?: string | null | undefined;
  metrics_testing_id?: string | null | undefined;
  start_time?: string | null | undefined;
  end_time?: string | null | undefined;
};

/** @internal */
export const LogRecordsAvailableColumnsRequest$outboundSchema: z.ZodMiniType<
  LogRecordsAvailableColumnsRequest$Outbound,
  LogRecordsAvailableColumnsRequest
> = z.pipe(
  z.object({
    logStreamId: z.optional(z.nullable(z.string())),
    experimentId: z.optional(z.nullable(z.string())),
    metricsTestingId: z.optional(z.nullable(z.string())),
    startTime: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    endTime: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      logStreamId: "log_stream_id",
      experimentId: "experiment_id",
      metricsTestingId: "metrics_testing_id",
      startTime: "start_time",
      endTime: "end_time",
    });
  }),
);

export function logRecordsAvailableColumnsRequestToJSON(
  logRecordsAvailableColumnsRequest: LogRecordsAvailableColumnsRequest,
): string {
  return JSON.stringify(
    LogRecordsAvailableColumnsRequest$outboundSchema.parse(
      logRecordsAvailableColumnsRequest,
    ),
  );
}
