/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 54506a76a8ba
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type LogRecordsQueryCountResponse = {
  /**
   * Total number of records matching the query
   */
  totalCount: number;
};

/** @internal */
export const LogRecordsQueryCountResponse$inboundSchema: z.ZodMiniType<
  LogRecordsQueryCountResponse,
  unknown
> = z.pipe(
  z.object({
    total_count: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "total_count": "totalCount",
    });
  }),
);

export function logRecordsQueryCountResponseFromJSON(
  jsonString: string,
): SafeParseResult<LogRecordsQueryCountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LogRecordsQueryCountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LogRecordsQueryCountResponse' from JSON`,
  );
}
