/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9a568890477a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PartialExtendedAgentSpanRecord,
  PartialExtendedAgentSpanRecord$inboundSchema,
} from "./partialextendedagentspanrecord.js";
import {
  PartialExtendedLlmSpanRecord,
  PartialExtendedLlmSpanRecord$inboundSchema,
} from "./partialextendedllmspanrecord.js";
import {
  PartialExtendedRetrieverSpanRecord,
  PartialExtendedRetrieverSpanRecord$inboundSchema,
} from "./partialextendedretrieverspanrecord.js";
import {
  PartialExtendedSessionRecord,
  PartialExtendedSessionRecord$inboundSchema,
} from "./partialextendedsessionrecord.js";
import {
  PartialExtendedToolSpanRecord,
  PartialExtendedToolSpanRecord$inboundSchema,
} from "./partialextendedtoolspanrecord.js";
import {
  PartialExtendedTraceRecord,
  PartialExtendedTraceRecord$inboundSchema,
} from "./partialextendedtracerecord.js";
import {
  PartialExtendedWorkflowSpanRecord,
  PartialExtendedWorkflowSpanRecord$inboundSchema,
} from "./partialextendedworkflowspanrecord.js";

export type LogRecordsPartialQueryResponseRecord =
  | PartialExtendedAgentSpanRecord
  | PartialExtendedLlmSpanRecord
  | PartialExtendedRetrieverSpanRecord
  | PartialExtendedSessionRecord
  | PartialExtendedToolSpanRecord
  | PartialExtendedTraceRecord
  | PartialExtendedWorkflowSpanRecord
  | discriminatedUnionTypes.Unknown<"type">;

export type LogRecordsPartialQueryResponse = {
  startingToken: number;
  limit: number;
  paginated: boolean;
  nextStartingToken?: number | null | undefined;
  lastRowId?: string | null | undefined;
  /**
   * records matching the query
   */
  records?:
    | Array<
      | PartialExtendedAgentSpanRecord
      | PartialExtendedLlmSpanRecord
      | PartialExtendedRetrieverSpanRecord
      | PartialExtendedSessionRecord
      | PartialExtendedToolSpanRecord
      | PartialExtendedTraceRecord
      | PartialExtendedWorkflowSpanRecord
      | discriminatedUnionTypes.Unknown<"type">
    >
    | undefined;
};

/** @internal */
export const LogRecordsPartialQueryResponseRecord$inboundSchema: z.ZodMiniType<
  LogRecordsPartialQueryResponseRecord,
  unknown
> = discriminatedUnion("type", {
  agent: PartialExtendedAgentSpanRecord$inboundSchema,
  llm: PartialExtendedLlmSpanRecord$inboundSchema,
  retriever: PartialExtendedRetrieverSpanRecord$inboundSchema,
  session: PartialExtendedSessionRecord$inboundSchema,
  tool: PartialExtendedToolSpanRecord$inboundSchema,
  trace: PartialExtendedTraceRecord$inboundSchema,
  workflow: PartialExtendedWorkflowSpanRecord$inboundSchema,
});

export function logRecordsPartialQueryResponseRecordFromJSON(
  jsonString: string,
): SafeParseResult<LogRecordsPartialQueryResponseRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LogRecordsPartialQueryResponseRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LogRecordsPartialQueryResponseRecord' from JSON`,
  );
}

/** @internal */
export const LogRecordsPartialQueryResponse$inboundSchema: z.ZodMiniType<
  LogRecordsPartialQueryResponse,
  unknown
> = z.pipe(
  z.object({
    starting_token: z._default(types.number(), 0),
    limit: z._default(types.number(), 100),
    paginated: z._default(types.boolean(), false),
    next_starting_token: z.optional(z.nullable(types.number())),
    last_row_id: z.optional(z.nullable(types.string())),
    records: types.optional(z.array(discriminatedUnion("type", {
      agent: PartialExtendedAgentSpanRecord$inboundSchema,
      llm: PartialExtendedLlmSpanRecord$inboundSchema,
      retriever: PartialExtendedRetrieverSpanRecord$inboundSchema,
      session: PartialExtendedSessionRecord$inboundSchema,
      tool: PartialExtendedToolSpanRecord$inboundSchema,
      trace: PartialExtendedTraceRecord$inboundSchema,
      workflow: PartialExtendedWorkflowSpanRecord$inboundSchema,
    }))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "starting_token": "startingToken",
      "next_starting_token": "nextStartingToken",
      "last_row_id": "lastRowId",
    });
  }),
);

export function logRecordsPartialQueryResponseFromJSON(
  jsonString: string,
): SafeParseResult<LogRecordsPartialQueryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LogRecordsPartialQueryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LogRecordsPartialQueryResponse' from JSON`,
  );
}
