/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: afeb7f52b6ff
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterLogRecordsFullyAnnotatedFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType,
  FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterLogRecordsFullyAnnotatedFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType$Outbound,
  FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterLogRecordsFullyAnnotatedFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType$outboundSchema,
} from "./filterexpressionannotatedunionlogrecordsidfilterlogrecordsdatefilterlogrecordsnumberfilterlogrecordsbooleanfilterlogrecordscollectionfilterlogrecordstextfilterlogrecordsfullyannotatedfilterfieldinfoannotationnonetyperequiredtruedis_38eba81e.js";
import {
  LogRecordsBooleanFilter,
  LogRecordsBooleanFilter$Outbound,
  LogRecordsBooleanFilter$outboundSchema,
} from "./logrecordsbooleanfilter.js";
import {
  LogRecordsCollectionFilter,
  LogRecordsCollectionFilter$Outbound,
  LogRecordsCollectionFilter$outboundSchema,
} from "./logrecordscollectionfilter.js";
import {
  LogRecordsDateFilter,
  LogRecordsDateFilter$Outbound,
  LogRecordsDateFilter$outboundSchema,
} from "./logrecordsdatefilter.js";
import {
  LogRecordsFullyAnnotatedFilter,
  LogRecordsFullyAnnotatedFilter$Outbound,
  LogRecordsFullyAnnotatedFilter$outboundSchema,
} from "./logrecordsfullyannotatedfilter.js";
import {
  LogRecordsIDFilter,
  LogRecordsIDFilter$Outbound,
  LogRecordsIDFilter$outboundSchema,
} from "./logrecordsidfilter.js";
import {
  LogRecordsNumberFilter,
  LogRecordsNumberFilter$Outbound,
  LogRecordsNumberFilter$outboundSchema,
} from "./logrecordsnumberfilter.js";
import {
  LogRecordsSortClause,
  LogRecordsSortClause$Outbound,
  LogRecordsSortClause$outboundSchema,
} from "./logrecordssortclause.js";
import {
  LogRecordsTextFilter,
  LogRecordsTextFilter$Outbound,
  LogRecordsTextFilter$outboundSchema,
} from "./logrecordstextfilter.js";
import {
  SelectColumns,
  SelectColumns$Outbound,
  SelectColumns$outboundSchema,
} from "./selectcolumns.js";

export type LogRecordsPartialQueryRequestFilter =
  | LogRecordsBooleanFilter
  | LogRecordsCollectionFilter
  | LogRecordsDateFilter
  | LogRecordsFullyAnnotatedFilter
  | LogRecordsIDFilter
  | LogRecordsNumberFilter
  | LogRecordsTextFilter;

/**
 * Request to query a genai project run (log stream or experiment) with partial results.
 */
export type LogRecordsPartialQueryRequest = {
  startingToken?: number | undefined;
  limit?: number | undefined;
  previousLastRowId?: string | null | undefined;
  /**
   * Log stream id associated with the traces.
   */
  logStreamId?: string | null | undefined;
  /**
   * Experiment id associated with the traces.
   */
  experimentId?: string | null | undefined;
  /**
   * Metrics testing id associated with the traces.
   */
  metricsTestingId?: string | null | undefined;
  filters?:
    | Array<
      | LogRecordsBooleanFilter
      | LogRecordsCollectionFilter
      | LogRecordsDateFilter
      | LogRecordsFullyAnnotatedFilter
      | LogRecordsIDFilter
      | LogRecordsNumberFilter
      | LogRecordsTextFilter
    >
    | undefined;
  filterTree?:
    | FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterLogRecordsFullyAnnotatedFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType
    | null
    | undefined;
  /**
   * Sort for the query.  Defaults to native sort (created_at, id descending).
   */
  sort?: LogRecordsSortClause | null | undefined;
  truncateFields?: boolean | undefined;
  /**
   * If True, include computed child counts (e.g., num_traces for sessions, num_spans for traces).
   */
  includeCounts?: boolean | undefined;
  /**
   * If True, include per-row scorer metadata (the dict returned alongside the score by code-based scorers via the (score, metadata) tuple-return contract) on each MetricSuccess in the response. Off by default to keep payloads small for callers that don't need it.
   */
  includeCodeMetricMetadata?: boolean | undefined;
  selectColumns: SelectColumns;
};

/** @internal */
export type LogRecordsPartialQueryRequestFilter$Outbound =
  | LogRecordsBooleanFilter$Outbound
  | LogRecordsCollectionFilter$Outbound
  | LogRecordsDateFilter$Outbound
  | LogRecordsFullyAnnotatedFilter$Outbound
  | LogRecordsIDFilter$Outbound
  | LogRecordsNumberFilter$Outbound
  | LogRecordsTextFilter$Outbound;

/** @internal */
export const LogRecordsPartialQueryRequestFilter$outboundSchema: z.ZodMiniType<
  LogRecordsPartialQueryRequestFilter$Outbound,
  LogRecordsPartialQueryRequestFilter
> = z.union([
  LogRecordsBooleanFilter$outboundSchema,
  LogRecordsCollectionFilter$outboundSchema,
  LogRecordsDateFilter$outboundSchema,
  LogRecordsFullyAnnotatedFilter$outboundSchema,
  LogRecordsIDFilter$outboundSchema,
  LogRecordsNumberFilter$outboundSchema,
  LogRecordsTextFilter$outboundSchema,
]);

export function logRecordsPartialQueryRequestFilterToJSON(
  logRecordsPartialQueryRequestFilter: LogRecordsPartialQueryRequestFilter,
): string {
  return JSON.stringify(
    LogRecordsPartialQueryRequestFilter$outboundSchema.parse(
      logRecordsPartialQueryRequestFilter,
    ),
  );
}

/** @internal */
export type LogRecordsPartialQueryRequest$Outbound = {
  starting_token: number;
  limit: number;
  previous_last_row_id?: string | null | undefined;
  log_stream_id?: string | null | undefined;
  experiment_id?: string | null | undefined;
  metrics_testing_id?: string | null | undefined;
  filters?:
    | Array<
      | LogRecordsBooleanFilter$Outbound
      | LogRecordsCollectionFilter$Outbound
      | LogRecordsDateFilter$Outbound
      | LogRecordsFullyAnnotatedFilter$Outbound
      | LogRecordsIDFilter$Outbound
      | LogRecordsNumberFilter$Outbound
      | LogRecordsTextFilter$Outbound
    >
    | undefined;
  filter_tree?:
    | FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterLogRecordsFullyAnnotatedFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType$Outbound
    | null
    | undefined;
  sort?: LogRecordsSortClause$Outbound | null | undefined;
  truncate_fields: boolean;
  include_counts: boolean;
  include_code_metric_metadata: boolean;
  select_columns: SelectColumns$Outbound;
};

/** @internal */
export const LogRecordsPartialQueryRequest$outboundSchema: z.ZodMiniType<
  LogRecordsPartialQueryRequest$Outbound,
  LogRecordsPartialQueryRequest
> = z.pipe(
  z.object({
    startingToken: z._default(z.int(), 0),
    limit: z._default(z.int(), 100),
    previousLastRowId: z.optional(z.nullable(z.string())),
    logStreamId: z.optional(z.nullable(z.string())),
    experimentId: z.optional(z.nullable(z.string())),
    metricsTestingId: z.optional(z.nullable(z.string())),
    filters: z.optional(
      z.array(
        z.union([
          LogRecordsBooleanFilter$outboundSchema,
          LogRecordsCollectionFilter$outboundSchema,
          LogRecordsDateFilter$outboundSchema,
          LogRecordsFullyAnnotatedFilter$outboundSchema,
          LogRecordsIDFilter$outboundSchema,
          LogRecordsNumberFilter$outboundSchema,
          LogRecordsTextFilter$outboundSchema,
        ]),
      ),
    ),
    filterTree: z.optional(
      z.nullable(
        FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterLogRecordsFullyAnnotatedFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType$outboundSchema,
      ),
    ),
    sort: z.optional(z.nullable(LogRecordsSortClause$outboundSchema)),
    truncateFields: z._default(z.boolean(), false),
    includeCounts: z._default(z.boolean(), false),
    includeCodeMetricMetadata: z._default(z.boolean(), false),
    selectColumns: SelectColumns$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      startingToken: "starting_token",
      previousLastRowId: "previous_last_row_id",
      logStreamId: "log_stream_id",
      experimentId: "experiment_id",
      metricsTestingId: "metrics_testing_id",
      filterTree: "filter_tree",
      truncateFields: "truncate_fields",
      includeCounts: "include_counts",
      includeCodeMetricMetadata: "include_code_metric_metadata",
      selectColumns: "select_columns",
    });
  }),
);

export function logRecordsPartialQueryRequestToJSON(
  logRecordsPartialQueryRequest: LogRecordsPartialQueryRequest,
): string {
  return JSON.stringify(
    LogRecordsPartialQueryRequest$outboundSchema.parse(
      logRecordsPartialQueryRequest,
    ),
  );
}
