/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  LogStreamCreatedAtFilter,
  LogStreamCreatedAtFilter$Outbound,
  LogStreamCreatedAtFilter$outboundSchema,
} from "./logstreamcreatedatfilter.js";
import {
  LogStreamCreatedAtSort,
  LogStreamCreatedAtSort$Outbound,
  LogStreamCreatedAtSort$outboundSchema,
} from "./logstreamcreatedatsort.js";
import {
  LogStreamCreatedByFilter,
  LogStreamCreatedByFilter$Outbound,
  LogStreamCreatedByFilter$outboundSchema,
} from "./logstreamcreatedbyfilter.js";
import {
  LogStreamIDFilter,
  LogStreamIDFilter$Outbound,
  LogStreamIDFilter$outboundSchema,
} from "./logstreamidfilter.js";
import {
  LogStreamNameFilter,
  LogStreamNameFilter$Outbound,
  LogStreamNameFilter$outboundSchema,
} from "./logstreamnamefilter.js";
import {
  LogStreamNameSort,
  LogStreamNameSort$Outbound,
  LogStreamNameSort$outboundSchema,
} from "./logstreamnamesort.js";
import {
  LogStreamUpdatedAtFilter,
  LogStreamUpdatedAtFilter$Outbound,
  LogStreamUpdatedAtFilter$outboundSchema,
} from "./logstreamupdatedatfilter.js";
import {
  LogStreamUpdatedAtSort,
  LogStreamUpdatedAtSort$Outbound,
  LogStreamUpdatedAtSort$outboundSchema,
} from "./logstreamupdatedatsort.js";

export type LogStreamSearchRequestFilter =
  | LogStreamCreatedAtFilter
  | LogStreamCreatedByFilter
  | LogStreamIDFilter
  | LogStreamNameFilter
  | LogStreamUpdatedAtFilter;

export type LogStreamSearchRequestSort =
  | LogStreamCreatedAtSort
  | LogStreamNameSort
  | LogStreamUpdatedAtSort;

export type LogStreamSearchRequest = {
  startingToken?: number | undefined;
  limit?: number | undefined;
  filters?:
    | Array<
      | LogStreamCreatedAtFilter
      | LogStreamCreatedByFilter
      | LogStreamIDFilter
      | LogStreamNameFilter
      | LogStreamUpdatedAtFilter
    >
    | undefined;
  sort?:
    | LogStreamCreatedAtSort
    | LogStreamNameSort
    | LogStreamUpdatedAtSort
    | null
    | undefined;
  includeCounts?: boolean | undefined;
};

/** @internal */
export type LogStreamSearchRequestFilter$Outbound =
  | LogStreamCreatedAtFilter$Outbound
  | LogStreamCreatedByFilter$Outbound
  | LogStreamIDFilter$Outbound
  | LogStreamNameFilter$Outbound
  | LogStreamUpdatedAtFilter$Outbound;

/** @internal */
export const LogStreamSearchRequestFilter$outboundSchema: z.ZodMiniType<
  LogStreamSearchRequestFilter$Outbound,
  LogStreamSearchRequestFilter
> = z.union([
  LogStreamCreatedAtFilter$outboundSchema,
  LogStreamCreatedByFilter$outboundSchema,
  LogStreamIDFilter$outboundSchema,
  LogStreamNameFilter$outboundSchema,
  LogStreamUpdatedAtFilter$outboundSchema,
]);

export function logStreamSearchRequestFilterToJSON(
  logStreamSearchRequestFilter: LogStreamSearchRequestFilter,
): string {
  return JSON.stringify(
    LogStreamSearchRequestFilter$outboundSchema.parse(
      logStreamSearchRequestFilter,
    ),
  );
}

/** @internal */
export type LogStreamSearchRequestSort$Outbound =
  | LogStreamCreatedAtSort$Outbound
  | LogStreamNameSort$Outbound
  | LogStreamUpdatedAtSort$Outbound;

/** @internal */
export const LogStreamSearchRequestSort$outboundSchema: z.ZodMiniType<
  LogStreamSearchRequestSort$Outbound,
  LogStreamSearchRequestSort
> = z.union([
  LogStreamCreatedAtSort$outboundSchema,
  LogStreamNameSort$outboundSchema,
  LogStreamUpdatedAtSort$outboundSchema,
]);

export function logStreamSearchRequestSortToJSON(
  logStreamSearchRequestSort: LogStreamSearchRequestSort,
): string {
  return JSON.stringify(
    LogStreamSearchRequestSort$outboundSchema.parse(logStreamSearchRequestSort),
  );
}

/** @internal */
export type LogStreamSearchRequest$Outbound = {
  starting_token: number;
  limit: number;
  filters?:
    | Array<
      | LogStreamCreatedAtFilter$Outbound
      | LogStreamCreatedByFilter$Outbound
      | LogStreamIDFilter$Outbound
      | LogStreamNameFilter$Outbound
      | LogStreamUpdatedAtFilter$Outbound
    >
    | undefined;
  sort?:
    | LogStreamCreatedAtSort$Outbound
    | LogStreamNameSort$Outbound
    | LogStreamUpdatedAtSort$Outbound
    | null
    | undefined;
  include_counts: boolean;
};

/** @internal */
export const LogStreamSearchRequest$outboundSchema: z.ZodMiniType<
  LogStreamSearchRequest$Outbound,
  LogStreamSearchRequest
> = z.pipe(
  z.object({
    startingToken: z._default(z.int(), 0),
    limit: z._default(z.int(), 100),
    filters: z.optional(
      z.array(
        z.union([
          LogStreamCreatedAtFilter$outboundSchema,
          LogStreamCreatedByFilter$outboundSchema,
          LogStreamIDFilter$outboundSchema,
          LogStreamNameFilter$outboundSchema,
          LogStreamUpdatedAtFilter$outboundSchema,
        ]),
      ),
    ),
    sort: z.optional(
      z.nullable(
        z.union([
          LogStreamCreatedAtSort$outboundSchema,
          LogStreamNameSort$outboundSchema,
          LogStreamUpdatedAtSort$outboundSchema,
        ]),
      ),
    ),
    includeCounts: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      startingToken: "starting_token",
      includeCounts: "include_counts",
    });
  }),
);

export function logStreamSearchRequestToJSON(
  logStreamSearchRequest: LogStreamSearchRequest,
): string {
  return JSON.stringify(
    LogStreamSearchRequest$outboundSchema.parse(logStreamSearchRequest),
  );
}
