/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  EventStatus,
  EventStatus$inboundSchema,
  EventStatus$outboundSchema,
} from "./eventstatus.js";

/**
 * MCP list tools event - when the model queries available MCP tools.
 */
export type MCPListToolsEvent = {
  type: "mcp_list_tools";
  /**
   * Unique identifier for the event
   */
  id?: string | null | undefined;
  /**
   * Status of the event
   */
  status?: EventStatus | null | undefined;
  /**
   * Provider-specific metadata and additional fields
   */
  metadata?: { [k: string]: any } | null | undefined;
  /**
   * Error message if the event failed
   */
  errorMessage?: string | null | undefined;
  /**
   * Name of the MCP server
   */
  serverName?: string | null | undefined;
  /**
   * List of available MCP tools
   */
  tools?: Array<{ [k: string]: any }> | null | undefined;
};

/** @internal */
export const MCPListToolsEvent$inboundSchema: z.ZodMiniType<
  MCPListToolsEvent,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("mcp_list_tools"),
    id: z.optional(z.nullable(types.string())),
    status: z.optional(z.nullable(EventStatus$inboundSchema)),
    metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
    error_message: z.optional(z.nullable(types.string())),
    server_name: z.optional(z.nullable(types.string())),
    tools: z.optional(z.nullable(z.array(z.record(z.string(), z.any())))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "error_message": "errorMessage",
      "server_name": "serverName",
    });
  }),
);
/** @internal */
export type MCPListToolsEvent$Outbound = {
  type: "mcp_list_tools";
  id?: string | null | undefined;
  status?: string | null | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  error_message?: string | null | undefined;
  server_name?: string | null | undefined;
  tools?: Array<{ [k: string]: any }> | null | undefined;
};

/** @internal */
export const MCPListToolsEvent$outboundSchema: z.ZodMiniType<
  MCPListToolsEvent$Outbound,
  MCPListToolsEvent
> = z.pipe(
  z.object({
    type: z.literal("mcp_list_tools"),
    id: z.optional(z.nullable(z.string())),
    status: z.optional(z.nullable(EventStatus$outboundSchema)),
    metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
    errorMessage: z.optional(z.nullable(z.string())),
    serverName: z.optional(z.nullable(z.string())),
    tools: z.optional(z.nullable(z.array(z.record(z.string(), z.any())))),
  }),
  z.transform((v) => {
    return remap$(v, {
      errorMessage: "error_message",
      serverName: "server_name",
    });
  }),
);

export function mcpListToolsEventToJSON(
  mcpListToolsEvent: MCPListToolsEvent,
): string {
  return JSON.stringify(
    MCPListToolsEvent$outboundSchema.parse(mcpListToolsEvent),
  );
}
export function mcpListToolsEventFromJSON(
  jsonString: string,
): SafeParseResult<MCPListToolsEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MCPListToolsEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MCPListToolsEvent' from JSON`,
  );
}
