/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 31091fa3c077
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const MetadataFilterOperator = {
  OneOf: "one_of",
  NotIn: "not_in",
  Eq: "eq",
  Ne: "ne",
} as const;
export type MetadataFilterOperator = OpenEnum<typeof MetadataFilterOperator>;

export type MetadataFilterValue = string | Array<string>;

/**
 * Filters on metadata key-value pairs in scorer jobs.
 */
export type MetadataFilter = {
  name: "metadata";
  filterType?: "map" | undefined;
  operator: MetadataFilterOperator;
  key: string;
  value: string | Array<string>;
};

/** @internal */
export const MetadataFilterOperator$inboundSchema: z.ZodMiniType<
  MetadataFilterOperator,
  unknown
> = openEnums.inboundSchema(MetadataFilterOperator);
/** @internal */
export const MetadataFilterOperator$outboundSchema: z.ZodMiniType<
  string,
  MetadataFilterOperator
> = openEnums.outboundSchema(MetadataFilterOperator);

/** @internal */
export const MetadataFilterValue$inboundSchema: z.ZodMiniType<
  MetadataFilterValue,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);
/** @internal */
export type MetadataFilterValue$Outbound = string | Array<string>;

/** @internal */
export const MetadataFilterValue$outboundSchema: z.ZodMiniType<
  MetadataFilterValue$Outbound,
  MetadataFilterValue
> = smartUnion([z.string(), z.array(z.string())]);

export function metadataFilterValueToJSON(
  metadataFilterValue: MetadataFilterValue,
): string {
  return JSON.stringify(
    MetadataFilterValue$outboundSchema.parse(metadataFilterValue),
  );
}
export function metadataFilterValueFromJSON(
  jsonString: string,
): SafeParseResult<MetadataFilterValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetadataFilterValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetadataFilterValue' from JSON`,
  );
}

/** @internal */
export const MetadataFilter$inboundSchema: z.ZodMiniType<
  MetadataFilter,
  unknown
> = z.pipe(
  z.object({
    name: types.literal("metadata"),
    filter_type: z._default(types.literal("map"), "map"),
    operator: MetadataFilterOperator$inboundSchema,
    key: types.string(),
    value: smartUnion([types.string(), z.array(types.string())]),
  }),
  z.transform((v) => {
    return remap$(v, {
      "filter_type": "filterType",
    });
  }),
);
/** @internal */
export type MetadataFilter$Outbound = {
  name: "metadata";
  filter_type: "map";
  operator: string;
  key: string;
  value: string | Array<string>;
};

/** @internal */
export const MetadataFilter$outboundSchema: z.ZodMiniType<
  MetadataFilter$Outbound,
  MetadataFilter
> = z.pipe(
  z.object({
    name: z.literal("metadata"),
    filterType: z._default(z.literal("map"), "map" as const),
    operator: MetadataFilterOperator$outboundSchema,
    key: z.string(),
    value: smartUnion([z.string(), z.array(z.string())]),
  }),
  z.transform((v) => {
    return remap$(v, {
      filterType: "filter_type",
    });
  }),
);

export function metadataFilterToJSON(metadataFilter: MetadataFilter): string {
  return JSON.stringify(MetadataFilter$outboundSchema.parse(metadataFilter));
}
export function metadataFilterFromJSON(
  jsonString: string,
): SafeParseResult<MetadataFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetadataFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetadataFilter' from JSON`,
  );
}
