/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 95619cc92530
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const MetricComputationStatus = {
  Success: "success",
  Timeout: "timeout",
  Failed: "failed",
  Error: "error",
} as const;
export type MetricComputationStatus = OpenEnum<typeof MetricComputationStatus>;

/** @internal */
export const MetricComputationStatus$inboundSchema: z.ZodMiniType<
  MetricComputationStatus,
  unknown
> = openEnums.inboundSchema(MetricComputationStatus);
