/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { ScorerType, ScorerType$inboundSchema } from "./scorertype.js";

export type MetricNotComputed = {
  statusType: "not_computed";
  scorerType?: ScorerType | null | undefined;
  message: string;
};

/** @internal */
export const MetricNotComputed$inboundSchema: z.ZodMiniType<
  MetricNotComputed,
  unknown
> = z.pipe(
  z.object({
    status_type: types.literal("not_computed"),
    scorer_type: z.optional(z.nullable(ScorerType$inboundSchema)),
    message: z._default(types.string(), "Metric not computed."),
  }),
  z.transform((v) => {
    return remap$(v, {
      "status_type": "statusType",
      "scorer_type": "scorerType",
    });
  }),
);

export function metricNotComputedFromJSON(
  jsonString: string,
): SafeParseResult<MetricNotComputed, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetricNotComputed$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetricNotComputed' from JSON`,
  );
}
