/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type MistralIntegrationCreate = {
  token: string;
};

/** @internal */
export type MistralIntegrationCreate$Outbound = {
  token: string;
};

/** @internal */
export const MistralIntegrationCreate$outboundSchema: z.ZodMiniType<
  MistralIntegrationCreate$Outbound,
  MistralIntegrationCreate
> = z.object({
  token: z.string(),
});

export function mistralIntegrationCreateToJSON(
  mistralIntegrationCreate: MistralIntegrationCreate,
): string {
  return JSON.stringify(
    MistralIntegrationCreate$outboundSchema.parse(mistralIntegrationCreate),
  );
}
