/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 86a38d00d249
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ModelLifecycleState = {
  Active: "active",
  Deprecated: "deprecated",
  Retired: "retired",
} as const;
export type ModelLifecycleState = OpenEnum<typeof ModelLifecycleState>;

/** @internal */
export const ModelLifecycleState$inboundSchema: z.ZodMiniType<
  ModelLifecycleState,
  unknown
> = openEnums.inboundSchema(ModelLifecycleState);
/** @internal */
export const ModelLifecycleState$outboundSchema: z.ZodMiniType<
  string,
  ModelLifecycleState
> = openEnums.outboundSchema(ModelLifecycleState);
