/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9b70d48515b1
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ModelType = {
  Slm: "slm",
  Llm: "llm",
  Code: "code",
} as const;
export type ModelType = OpenEnum<typeof ModelType>;

/** @internal */
export const ModelType$inboundSchema: z.ZodMiniType<ModelType, unknown> =
  openEnums.inboundSchema(ModelType);
/** @internal */
export const ModelType$outboundSchema: z.ZodMiniType<string, ModelType> =
  openEnums.outboundSchema(ModelType);
