/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ContentModality,
  ContentModality$inboundSchema,
} from "./contentmodality.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ModelProperties = {
  alias: string;
  name: string;
  inputModalities: Array<ContentModality>;
};

/** @internal */
export const ModelProperties$inboundSchema: z.ZodMiniType<
  ModelProperties,
  unknown
> = z.pipe(
  z.object({
    alias: types.string(),
    name: types.string(),
    input_modalities: z.array(ContentModality$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "input_modalities": "inputModalities",
    });
  }),
);

export function modelPropertiesFromJSON(
  jsonString: string,
): SafeParseResult<ModelProperties, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelProperties$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelProperties' from JSON`,
  );
}
