/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d9cb57d9a4c3
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const MultimodalCapability = {
  Vision: "vision",
  Audio: "audio",
} as const;
export type MultimodalCapability = OpenEnum<typeof MultimodalCapability>;

/** @internal */
export const MultimodalCapability$inboundSchema: z.ZodMiniType<
  MultimodalCapability,
  unknown
> = openEnums.inboundSchema(MultimodalCapability);
/** @internal */
export const MultimodalCapability$outboundSchema: z.ZodMiniType<
  string,
  MultimodalCapability
> = openEnums.outboundSchema(MultimodalCapability);
