/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Global name class for handling unique naming across the application.
 */
export type Name = {
  value: string;
  appendSuffixIfDuplicate?: boolean | undefined;
};

/** @internal */
export const Name$inboundSchema: z.ZodMiniType<Name, unknown> = z.pipe(
  z.object({
    value: types.string(),
    append_suffix_if_duplicate: z._default(types.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      "append_suffix_if_duplicate": "appendSuffixIfDuplicate",
    });
  }),
);
/** @internal */
export type Name$Outbound = {
  value: string;
  append_suffix_if_duplicate: boolean;
};

/** @internal */
export const Name$outboundSchema: z.ZodMiniType<Name$Outbound, Name> = z.pipe(
  z.object({
    value: z.string(),
    appendSuffixIfDuplicate: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      appendSuffixIfDuplicate: "append_suffix_if_duplicate",
    });
  }),
);

export function nameToJSON(name: Name): string {
  return JSON.stringify(Name$outboundSchema.parse(name));
}
export function nameFromJSON(
  jsonString: string,
): SafeParseResult<Name, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Name$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Name' from JSON`,
  );
}
