/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 46117011d05e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  MetadataFilter,
  MetadataFilter$inboundSchema,
  MetadataFilter$Outbound,
  MetadataFilter$outboundSchema,
} from "./metadatafilter.js";
import {
  NodeNameFilter,
  NodeNameFilter$inboundSchema,
  NodeNameFilter$Outbound,
  NodeNameFilter$outboundSchema,
} from "./nodenamefilter.js";

export type OutputToneScorerFilter =
  | MetadataFilter
  | NodeNameFilter
  | discriminatedUnionTypes.Unknown<"name">;

export type OutputToneScorer = {
  name: "output_tone";
  /**
   * List of filters to apply to the scorer.
   */
  filters?:
    | Array<
      MetadataFilter | NodeNameFilter | discriminatedUnionTypes.Unknown<"name">
    >
    | null
    | undefined;
};

/** @internal */
export const OutputToneScorerFilter$inboundSchema: z.ZodMiniType<
  OutputToneScorerFilter,
  unknown
> = discriminatedUnion("name", {
  metadata: MetadataFilter$inboundSchema,
  node_name: NodeNameFilter$inboundSchema,
});
/** @internal */
export type OutputToneScorerFilter$Outbound =
  | MetadataFilter$Outbound
  | NodeNameFilter$Outbound;

/** @internal */
export const OutputToneScorerFilter$outboundSchema: z.ZodMiniType<
  OutputToneScorerFilter$Outbound,
  OutputToneScorerFilter
> = z.union([MetadataFilter$outboundSchema, NodeNameFilter$outboundSchema]);

export function outputToneScorerFilterToJSON(
  outputToneScorerFilter: OutputToneScorerFilter,
): string {
  return JSON.stringify(
    OutputToneScorerFilter$outboundSchema.parse(outputToneScorerFilter),
  );
}
export function outputToneScorerFilterFromJSON(
  jsonString: string,
): SafeParseResult<OutputToneScorerFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputToneScorerFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputToneScorerFilter' from JSON`,
  );
}

/** @internal */
export const OutputToneScorer$inboundSchema: z.ZodMiniType<
  OutputToneScorer,
  unknown
> = z.object({
  name: types.literal("output_tone"),
  filters: z.optional(
    z.nullable(
      z.array(
        discriminatedUnion("name", {
          metadata: MetadataFilter$inboundSchema,
          node_name: NodeNameFilter$inboundSchema,
        }),
      ),
    ),
  ),
});
/** @internal */
export type OutputToneScorer$Outbound = {
  name: "output_tone";
  filters?:
    | Array<MetadataFilter$Outbound | NodeNameFilter$Outbound>
    | null
    | undefined;
};

/** @internal */
export const OutputToneScorer$outboundSchema: z.ZodMiniType<
  OutputToneScorer$Outbound,
  OutputToneScorer
> = z.object({
  name: z.literal("output_tone"),
  filters: z.optional(
    z.nullable(
      z.array(
        z.union([MetadataFilter$outboundSchema, NodeNameFilter$outboundSchema]),
      ),
    ),
  ),
});

export function outputToneScorerToJSON(
  outputToneScorer: OutputToneScorer,
): string {
  return JSON.stringify(
    OutputToneScorer$outboundSchema.parse(outputToneScorer),
  );
}
export function outputToneScorerFromJSON(
  jsonString: string,
): SafeParseResult<OutputToneScorer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputToneScorer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputToneScorer' from JSON`,
  );
}
