/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bbbdd3b3017a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  AnnotationAggregate,
  AnnotationAggregate$inboundSchema,
} from "./annotationaggregate.js";
import {
  AnnotationRatingInfo,
  AnnotationRatingInfo$inboundSchema,
} from "./annotationratinginfo.js";
import {
  ContentModality,
  ContentModality$inboundSchema,
} from "./contentmodality.js";
import { ControlResult, ControlResult$inboundSchema } from "./controlresult.js";
import { Document, Document$inboundSchema } from "./document.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  FeedbackRatingInfo,
  FeedbackRatingInfo$inboundSchema,
} from "./feedbackratinginfo.js";
import {
  FileContentPart,
  FileContentPart$inboundSchema,
} from "./filecontentpart.js";
import { FileMetadata, FileMetadata$inboundSchema } from "./filemetadata.js";
import {
  GalileoCoreSchemasLoggingLlmMessage,
  GalileoCoreSchemasLoggingLlmMessage$inboundSchema,
} from "./galileocoreschemasloggingllmmessage.js";
import {
  MetricComputing,
  MetricComputing$inboundSchema,
} from "./metriccomputing.js";
import { MetricError, MetricError$inboundSchema } from "./metricerror.js";
import { MetricFailed, MetricFailed$inboundSchema } from "./metricfailed.js";
import {
  MetricNotApplicable,
  MetricNotApplicable$inboundSchema,
} from "./metricnotapplicable.js";
import {
  MetricNotComputed,
  MetricNotComputed$inboundSchema,
} from "./metricnotcomputed.js";
import { MetricPending, MetricPending$inboundSchema } from "./metricpending.js";
import { MetricRollUp, MetricRollUp$inboundSchema } from "./metricrollup.js";
import { Metrics, Metrics$inboundSchema } from "./metrics.js";
import { MetricSuccess, MetricSuccess$inboundSchema } from "./metricsuccess.js";
import {
  TextContentPart,
  TextContentPart$inboundSchema,
} from "./textcontentpart.js";

export type PartialExtendedHttpSpanRecordInput1 =
  | FileContentPart
  | TextContentPart
  | discriminatedUnionTypes.Unknown<"type">;

/**
 * Input to the trace or span.
 */
export type PartialExtendedHttpSpanRecordInput2 =
  | string
  | Array<GalileoCoreSchemasLoggingLlmMessage>
  | Array<
    FileContentPart | TextContentPart | discriminatedUnionTypes.Unknown<"type">
  >;

export type PartialExtendedHttpSpanRecordRedactedInput1 =
  | FileContentPart
  | TextContentPart
  | discriminatedUnionTypes.Unknown<"type">;

/**
 * Redacted input of the trace or span.
 */
export type PartialExtendedHttpSpanRecordRedactedInput2 =
  | string
  | Array<GalileoCoreSchemasLoggingLlmMessage>
  | Array<
    FileContentPart | TextContentPart | discriminatedUnionTypes.Unknown<"type">
  >;

export type PartialExtendedHttpSpanRecordOutput1 =
  | FileContentPart
  | TextContentPart
  | discriminatedUnionTypes.Unknown<"type">;

/**
 * Output of the trace or span.
 */
export type PartialExtendedHttpSpanRecordOutput2 =
  | GalileoCoreSchemasLoggingLlmMessage
  | ControlResult
  | string
  | Array<Document>
  | Array<
    FileContentPart | TextContentPart | discriminatedUnionTypes.Unknown<"type">
  >;

export type PartialExtendedHttpSpanRecordRedactedOutput1 =
  | FileContentPart
  | TextContentPart
  | discriminatedUnionTypes.Unknown<"type">;

/**
 * Redacted output of the trace or span.
 */
export type PartialExtendedHttpSpanRecordRedactedOutput2 =
  | GalileoCoreSchemasLoggingLlmMessage
  | ControlResult
  | string
  | Array<Document>
  | Array<
    FileContentPart | TextContentPart | discriminatedUnionTypes.Unknown<"type">
  >;

export type PartialExtendedHttpSpanRecordMetricInfo =
  | MetricComputing
  | MetricError
  | MetricFailed
  | MetricNotApplicable
  | MetricNotComputed
  | MetricPending
  | MetricRollUp
  | MetricSuccess
  | discriminatedUnionTypes.Unknown<"statusType">;

export type PartialExtendedHttpSpanRecord = {
  /**
   * Type of the trace, span or session.
   */
  type: "http";
  /**
   * Input to the trace or span.
   */
  input?:
    | string
    | Array<GalileoCoreSchemasLoggingLlmMessage>
    | Array<
      | FileContentPart
      | TextContentPart
      | discriminatedUnionTypes.Unknown<"type">
    >
    | undefined;
  /**
   * Redacted input of the trace or span.
   */
  redactedInput?:
    | string
    | Array<GalileoCoreSchemasLoggingLlmMessage>
    | Array<
      | FileContentPart
      | TextContentPart
      | discriminatedUnionTypes.Unknown<"type">
    >
    | null
    | undefined;
  /**
   * Output of the trace or span.
   */
  output?:
    | GalileoCoreSchemasLoggingLlmMessage
    | ControlResult
    | string
    | Array<Document>
    | Array<
      | FileContentPart
      | TextContentPart
      | discriminatedUnionTypes.Unknown<"type">
    >
    | null
    | undefined;
  /**
   * Redacted output of the trace or span.
   */
  redactedOutput?:
    | GalileoCoreSchemasLoggingLlmMessage
    | ControlResult
    | string
    | Array<Document>
    | Array<
      | FileContentPart
      | TextContentPart
      | discriminatedUnionTypes.Unknown<"type">
    >
    | null
    | undefined;
  /**
   * Name of the trace, span or session.
   */
  name: string;
  /**
   * Timestamp of the trace or span's creation.
   */
  createdAt?: Date | undefined;
  /**
   * Metadata associated with this trace or span.
   */
  userMetadata?: { [k: string]: string } | undefined;
  /**
   * Tags associated with this trace or span.
   */
  tags?: Array<string> | undefined;
  /**
   * Status code of the trace or span. Used for logging failure or error states.
   */
  statusCode?: number | null | undefined;
  metrics?: Metrics | undefined;
  /**
   * A user-provided session, trace or span ID.
   */
  externalId?: string | null | undefined;
  /**
   * Input to the dataset associated with this trace
   */
  datasetInput?: string | null | undefined;
  /**
   * Output from the dataset associated with this trace
   */
  datasetOutput?: string | null | undefined;
  /**
   * Metadata from the dataset associated with this trace
   */
  datasetMetadata?: { [k: string]: string } | undefined;
  /**
   * Galileo ID of the session, trace or span
   */
  id?: string | null | undefined;
  /**
   * Galileo ID of the session containing the trace (or the same value as id for a trace)
   */
  sessionId?: string | null | undefined;
  /**
   * Galileo ID of the trace containing the span (or the same value as id for a trace)
   */
  traceId?: string | null | undefined;
  /**
   * Galileo ID of the project associated with this trace or span
   */
  projectId?: string | null | undefined;
  /**
   * Galileo ID of the run (log stream or experiment) associated with this trace or span
   */
  runId?: string | null | undefined;
  /**
   * Timestamp of the session or trace or span's last update
   */
  updatedAt?: Date | null | undefined;
  /**
   * Whether or not this trace or span has child spans
   */
  hasChildren?: boolean | null | undefined;
  /**
   * Galileo ID of the metrics batch associated with this trace or span
   */
  metricsBatchId?: string | null | undefined;
  /**
   * Galileo ID of the metrics batch associated with this trace or span
   */
  sessionBatchId?: string | null | undefined;
  /**
   * Feedback information related to the record
   */
  feedbackRatingInfo?: { [k: string]: FeedbackRatingInfo } | undefined;
  /**
   * Annotations keyed by template ID and annotator ID
   */
  annotations?:
    | { [k: string]: { [k: string]: AnnotationRatingInfo } }
    | undefined;
  /**
   * IDs of files associated with this record
   */
  fileIds?: Array<string> | undefined;
  /**
   * Modalities of files associated with this record
   */
  fileModalities?: Array<ContentModality> | undefined;
  /**
   * Annotation aggregate information keyed by template ID
   */
  annotationAggregates?: { [k: string]: AnnotationAggregate } | undefined;
  /**
   * Annotation agreement scores keyed by template ID
   */
  annotationAgreement?: { [k: string]: number } | undefined;
  /**
   * Average annotation agreement across all templates in the queue
   */
  overallAnnotationAgreement?: number | null | undefined;
  /**
   * IDs of annotation queues this record is in
   */
  annotationQueueIds?: Array<string> | undefined;
  /**
   * Whether every field is annotated by every annotator in the queue
   */
  fullyAnnotated?: boolean | null | undefined;
  /**
   * Runner progress text written directly to CH span
   */
  progressMessage: string;
  /**
   * Runner error text written directly to CH span
   */
  errorMessage: string;
  /**
   * Detailed information about the metrics associated with this trace or span
   */
  metricInfo?:
    | {
      [k: string]:
        | MetricComputing
        | MetricError
        | MetricFailed
        | MetricNotApplicable
        | MetricNotComputed
        | MetricPending
        | MetricRollUp
        | MetricSuccess
        | discriminatedUnionTypes.Unknown<"statusType">;
    }
    | null
    | undefined;
  /**
   * File metadata keyed by file ID for files associated with this record
   */
  files?: { [k: string]: FileMetadata } | null | undefined;
  /**
   * Galileo ID of the parent of this span
   */
  parentId?: string | null | undefined;
  /**
   * Whether the parent trace is complete or not
   */
  isComplete: boolean;
  /**
   * Topological step number of the span.
   */
  stepNumber?: number | null | undefined;
};

/** @internal */
export const PartialExtendedHttpSpanRecordInput1$inboundSchema: z.ZodMiniType<
  PartialExtendedHttpSpanRecordInput1,
  unknown
> = discriminatedUnion("type", {
  file: FileContentPart$inboundSchema,
  text: TextContentPart$inboundSchema,
});

export function partialExtendedHttpSpanRecordInput1FromJSON(
  jsonString: string,
): SafeParseResult<PartialExtendedHttpSpanRecordInput1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PartialExtendedHttpSpanRecordInput1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PartialExtendedHttpSpanRecordInput1' from JSON`,
  );
}

/** @internal */
export const PartialExtendedHttpSpanRecordInput2$inboundSchema: z.ZodMiniType<
  PartialExtendedHttpSpanRecordInput2,
  unknown
> = smartUnion([
  types.string(),
  z.array(GalileoCoreSchemasLoggingLlmMessage$inboundSchema),
  z.array(
    discriminatedUnion("type", {
      file: FileContentPart$inboundSchema,
      text: TextContentPart$inboundSchema,
    }),
  ),
]);

export function partialExtendedHttpSpanRecordInput2FromJSON(
  jsonString: string,
): SafeParseResult<PartialExtendedHttpSpanRecordInput2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PartialExtendedHttpSpanRecordInput2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PartialExtendedHttpSpanRecordInput2' from JSON`,
  );
}

/** @internal */
export const PartialExtendedHttpSpanRecordRedactedInput1$inboundSchema:
  z.ZodMiniType<PartialExtendedHttpSpanRecordRedactedInput1, unknown> =
    discriminatedUnion("type", {
      file: FileContentPart$inboundSchema,
      text: TextContentPart$inboundSchema,
    });

export function partialExtendedHttpSpanRecordRedactedInput1FromJSON(
  jsonString: string,
): SafeParseResult<
  PartialExtendedHttpSpanRecordRedactedInput1,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PartialExtendedHttpSpanRecordRedactedInput1$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PartialExtendedHttpSpanRecordRedactedInput1' from JSON`,
  );
}

/** @internal */
export const PartialExtendedHttpSpanRecordRedactedInput2$inboundSchema:
  z.ZodMiniType<PartialExtendedHttpSpanRecordRedactedInput2, unknown> =
    smartUnion([
      types.string(),
      z.array(GalileoCoreSchemasLoggingLlmMessage$inboundSchema),
      z.array(
        discriminatedUnion("type", {
          file: FileContentPart$inboundSchema,
          text: TextContentPart$inboundSchema,
        }),
      ),
    ]);

export function partialExtendedHttpSpanRecordRedactedInput2FromJSON(
  jsonString: string,
): SafeParseResult<
  PartialExtendedHttpSpanRecordRedactedInput2,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PartialExtendedHttpSpanRecordRedactedInput2$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PartialExtendedHttpSpanRecordRedactedInput2' from JSON`,
  );
}

/** @internal */
export const PartialExtendedHttpSpanRecordOutput1$inboundSchema: z.ZodMiniType<
  PartialExtendedHttpSpanRecordOutput1,
  unknown
> = discriminatedUnion("type", {
  file: FileContentPart$inboundSchema,
  text: TextContentPart$inboundSchema,
});

export function partialExtendedHttpSpanRecordOutput1FromJSON(
  jsonString: string,
): SafeParseResult<PartialExtendedHttpSpanRecordOutput1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PartialExtendedHttpSpanRecordOutput1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PartialExtendedHttpSpanRecordOutput1' from JSON`,
  );
}

/** @internal */
export const PartialExtendedHttpSpanRecordOutput2$inboundSchema: z.ZodMiniType<
  PartialExtendedHttpSpanRecordOutput2,
  unknown
> = smartUnion([
  GalileoCoreSchemasLoggingLlmMessage$inboundSchema,
  ControlResult$inboundSchema,
  types.string(),
  z.array(Document$inboundSchema),
  z.array(
    discriminatedUnion("type", {
      file: FileContentPart$inboundSchema,
      text: TextContentPart$inboundSchema,
    }),
  ),
]);

export function partialExtendedHttpSpanRecordOutput2FromJSON(
  jsonString: string,
): SafeParseResult<PartialExtendedHttpSpanRecordOutput2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PartialExtendedHttpSpanRecordOutput2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PartialExtendedHttpSpanRecordOutput2' from JSON`,
  );
}

/** @internal */
export const PartialExtendedHttpSpanRecordRedactedOutput1$inboundSchema:
  z.ZodMiniType<PartialExtendedHttpSpanRecordRedactedOutput1, unknown> =
    discriminatedUnion("type", {
      file: FileContentPart$inboundSchema,
      text: TextContentPart$inboundSchema,
    });

export function partialExtendedHttpSpanRecordRedactedOutput1FromJSON(
  jsonString: string,
): SafeParseResult<
  PartialExtendedHttpSpanRecordRedactedOutput1,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PartialExtendedHttpSpanRecordRedactedOutput1$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PartialExtendedHttpSpanRecordRedactedOutput1' from JSON`,
  );
}

/** @internal */
export const PartialExtendedHttpSpanRecordRedactedOutput2$inboundSchema:
  z.ZodMiniType<PartialExtendedHttpSpanRecordRedactedOutput2, unknown> =
    smartUnion([
      GalileoCoreSchemasLoggingLlmMessage$inboundSchema,
      ControlResult$inboundSchema,
      types.string(),
      z.array(Document$inboundSchema),
      z.array(
        discriminatedUnion("type", {
          file: FileContentPart$inboundSchema,
          text: TextContentPart$inboundSchema,
        }),
      ),
    ]);

export function partialExtendedHttpSpanRecordRedactedOutput2FromJSON(
  jsonString: string,
): SafeParseResult<
  PartialExtendedHttpSpanRecordRedactedOutput2,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PartialExtendedHttpSpanRecordRedactedOutput2$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PartialExtendedHttpSpanRecordRedactedOutput2' from JSON`,
  );
}

/** @internal */
export const PartialExtendedHttpSpanRecordMetricInfo$inboundSchema:
  z.ZodMiniType<PartialExtendedHttpSpanRecordMetricInfo, unknown> =
    discriminatedUnion("status_type", {
      computing: MetricComputing$inboundSchema,
      error: MetricError$inboundSchema,
      failed: MetricFailed$inboundSchema,
      not_applicable: MetricNotApplicable$inboundSchema,
      not_computed: MetricNotComputed$inboundSchema,
      pending: MetricPending$inboundSchema,
      roll_up: MetricRollUp$inboundSchema,
      success: MetricSuccess$inboundSchema,
    }, { outputPropertyName: "statusType" });

export function partialExtendedHttpSpanRecordMetricInfoFromJSON(
  jsonString: string,
): SafeParseResult<
  PartialExtendedHttpSpanRecordMetricInfo,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PartialExtendedHttpSpanRecordMetricInfo$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PartialExtendedHttpSpanRecordMetricInfo' from JSON`,
  );
}

/** @internal */
export const PartialExtendedHttpSpanRecord$inboundSchema: z.ZodMiniType<
  PartialExtendedHttpSpanRecord,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("http"),
    input: types.optional(
      smartUnion([
        types.string(),
        z.array(GalileoCoreSchemasLoggingLlmMessage$inboundSchema),
        z.array(
          discriminatedUnion("type", {
            file: FileContentPart$inboundSchema,
            text: TextContentPart$inboundSchema,
          }),
        ),
      ]),
    ),
    redacted_input: z.optional(
      z.nullable(
        smartUnion([
          types.string(),
          z.array(GalileoCoreSchemasLoggingLlmMessage$inboundSchema),
          z.array(
            discriminatedUnion("type", {
              file: FileContentPart$inboundSchema,
              text: TextContentPart$inboundSchema,
            }),
          ),
        ]),
      ),
    ),
    output: z.optional(
      z.nullable(
        smartUnion([
          GalileoCoreSchemasLoggingLlmMessage$inboundSchema,
          ControlResult$inboundSchema,
          types.string(),
          z.array(Document$inboundSchema),
          z.array(
            discriminatedUnion("type", {
              file: FileContentPart$inboundSchema,
              text: TextContentPart$inboundSchema,
            }),
          ),
        ]),
      ),
    ),
    redacted_output: z.optional(
      z.nullable(
        smartUnion([
          GalileoCoreSchemasLoggingLlmMessage$inboundSchema,
          ControlResult$inboundSchema,
          types.string(),
          z.array(Document$inboundSchema),
          z.array(
            discriminatedUnion("type", {
              file: FileContentPart$inboundSchema,
              text: TextContentPart$inboundSchema,
            }),
          ),
        ]),
      ),
    ),
    name: z._default(types.string(), ""),
    created_at: types.optional(types.date()),
    user_metadata: types.optional(z.record(z.string(), types.string())),
    tags: types.optional(z.array(types.string())),
    status_code: z.optional(z.nullable(types.number())),
    metrics: types.optional(Metrics$inboundSchema),
    external_id: z.optional(z.nullable(types.string())),
    dataset_input: z.optional(z.nullable(types.string())),
    dataset_output: z.optional(z.nullable(types.string())),
    dataset_metadata: types.optional(z.record(z.string(), types.string())),
    id: z.optional(z.nullable(types.string())),
    session_id: z.optional(z.nullable(types.string())),
    trace_id: z.optional(z.nullable(types.string())),
    project_id: z.optional(z.nullable(types.string())),
    run_id: z.optional(z.nullable(types.string())),
    updated_at: z.optional(z.nullable(types.date())),
    has_children: z.optional(z.nullable(types.boolean())),
    metrics_batch_id: z.optional(z.nullable(types.string())),
    session_batch_id: z.optional(z.nullable(types.string())),
    feedback_rating_info: types.optional(
      z.record(z.string(), FeedbackRatingInfo$inboundSchema),
    ),
    annotations: types.optional(
      z.record(
        z.string(),
        z.record(z.string(), AnnotationRatingInfo$inboundSchema),
      ),
    ),
    file_ids: types.optional(z.array(types.string())),
    file_modalities: types.optional(z.array(ContentModality$inboundSchema)),
    annotation_aggregates: types.optional(
      z.record(z.string(), AnnotationAggregate$inboundSchema),
    ),
    annotation_agreement: types.optional(z.record(z.string(), types.number())),
    overall_annotation_agreement: z.optional(z.nullable(types.number())),
    annotation_queue_ids: types.optional(z.array(types.string())),
    fully_annotated: z.optional(z.nullable(types.boolean())),
    progress_message: z._default(types.string(), ""),
    error_message: z._default(types.string(), ""),
    metric_info: z.optional(
      z.nullable(z.record(
        z.string(),
        discriminatedUnion("status_type", {
          computing: MetricComputing$inboundSchema,
          error: MetricError$inboundSchema,
          failed: MetricFailed$inboundSchema,
          not_applicable: MetricNotApplicable$inboundSchema,
          not_computed: MetricNotComputed$inboundSchema,
          pending: MetricPending$inboundSchema,
          roll_up: MetricRollUp$inboundSchema,
          success: MetricSuccess$inboundSchema,
        }, { outputPropertyName: "statusType" }),
      )),
    ),
    files: z.optional(
      z.nullable(z.record(z.string(), FileMetadata$inboundSchema)),
    ),
    parent_id: z.optional(z.nullable(types.string())),
    is_complete: z._default(types.boolean(), true),
    step_number: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "redacted_input": "redactedInput",
      "redacted_output": "redactedOutput",
      "created_at": "createdAt",
      "user_metadata": "userMetadata",
      "status_code": "statusCode",
      "external_id": "externalId",
      "dataset_input": "datasetInput",
      "dataset_output": "datasetOutput",
      "dataset_metadata": "datasetMetadata",
      "session_id": "sessionId",
      "trace_id": "traceId",
      "project_id": "projectId",
      "run_id": "runId",
      "updated_at": "updatedAt",
      "has_children": "hasChildren",
      "metrics_batch_id": "metricsBatchId",
      "session_batch_id": "sessionBatchId",
      "feedback_rating_info": "feedbackRatingInfo",
      "file_ids": "fileIds",
      "file_modalities": "fileModalities",
      "annotation_aggregates": "annotationAggregates",
      "annotation_agreement": "annotationAgreement",
      "overall_annotation_agreement": "overallAnnotationAgreement",
      "annotation_queue_ids": "annotationQueueIds",
      "fully_annotated": "fullyAnnotated",
      "progress_message": "progressMessage",
      "error_message": "errorMessage",
      "metric_info": "metricInfo",
      "parent_id": "parentId",
      "is_complete": "isComplete",
      "step_number": "stepNumber",
    });
  }),
);

export function partialExtendedHttpSpanRecordFromJSON(
  jsonString: string,
): SafeParseResult<PartialExtendedHttpSpanRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PartialExtendedHttpSpanRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PartialExtendedHttpSpanRecord' from JSON`,
  );
}
