/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  ProjectBookmarkFilter,
  ProjectBookmarkFilter$Outbound,
  ProjectBookmarkFilter$outboundSchema,
} from "./projectbookmarkfilter.js";
import {
  ProjectBookmarkSort,
  ProjectBookmarkSort$Outbound,
  ProjectBookmarkSort$outboundSchema,
} from "./projectbookmarksort.js";
import {
  ProjectCreatedAtFilter,
  ProjectCreatedAtFilter$Outbound,
  ProjectCreatedAtFilter$outboundSchema,
} from "./projectcreatedatfilter.js";
import {
  ProjectCreatedAtSort,
  ProjectCreatedAtSort$Outbound,
  ProjectCreatedAtSort$outboundSchema,
} from "./projectcreatedatsort.js";
import {
  ProjectCreatorFilter,
  ProjectCreatorFilter$Outbound,
  ProjectCreatorFilter$outboundSchema,
} from "./projectcreatorfilter.js";
import {
  ProjectIDFilter,
  ProjectIDFilter$Outbound,
  ProjectIDFilter$outboundSchema,
} from "./projectidfilter.js";
import {
  ProjectNameFilter,
  ProjectNameFilter$Outbound,
  ProjectNameFilter$outboundSchema,
} from "./projectnamefilter.js";
import {
  ProjectNameSort,
  ProjectNameSort$Outbound,
  ProjectNameSort$outboundSchema,
} from "./projectnamesort.js";
import {
  ProjectRunsFilter,
  ProjectRunsFilter$Outbound,
  ProjectRunsFilter$outboundSchema,
} from "./projectrunsfilter.js";
import {
  ProjectRunsSort,
  ProjectRunsSort$Outbound,
  ProjectRunsSort$outboundSchema,
} from "./projectrunssort.js";
import {
  ProjectTypeFilter,
  ProjectTypeFilter$Outbound,
  ProjectTypeFilter$outboundSchema,
} from "./projecttypefilter.js";
import {
  ProjectTypeSort,
  ProjectTypeSort$Outbound,
  ProjectTypeSort$outboundSchema,
} from "./projecttypesort.js";
import {
  ProjectUpdatedAtFilter,
  ProjectUpdatedAtFilter$Outbound,
  ProjectUpdatedAtFilter$outboundSchema,
} from "./projectupdatedatfilter.js";
import {
  ProjectUpdatedAtSort,
  ProjectUpdatedAtSort$Outbound,
  ProjectUpdatedAtSort$outboundSchema,
} from "./projectupdatedatsort.js";

export type ProjectCollectionParamsFilter =
  | ProjectBookmarkFilter
  | ProjectCreatedAtFilter
  | ProjectCreatorFilter
  | ProjectIDFilter
  | ProjectNameFilter
  | ProjectRunsFilter
  | ProjectTypeFilter
  | ProjectUpdatedAtFilter;

export type ProjectCollectionParamsSort =
  | ProjectBookmarkSort
  | ProjectCreatedAtSort
  | ProjectNameSort
  | ProjectRunsSort
  | ProjectTypeSort
  | ProjectUpdatedAtSort;

export type ProjectCollectionParams = {
  filters?:
    | Array<
      | ProjectBookmarkFilter
      | ProjectCreatedAtFilter
      | ProjectCreatorFilter
      | ProjectIDFilter
      | ProjectNameFilter
      | ProjectRunsFilter
      | ProjectTypeFilter
      | ProjectUpdatedAtFilter
    >
    | undefined;
  sort?:
    | ProjectBookmarkSort
    | ProjectCreatedAtSort
    | ProjectNameSort
    | ProjectRunsSort
    | ProjectTypeSort
    | ProjectUpdatedAtSort
    | null
    | undefined;
};

/** @internal */
export type ProjectCollectionParamsFilter$Outbound =
  | ProjectBookmarkFilter$Outbound
  | ProjectCreatedAtFilter$Outbound
  | ProjectCreatorFilter$Outbound
  | ProjectIDFilter$Outbound
  | ProjectNameFilter$Outbound
  | ProjectRunsFilter$Outbound
  | ProjectTypeFilter$Outbound
  | ProjectUpdatedAtFilter$Outbound;

/** @internal */
export const ProjectCollectionParamsFilter$outboundSchema: z.ZodMiniType<
  ProjectCollectionParamsFilter$Outbound,
  ProjectCollectionParamsFilter
> = z.union([
  ProjectBookmarkFilter$outboundSchema,
  ProjectCreatedAtFilter$outboundSchema,
  ProjectCreatorFilter$outboundSchema,
  ProjectIDFilter$outboundSchema,
  ProjectNameFilter$outboundSchema,
  ProjectRunsFilter$outboundSchema,
  ProjectTypeFilter$outboundSchema,
  ProjectUpdatedAtFilter$outboundSchema,
]);

export function projectCollectionParamsFilterToJSON(
  projectCollectionParamsFilter: ProjectCollectionParamsFilter,
): string {
  return JSON.stringify(
    ProjectCollectionParamsFilter$outboundSchema.parse(
      projectCollectionParamsFilter,
    ),
  );
}

/** @internal */
export type ProjectCollectionParamsSort$Outbound =
  | ProjectBookmarkSort$Outbound
  | ProjectCreatedAtSort$Outbound
  | ProjectNameSort$Outbound
  | ProjectRunsSort$Outbound
  | ProjectTypeSort$Outbound
  | ProjectUpdatedAtSort$Outbound;

/** @internal */
export const ProjectCollectionParamsSort$outboundSchema: z.ZodMiniType<
  ProjectCollectionParamsSort$Outbound,
  ProjectCollectionParamsSort
> = z.union([
  ProjectBookmarkSort$outboundSchema,
  ProjectCreatedAtSort$outboundSchema,
  ProjectNameSort$outboundSchema,
  ProjectRunsSort$outboundSchema,
  ProjectTypeSort$outboundSchema,
  ProjectUpdatedAtSort$outboundSchema,
]);

export function projectCollectionParamsSortToJSON(
  projectCollectionParamsSort: ProjectCollectionParamsSort,
): string {
  return JSON.stringify(
    ProjectCollectionParamsSort$outboundSchema.parse(
      projectCollectionParamsSort,
    ),
  );
}

/** @internal */
export type ProjectCollectionParams$Outbound = {
  filters?:
    | Array<
      | ProjectBookmarkFilter$Outbound
      | ProjectCreatedAtFilter$Outbound
      | ProjectCreatorFilter$Outbound
      | ProjectIDFilter$Outbound
      | ProjectNameFilter$Outbound
      | ProjectRunsFilter$Outbound
      | ProjectTypeFilter$Outbound
      | ProjectUpdatedAtFilter$Outbound
    >
    | undefined;
  sort?:
    | ProjectBookmarkSort$Outbound
    | ProjectCreatedAtSort$Outbound
    | ProjectNameSort$Outbound
    | ProjectRunsSort$Outbound
    | ProjectTypeSort$Outbound
    | ProjectUpdatedAtSort$Outbound
    | null
    | undefined;
};

/** @internal */
export const ProjectCollectionParams$outboundSchema: z.ZodMiniType<
  ProjectCollectionParams$Outbound,
  ProjectCollectionParams
> = z.object({
  filters: z.optional(
    z.array(
      z.union([
        ProjectBookmarkFilter$outboundSchema,
        ProjectCreatedAtFilter$outboundSchema,
        ProjectCreatorFilter$outboundSchema,
        ProjectIDFilter$outboundSchema,
        ProjectNameFilter$outboundSchema,
        ProjectRunsFilter$outboundSchema,
        ProjectTypeFilter$outboundSchema,
        ProjectUpdatedAtFilter$outboundSchema,
      ]),
    ),
  ),
  sort: z.optional(
    z.nullable(
      z.union([
        ProjectBookmarkSort$outboundSchema,
        ProjectCreatedAtSort$outboundSchema,
        ProjectNameSort$outboundSchema,
        ProjectRunsSort$outboundSchema,
        ProjectTypeSort$outboundSchema,
        ProjectUpdatedAtSort$outboundSchema,
      ]),
    ),
  ),
});

export function projectCollectionParamsToJSON(
  projectCollectionParams: ProjectCollectionParams,
): string {
  return JSON.stringify(
    ProjectCollectionParams$outboundSchema.parse(projectCollectionParams),
  );
}
