/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4edfc169d521
 */

import * as z from "zod/v4-mini";

export type PromptTemplateNotInProjectFilter = {
  name: "not_in_project";
  value: string;
};

/** @internal */
export type PromptTemplateNotInProjectFilter$Outbound = {
  name: "not_in_project";
  value: string;
};

/** @internal */
export const PromptTemplateNotInProjectFilter$outboundSchema: z.ZodMiniType<
  PromptTemplateNotInProjectFilter$Outbound,
  PromptTemplateNotInProjectFilter
> = z.object({
  name: z.literal("not_in_project"),
  value: z.string(),
});

export function promptTemplateNotInProjectFilterToJSON(
  promptTemplateNotInProjectFilter: PromptTemplateNotInProjectFilter,
): string {
  return JSON.stringify(
    PromptTemplateNotInProjectFilter$outboundSchema.parse(
      promptTemplateNotInProjectFilter,
    ),
  );
}
