/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 28b9b6b344ff
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type PromptTemplateNameSort = {
  name: "name";
  ascending?: boolean | undefined;
  sortType?: "column" | undefined;
};

/** @internal */
export type PromptTemplateNameSort$Outbound = {
  name: "name";
  ascending: boolean;
  sort_type: "column";
};

/** @internal */
export const PromptTemplateNameSort$outboundSchema: z.ZodMiniType<
  PromptTemplateNameSort$Outbound,
  PromptTemplateNameSort
> = z.pipe(
  z.object({
    name: z.literal("name"),
    ascending: z._default(z.boolean(), true),
    sortType: z._default(z.literal("column"), "column" as const),
  }),
  z.transform((v) => {
    return remap$(v, {
      sortType: "sort_type",
    });
  }),
);

export function promptTemplateNameSortToJSON(
  promptTemplateNameSort: PromptTemplateNameSort,
): string {
  return JSON.stringify(
    PromptTemplateNameSort$outboundSchema.parse(promptTemplateNameSort),
  );
}
