/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0174bd4dcce9
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  Payload,
  Payload$Outbound,
  Payload$outboundSchema,
} from "./payload.js";
import {
  Ruleset,
  Ruleset$Outbound,
  Ruleset$outboundSchema,
} from "./ruleset.js";

/**
 * Protect request schema with custom OpenAPI title.
 */
export type ProtectRequest = {
  /**
   * Rulesets to be applied to the payload.
   */
  prioritizedRulesets?: Array<Ruleset> | undefined;
  payload: Payload;
  /**
   * Project name.
   */
  projectName?: string | null | undefined;
  /**
   * Project ID.
   */
  projectId?: string | null | undefined;
  /**
   * Stage name.
   */
  stageName?: string | null | undefined;
  /**
   * Stage ID.
   */
  stageId?: string | null | undefined;
  /**
   * Stage version to use for the request, if it's a central stage with a previously registered version.
   */
  stageVersion?: number | null | undefined;
  /**
   * Optional timeout for the guardrail execution in seconds. This is not the timeout for the request. If not set, a default timeout of 5 minutes will be used.
   */
  timeout?: number | undefined;
  /**
   * Optional additional metadata. This will be echoed back in the response.
   */
  metadata?: { [k: string]: string } | null | undefined;
  /**
   * Optional additional HTTP headers that should be included in the response.
   */
  headers?: { [k: string]: string } | null | undefined;
};

/** @internal */
export type ProtectRequest$Outbound = {
  prioritized_rulesets?: Array<Ruleset$Outbound> | undefined;
  payload: Payload$Outbound;
  project_name?: string | null | undefined;
  project_id?: string | null | undefined;
  stage_name?: string | null | undefined;
  stage_id?: string | null | undefined;
  stage_version?: number | null | undefined;
  timeout: number;
  metadata?: { [k: string]: string } | null | undefined;
  headers?: { [k: string]: string } | null | undefined;
};

/** @internal */
export const ProtectRequest$outboundSchema: z.ZodMiniType<
  ProtectRequest$Outbound,
  ProtectRequest
> = z.pipe(
  z.object({
    prioritizedRulesets: z.optional(z.array(Ruleset$outboundSchema)),
    payload: Payload$outboundSchema,
    projectName: z.optional(z.nullable(z.string())),
    projectId: z.optional(z.nullable(z.string())),
    stageName: z.optional(z.nullable(z.string())),
    stageId: z.optional(z.nullable(z.string())),
    stageVersion: z.optional(z.nullable(z.int())),
    timeout: z._default(z.number(), 300),
    metadata: z.optional(z.nullable(z.record(z.string(), z.string()))),
    headers: z.optional(z.nullable(z.record(z.string(), z.string()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      prioritizedRulesets: "prioritized_rulesets",
      projectName: "project_name",
      projectId: "project_id",
      stageName: "stage_name",
      stageId: "stage_id",
      stageVersion: "stage_version",
    });
  }),
);

export function protectRequestToJSON(protectRequest: ProtectRequest): string {
  return JSON.stringify(ProtectRequest$outboundSchema.parse(protectRequest));
}
