/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TaskResultStatus,
  TaskResultStatus$inboundSchema,
} from "./taskresultstatus.js";
import {
  ValidateRegisteredScorerResult,
  ValidateRegisteredScorerResult$inboundSchema,
} from "./validateregisteredscorerresult.js";

export type RegisteredScorerTaskResultResponseResult =
  | ValidateRegisteredScorerResult
  | string;

export type RegisteredScorerTaskResultResponse = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  status: TaskResultStatus;
  result?: ValidateRegisteredScorerResult | string | null | undefined;
};

/** @internal */
export const RegisteredScorerTaskResultResponseResult$inboundSchema:
  z.ZodMiniType<RegisteredScorerTaskResultResponseResult, unknown> = smartUnion(
    [ValidateRegisteredScorerResult$inboundSchema, types.string()],
  );

export function registeredScorerTaskResultResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<
  RegisteredScorerTaskResultResponseResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RegisteredScorerTaskResultResponseResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'RegisteredScorerTaskResultResponseResult' from JSON`,
  );
}

/** @internal */
export const RegisteredScorerTaskResultResponse$inboundSchema: z.ZodMiniType<
  RegisteredScorerTaskResultResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    created_at: types.date(),
    updated_at: types.date(),
    status: TaskResultStatus$inboundSchema,
    result: z.optional(
      z.nullable(
        smartUnion([
          ValidateRegisteredScorerResult$inboundSchema,
          types.string(),
        ]),
      ),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function registeredScorerTaskResultResponseFromJSON(
  jsonString: string,
): SafeParseResult<RegisteredScorerTaskResultResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RegisteredScorerTaskResultResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RegisteredScorerTaskResultResponse' from JSON`,
  );
}
