/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2a097d8fac09
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  BaseMetricRollUpConfigDB,
  BaseMetricRollUpConfigDB$inboundSchema,
  BaseMetricRollUpConfigDB$Outbound,
  BaseMetricRollUpConfigDB$outboundSchema,
} from "./basemetricrollupconfigdb.js";
import {
  BaseScorerVersionDB,
  BaseScorerVersionDB$inboundSchema,
  BaseScorerVersionDB$Outbound,
  BaseScorerVersionDB$outboundSchema,
} from "./basescorerversiondb.js";
import {
  ChainPollTemplate,
  ChainPollTemplate$inboundSchema,
  ChainPollTemplate$Outbound,
  ChainPollTemplate$outboundSchema,
} from "./chainpolltemplate.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  InputTypeEnum,
  InputTypeEnum$inboundSchema,
  InputTypeEnum$outboundSchema,
} from "./inputtypeenum.js";
import {
  LunaInputTypeEnum,
  LunaInputTypeEnum$inboundSchema,
  LunaInputTypeEnum$outboundSchema,
} from "./lunainputtypeenum.js";
import {
  LunaOutputTypeEnum,
  LunaOutputTypeEnum$inboundSchema,
  LunaOutputTypeEnum$outboundSchema,
} from "./lunaoutputtypeenum.js";
import {
  MetadataFilter,
  MetadataFilter$inboundSchema,
  MetadataFilter$Outbound,
  MetadataFilter$outboundSchema,
} from "./metadatafilter.js";
import {
  ModalityFilter,
  ModalityFilter$inboundSchema,
  ModalityFilter$Outbound,
  ModalityFilter$outboundSchema,
} from "./modalityfilter.js";
import {
  ModelType,
  ModelType$inboundSchema,
  ModelType$outboundSchema,
} from "./modeltype.js";
import {
  MultimodalCapability,
  MultimodalCapability$inboundSchema,
  MultimodalCapability$outboundSchema,
} from "./multimodalcapability.js";
import {
  NodeNameFilter,
  NodeNameFilter$inboundSchema,
  NodeNameFilter$Outbound,
  NodeNameFilter$outboundSchema,
} from "./nodenamefilter.js";
import {
  OutputTypeEnum,
  OutputTypeEnum$inboundSchema,
  OutputTypeEnum$outboundSchema,
} from "./outputtypeenum.js";
import {
  RollUpMethodDisplayOptions,
  RollUpMethodDisplayOptions$inboundSchema,
  RollUpMethodDisplayOptions$outboundSchema,
} from "./rollupmethoddisplayoptions.js";
import {
  RollUpStrategy,
  RollUpStrategy$inboundSchema,
  RollUpStrategy$outboundSchema,
} from "./rollupstrategy.js";
import {
  ScorerTypes,
  ScorerTypes$inboundSchema,
  ScorerTypes$outboundSchema,
} from "./scorertypes.js";

export type RuntimeScorerConfigFilter =
  | MetadataFilter
  | ModalityFilter
  | NodeNameFilter
  | discriminatedUnionTypes.Unknown<"name">;

export type RuntimeScorerConfigClassNameToVocabIx = {
  [k: string]: Array<number>;
} | { [k: string]: number };

/**
 * Hydrated scorer config used at runtime. Never persisted directly.
 *
 * @remarks
 *
 * Produced by hydrate_scorer_config from a StoredScorerConfig + live DB rows.
 */
export type RuntimeScorerConfig = {
  id: string;
  scorerVersionId?: string | null | undefined;
  /**
   * List of filters to apply to the scorer.
   */
  filters?:
    | Array<
      | MetadataFilter
      | ModalityFilter
      | NodeNameFilter
      | discriminatedUnionTypes.Unknown<"name">
    >
    | null
    | undefined;
  rollUpMethod?: RollUpMethodDisplayOptions | null | undefined;
  name?: string | null | undefined;
  scorerType?: ScorerTypes | null | undefined;
  modelName?: string | null | undefined;
  numJudges?: number | null | undefined;
  /**
   * ScorerVersion to use for this scorer. If not provided, the latest version will be used.
   */
  scorerVersion?: BaseScorerVersionDB | null | undefined;
  /**
   * List of node types that can be scored by this scorer. Defaults to llm/chat.
   */
  scoreableNodeTypes?: Array<string> | null | undefined;
  /**
   * Whether to enable chain of thought for this scorer. Defaults to False for llm scorers.
   */
  cotEnabled?: boolean | null | undefined;
  /**
   * What type of output to use for model-based scorers (boolean, categorical, etc.).
   */
  outputType?: OutputTypeEnum | null | undefined;
  /**
   * What type of input to use for model-based scorers (sessions_normalized, trace_io_only, etc..).
   */
  inputType?: InputTypeEnum | null | undefined;
  /**
   * Multimodal capabilities which this scorer can utilize in its evaluation.
   */
  multimodalCapabilities?: Array<MultimodalCapability> | null | undefined;
  rollUpConfig?: BaseMetricRollUpConfigDB | null | undefined;
  /**
   * Return type of code scorers (e.g., 'bool', 'int', 'float', 'str').
   */
  scoreType?: string | null | undefined;
  modelType?: ModelType | null | undefined;
  chainpollTemplate?: ChainPollTemplate | null | undefined;
  metricName?: string | null | undefined;
  scorerPathName?: string | null | undefined;
  userCode?: string | null | undefined;
  registeredScorerId?: string | null | undefined;
  modelAlias?: string | null | undefined;
  groundTruth?: boolean | undefined;
  requiresToolsInLlmSpan?: boolean | undefined;
  defaultModelAlias?: string | null | undefined;
  rollUpStrategy?: RollUpStrategy | null | undefined;
  requiredScorers?: Array<string> | null | undefined;
  requiredMetricIds?: Array<string> | null | undefined;
  prompt?: string | null | undefined;
  loraTaskId?: number | null | undefined;
  loraWeightsPath?: string | null | undefined;
  lunaInputType?: LunaInputTypeEnum | null | undefined;
  lunaOutputType?: LunaOutputTypeEnum | null | undefined;
  classNameToVocabIx?:
    | { [k: string]: Array<number> }
    | { [k: string]: number }
    | null
    | undefined;
};

/** @internal */
export const RuntimeScorerConfigFilter$inboundSchema: z.ZodMiniType<
  RuntimeScorerConfigFilter,
  unknown
> = discriminatedUnion("name", {
  metadata: MetadataFilter$inboundSchema,
  modality: ModalityFilter$inboundSchema,
  node_name: NodeNameFilter$inboundSchema,
});
/** @internal */
export type RuntimeScorerConfigFilter$Outbound =
  | MetadataFilter$Outbound
  | ModalityFilter$Outbound
  | NodeNameFilter$Outbound;

/** @internal */
export const RuntimeScorerConfigFilter$outboundSchema: z.ZodMiniType<
  RuntimeScorerConfigFilter$Outbound,
  RuntimeScorerConfigFilter
> = z.union([
  MetadataFilter$outboundSchema,
  ModalityFilter$outboundSchema,
  NodeNameFilter$outboundSchema,
]);

export function runtimeScorerConfigFilterToJSON(
  runtimeScorerConfigFilter: RuntimeScorerConfigFilter,
): string {
  return JSON.stringify(
    RuntimeScorerConfigFilter$outboundSchema.parse(runtimeScorerConfigFilter),
  );
}
export function runtimeScorerConfigFilterFromJSON(
  jsonString: string,
): SafeParseResult<RuntimeScorerConfigFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RuntimeScorerConfigFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RuntimeScorerConfigFilter' from JSON`,
  );
}

/** @internal */
export const RuntimeScorerConfigClassNameToVocabIx$inboundSchema: z.ZodMiniType<
  RuntimeScorerConfigClassNameToVocabIx,
  unknown
> = smartUnion([
  z.record(z.string(), z.array(types.number())),
  z.record(z.string(), types.number()),
]);
/** @internal */
export type RuntimeScorerConfigClassNameToVocabIx$Outbound = {
  [k: string]: Array<number>;
} | { [k: string]: number };

/** @internal */
export const RuntimeScorerConfigClassNameToVocabIx$outboundSchema:
  z.ZodMiniType<
    RuntimeScorerConfigClassNameToVocabIx$Outbound,
    RuntimeScorerConfigClassNameToVocabIx
  > = smartUnion([
    z.record(z.string(), z.array(z.int())),
    z.record(z.string(), z.int()),
  ]);

export function runtimeScorerConfigClassNameToVocabIxToJSON(
  runtimeScorerConfigClassNameToVocabIx: RuntimeScorerConfigClassNameToVocabIx,
): string {
  return JSON.stringify(
    RuntimeScorerConfigClassNameToVocabIx$outboundSchema.parse(
      runtimeScorerConfigClassNameToVocabIx,
    ),
  );
}
export function runtimeScorerConfigClassNameToVocabIxFromJSON(
  jsonString: string,
): SafeParseResult<RuntimeScorerConfigClassNameToVocabIx, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RuntimeScorerConfigClassNameToVocabIx$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RuntimeScorerConfigClassNameToVocabIx' from JSON`,
  );
}

/** @internal */
export const RuntimeScorerConfig$inboundSchema: z.ZodMiniType<
  RuntimeScorerConfig,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    scorer_version_id: z.optional(z.nullable(types.string())),
    filters: z.optional(
      z.nullable(
        z.array(
          discriminatedUnion("name", {
            metadata: MetadataFilter$inboundSchema,
            modality: ModalityFilter$inboundSchema,
            node_name: NodeNameFilter$inboundSchema,
          }),
        ),
      ),
    ),
    roll_up_method: z.optional(
      z.nullable(RollUpMethodDisplayOptions$inboundSchema),
    ),
    name: z.optional(z.nullable(types.string())),
    scorer_type: z.optional(z.nullable(ScorerTypes$inboundSchema)),
    model_name: z.optional(z.nullable(types.string())),
    num_judges: z.optional(z.nullable(types.number())),
    scorer_version: z.optional(z.nullable(BaseScorerVersionDB$inboundSchema)),
    scoreable_node_types: z.optional(z.nullable(z.array(types.string()))),
    cot_enabled: z.optional(z.nullable(types.boolean())),
    output_type: z.optional(z.nullable(OutputTypeEnum$inboundSchema)),
    input_type: z.optional(z.nullable(InputTypeEnum$inboundSchema)),
    multimodal_capabilities: z.optional(
      z.nullable(z.array(MultimodalCapability$inboundSchema)),
    ),
    roll_up_config: z.optional(
      z.nullable(BaseMetricRollUpConfigDB$inboundSchema),
    ),
    score_type: z.optional(z.nullable(types.string())),
    model_type: z.optional(z.nullable(ModelType$inboundSchema)),
    chainpoll_template: z.optional(z.nullable(ChainPollTemplate$inboundSchema)),
    metric_name: z.optional(z.nullable(types.string())),
    scorer_path_name: z.optional(z.nullable(types.string())),
    user_code: z.optional(z.nullable(types.string())),
    registered_scorer_id: z.optional(z.nullable(types.string())),
    model_alias: z.optional(z.nullable(types.string())),
    ground_truth: z._default(types.boolean(), false),
    requires_tools_in_llm_span: z._default(types.boolean(), false),
    default_model_alias: z.optional(z.nullable(types.string())),
    roll_up_strategy: z.optional(z.nullable(RollUpStrategy$inboundSchema)),
    required_scorers: z.optional(z.nullable(z.array(types.string()))),
    required_metric_ids: z.optional(z.nullable(z.array(types.string()))),
    prompt: z.optional(z.nullable(types.string())),
    lora_task_id: z.optional(z.nullable(types.number())),
    lora_weights_path: z.optional(z.nullable(types.string())),
    luna_input_type: z.optional(z.nullable(LunaInputTypeEnum$inboundSchema)),
    luna_output_type: z.optional(z.nullable(LunaOutputTypeEnum$inboundSchema)),
    class_name_to_vocab_ix: z.optional(
      z.nullable(
        smartUnion([
          z.record(z.string(), z.array(types.number())),
          z.record(z.string(), types.number()),
        ]),
      ),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "scorer_version_id": "scorerVersionId",
      "roll_up_method": "rollUpMethod",
      "scorer_type": "scorerType",
      "model_name": "modelName",
      "num_judges": "numJudges",
      "scorer_version": "scorerVersion",
      "scoreable_node_types": "scoreableNodeTypes",
      "cot_enabled": "cotEnabled",
      "output_type": "outputType",
      "input_type": "inputType",
      "multimodal_capabilities": "multimodalCapabilities",
      "roll_up_config": "rollUpConfig",
      "score_type": "scoreType",
      "model_type": "modelType",
      "chainpoll_template": "chainpollTemplate",
      "metric_name": "metricName",
      "scorer_path_name": "scorerPathName",
      "user_code": "userCode",
      "registered_scorer_id": "registeredScorerId",
      "model_alias": "modelAlias",
      "ground_truth": "groundTruth",
      "requires_tools_in_llm_span": "requiresToolsInLlmSpan",
      "default_model_alias": "defaultModelAlias",
      "roll_up_strategy": "rollUpStrategy",
      "required_scorers": "requiredScorers",
      "required_metric_ids": "requiredMetricIds",
      "lora_task_id": "loraTaskId",
      "lora_weights_path": "loraWeightsPath",
      "luna_input_type": "lunaInputType",
      "luna_output_type": "lunaOutputType",
      "class_name_to_vocab_ix": "classNameToVocabIx",
    });
  }),
);
/** @internal */
export type RuntimeScorerConfig$Outbound = {
  id: string;
  scorer_version_id?: string | null | undefined;
  filters?:
    | Array<
      | MetadataFilter$Outbound
      | ModalityFilter$Outbound
      | NodeNameFilter$Outbound
    >
    | null
    | undefined;
  roll_up_method?: string | null | undefined;
  name?: string | null | undefined;
  scorer_type?: string | null | undefined;
  model_name?: string | null | undefined;
  num_judges?: number | null | undefined;
  scorer_version?: BaseScorerVersionDB$Outbound | null | undefined;
  scoreable_node_types?: Array<string> | null | undefined;
  cot_enabled?: boolean | null | undefined;
  output_type?: string | null | undefined;
  input_type?: string | null | undefined;
  multimodal_capabilities?: Array<string> | null | undefined;
  roll_up_config?: BaseMetricRollUpConfigDB$Outbound | null | undefined;
  score_type?: string | null | undefined;
  model_type?: string | null | undefined;
  chainpoll_template?: ChainPollTemplate$Outbound | null | undefined;
  metric_name?: string | null | undefined;
  scorer_path_name?: string | null | undefined;
  user_code?: string | null | undefined;
  registered_scorer_id?: string | null | undefined;
  model_alias?: string | null | undefined;
  ground_truth: boolean;
  requires_tools_in_llm_span: boolean;
  default_model_alias?: string | null | undefined;
  roll_up_strategy?: string | null | undefined;
  required_scorers?: Array<string> | null | undefined;
  required_metric_ids?: Array<string> | null | undefined;
  prompt?: string | null | undefined;
  lora_task_id?: number | null | undefined;
  lora_weights_path?: string | null | undefined;
  luna_input_type?: string | null | undefined;
  luna_output_type?: string | null | undefined;
  class_name_to_vocab_ix?:
    | { [k: string]: Array<number> }
    | { [k: string]: number }
    | null
    | undefined;
};

/** @internal */
export const RuntimeScorerConfig$outboundSchema: z.ZodMiniType<
  RuntimeScorerConfig$Outbound,
  RuntimeScorerConfig
> = z.pipe(
  z.object({
    id: z.string(),
    scorerVersionId: z.optional(z.nullable(z.string())),
    filters: z.optional(
      z.nullable(
        z.array(
          z.union([
            MetadataFilter$outboundSchema,
            ModalityFilter$outboundSchema,
            NodeNameFilter$outboundSchema,
          ]),
        ),
      ),
    ),
    rollUpMethod: z.optional(
      z.nullable(RollUpMethodDisplayOptions$outboundSchema),
    ),
    name: z.optional(z.nullable(z.string())),
    scorerType: z.optional(z.nullable(ScorerTypes$outboundSchema)),
    modelName: z.optional(z.nullable(z.string())),
    numJudges: z.optional(z.nullable(z.int())),
    scorerVersion: z.optional(z.nullable(BaseScorerVersionDB$outboundSchema)),
    scoreableNodeTypes: z.optional(z.nullable(z.array(z.string()))),
    cotEnabled: z.optional(z.nullable(z.boolean())),
    outputType: z.optional(z.nullable(OutputTypeEnum$outboundSchema)),
    inputType: z.optional(z.nullable(InputTypeEnum$outboundSchema)),
    multimodalCapabilities: z.optional(
      z.nullable(z.array(MultimodalCapability$outboundSchema)),
    ),
    rollUpConfig: z.optional(
      z.nullable(BaseMetricRollUpConfigDB$outboundSchema),
    ),
    scoreType: z.optional(z.nullable(z.string())),
    modelType: z.optional(z.nullable(ModelType$outboundSchema)),
    chainpollTemplate: z.optional(z.nullable(ChainPollTemplate$outboundSchema)),
    metricName: z.optional(z.nullable(z.string())),
    scorerPathName: z.optional(z.nullable(z.string())),
    userCode: z.optional(z.nullable(z.string())),
    registeredScorerId: z.optional(z.nullable(z.string())),
    modelAlias: z.optional(z.nullable(z.string())),
    groundTruth: z._default(z.boolean(), false),
    requiresToolsInLlmSpan: z._default(z.boolean(), false),
    defaultModelAlias: z.optional(z.nullable(z.string())),
    rollUpStrategy: z.optional(z.nullable(RollUpStrategy$outboundSchema)),
    requiredScorers: z.optional(z.nullable(z.array(z.string()))),
    requiredMetricIds: z.optional(z.nullable(z.array(z.string()))),
    prompt: z.optional(z.nullable(z.string())),
    loraTaskId: z.optional(z.nullable(z.int())),
    loraWeightsPath: z.optional(z.nullable(z.string())),
    lunaInputType: z.optional(z.nullable(LunaInputTypeEnum$outboundSchema)),
    lunaOutputType: z.optional(z.nullable(LunaOutputTypeEnum$outboundSchema)),
    classNameToVocabIx: z.optional(
      z.nullable(
        smartUnion([
          z.record(z.string(), z.array(z.int())),
          z.record(z.string(), z.int()),
        ]),
      ),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      scorerVersionId: "scorer_version_id",
      rollUpMethod: "roll_up_method",
      scorerType: "scorer_type",
      modelName: "model_name",
      numJudges: "num_judges",
      scorerVersion: "scorer_version",
      scoreableNodeTypes: "scoreable_node_types",
      cotEnabled: "cot_enabled",
      outputType: "output_type",
      inputType: "input_type",
      multimodalCapabilities: "multimodal_capabilities",
      rollUpConfig: "roll_up_config",
      scoreType: "score_type",
      modelType: "model_type",
      chainpollTemplate: "chainpoll_template",
      metricName: "metric_name",
      scorerPathName: "scorer_path_name",
      userCode: "user_code",
      registeredScorerId: "registered_scorer_id",
      modelAlias: "model_alias",
      groundTruth: "ground_truth",
      requiresToolsInLlmSpan: "requires_tools_in_llm_span",
      defaultModelAlias: "default_model_alias",
      rollUpStrategy: "roll_up_strategy",
      requiredScorers: "required_scorers",
      requiredMetricIds: "required_metric_ids",
      loraTaskId: "lora_task_id",
      loraWeightsPath: "lora_weights_path",
      lunaInputType: "luna_input_type",
      lunaOutputType: "luna_output_type",
      classNameToVocabIx: "class_name_to_vocab_ix",
    });
  }),
);

export function runtimeScorerConfigToJSON(
  runtimeScorerConfig: RuntimeScorerConfig,
): string {
  return JSON.stringify(
    RuntimeScorerConfig$outboundSchema.parse(runtimeScorerConfig),
  );
}
export function runtimeScorerConfigFromJSON(
  jsonString: string,
): SafeParseResult<RuntimeScorerConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RuntimeScorerConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RuntimeScorerConfig' from JSON`,
  );
}
