/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d3fbb8a341dd
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smartUnion.js";

export const ScorerMultimodalCapabilitiesFilterOperator = {
  Eq: "eq",
  Contains: "contains",
  OneOf: "one_of",
  NotIn: "not_in",
} as const;
export type ScorerMultimodalCapabilitiesFilterOperator = ClosedEnum<
  typeof ScorerMultimodalCapabilitiesFilterOperator
>;

export type ScorerMultimodalCapabilitiesFilterValue = string | Array<string>;

/**
 * Filter scorers by multimodal_capabilities.
 *
 * @remarks
 *
 * Use operator ``contains`` to match scorers that support a single capability
 * (e.g. ``{"name": "multimodal_capabilities", "operator": "contains", "value": "vision"}``).
 * Use ``one_of`` to match scorers whose capabilities include ANY of the given
 * values (e.g. ``{"name": "multimodal_capabilities", "operator": "one_of", "value": ["vision", "audio"]}``).
 */
export type ScorerMultimodalCapabilitiesFilter = {
  name: "multimodal_capabilities";
  operator: ScorerMultimodalCapabilitiesFilterOperator;
  value: string | Array<string>;
  caseSensitive?: boolean | undefined;
};

/** @internal */
export const ScorerMultimodalCapabilitiesFilterOperator$outboundSchema:
  z.ZodMiniEnum<typeof ScorerMultimodalCapabilitiesFilterOperator> = z.enum(
    ScorerMultimodalCapabilitiesFilterOperator,
  );

/** @internal */
export type ScorerMultimodalCapabilitiesFilterValue$Outbound =
  | string
  | Array<string>;

/** @internal */
export const ScorerMultimodalCapabilitiesFilterValue$outboundSchema:
  z.ZodMiniType<
    ScorerMultimodalCapabilitiesFilterValue$Outbound,
    ScorerMultimodalCapabilitiesFilterValue
  > = smartUnion([z.string(), z.array(z.string())]);

export function scorerMultimodalCapabilitiesFilterValueToJSON(
  scorerMultimodalCapabilitiesFilterValue:
    ScorerMultimodalCapabilitiesFilterValue,
): string {
  return JSON.stringify(
    ScorerMultimodalCapabilitiesFilterValue$outboundSchema.parse(
      scorerMultimodalCapabilitiesFilterValue,
    ),
  );
}

/** @internal */
export type ScorerMultimodalCapabilitiesFilter$Outbound = {
  name: "multimodal_capabilities";
  operator: string;
  value: string | Array<string>;
  case_sensitive: boolean;
};

/** @internal */
export const ScorerMultimodalCapabilitiesFilter$outboundSchema: z.ZodMiniType<
  ScorerMultimodalCapabilitiesFilter$Outbound,
  ScorerMultimodalCapabilitiesFilter
> = z.pipe(
  z.object({
    name: z.literal("multimodal_capabilities"),
    operator: ScorerMultimodalCapabilitiesFilterOperator$outboundSchema,
    value: smartUnion([z.string(), z.array(z.string())]),
    caseSensitive: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      caseSensitive: "case_sensitive",
    });
  }),
);

export function scorerMultimodalCapabilitiesFilterToJSON(
  scorerMultimodalCapabilitiesFilter: ScorerMultimodalCapabilitiesFilter,
): string {
  return JSON.stringify(
    ScorerMultimodalCapabilitiesFilter$outboundSchema.parse(
      scorerMultimodalCapabilitiesFilter,
    ),
  );
}
