/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ScoreAggregate = {
  feedbackType: "score";
  average: number;
  unratedCount: number;
};

/** @internal */
export const ScoreAggregate$inboundSchema: z.ZodMiniType<
  ScoreAggregate,
  unknown
> = z.pipe(
  z.object({
    feedback_type: types.literal("score"),
    average: types.number(),
    unrated_count: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "feedback_type": "feedbackType",
      "unrated_count": "unratedCount",
    });
  }),
);

export function scoreAggregateFromJSON(
  jsonString: string,
): SafeParseResult<ScoreAggregate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScoreAggregate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScoreAggregate' from JSON`,
  );
}
