/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smartUnion.js";

export const ScorerTagsFilterOperator = {
  Eq: "eq",
  Contains: "contains",
  NotIn: "not_in",
} as const;
export type ScorerTagsFilterOperator = ClosedEnum<
  typeof ScorerTagsFilterOperator
>;

export type ScorerTagsFilterValue = string | Array<string>;

export type ScorerTagsFilter = {
  name: "tags";
  operator: ScorerTagsFilterOperator;
  value: string | Array<string>;
  caseSensitive?: boolean | undefined;
};

/** @internal */
export const ScorerTagsFilterOperator$outboundSchema: z.ZodMiniEnum<
  typeof ScorerTagsFilterOperator
> = z.enum(ScorerTagsFilterOperator);

/** @internal */
export type ScorerTagsFilterValue$Outbound = string | Array<string>;

/** @internal */
export const ScorerTagsFilterValue$outboundSchema: z.ZodMiniType<
  ScorerTagsFilterValue$Outbound,
  ScorerTagsFilterValue
> = smartUnion([z.string(), z.array(z.string())]);

export function scorerTagsFilterValueToJSON(
  scorerTagsFilterValue: ScorerTagsFilterValue,
): string {
  return JSON.stringify(
    ScorerTagsFilterValue$outboundSchema.parse(scorerTagsFilterValue),
  );
}

/** @internal */
export type ScorerTagsFilter$Outbound = {
  name: "tags";
  operator: string;
  value: string | Array<string>;
  case_sensitive: boolean;
};

/** @internal */
export const ScorerTagsFilter$outboundSchema: z.ZodMiniType<
  ScorerTagsFilter$Outbound,
  ScorerTagsFilter
> = z.pipe(
  z.object({
    name: z.literal("tags"),
    operator: ScorerTagsFilterOperator$outboundSchema,
    value: smartUnion([z.string(), z.array(z.string())]),
    caseSensitive: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      caseSensitive: "case_sensitive",
    });
  }),
);

export function scorerTagsFilterToJSON(
  scorerTagsFilter: ScorerTagsFilter,
): string {
  return JSON.stringify(
    ScorerTagsFilter$outboundSchema.parse(scorerTagsFilter),
  );
}
