/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4f8befc5d770
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type SelectColumns = {
  columnIds?: Array<string> | undefined;
  includeAllMetrics?: boolean | undefined;
  includeAllFeedback?: boolean | undefined;
};

/** @internal */
export type SelectColumns$Outbound = {
  column_ids?: Array<string> | undefined;
  include_all_metrics: boolean;
  include_all_feedback: boolean;
};

/** @internal */
export const SelectColumns$outboundSchema: z.ZodMiniType<
  SelectColumns$Outbound,
  SelectColumns
> = z.pipe(
  z.object({
    columnIds: z.optional(z.array(z.string())),
    includeAllMetrics: z._default(z.boolean(), false),
    includeAllFeedback: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      columnIds: "column_ids",
      includeAllMetrics: "include_all_metrics",
      includeAllFeedback: "include_all_feedback",
    });
  }),
);

export function selectColumnsToJSON(selectColumns: SelectColumns): string {
  return JSON.stringify(SelectColumns$outboundSchema.parse(selectColumns));
}
