/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9e6de08bbffb
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const StepType = {
  Llm: "llm",
  Retriever: "retriever",
  Tool: "tool",
  Workflow: "workflow",
  Agent: "agent",
  Control: "control",
  Trace: "trace",
  Session: "session",
} as const;
export type StepType = OpenEnum<typeof StepType>;

/** @internal */
export const StepType$inboundSchema: z.ZodMiniType<StepType, unknown> =
  openEnums.inboundSchema(StepType);
