/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b231432e8764
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Configuration for dataset examples in synthetic data generation.
 */
export type SyntheticDataSourceDataset = {
  datasetId: string;
  datasetVersionIndex?: number | null | undefined;
  rowIds?: Array<string> | null | undefined;
};

/** @internal */
export type SyntheticDataSourceDataset$Outbound = {
  dataset_id: string;
  dataset_version_index?: number | null | undefined;
  row_ids?: Array<string> | null | undefined;
};

/** @internal */
export const SyntheticDataSourceDataset$outboundSchema: z.ZodMiniType<
  SyntheticDataSourceDataset$Outbound,
  SyntheticDataSourceDataset
> = z.pipe(
  z.object({
    datasetId: z.string(),
    datasetVersionIndex: z.optional(z.nullable(z.int())),
    rowIds: z.optional(z.nullable(z.array(z.string()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      datasetId: "dataset_id",
      datasetVersionIndex: "dataset_version_index",
      rowIds: "row_ids",
    });
  }),
);

export function syntheticDataSourceDatasetToJSON(
  syntheticDataSourceDataset: SyntheticDataSourceDataset,
): string {
  return JSON.stringify(
    SyntheticDataSourceDataset$outboundSchema.parse(syntheticDataSourceDataset),
  );
}
