/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 08dcf41793fc
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type TreeChoiceRating = {
  feedbackType: "tree_choice";
  value: string;
};

/** @internal */
export const TreeChoiceRating$inboundSchema: z.ZodMiniType<
  TreeChoiceRating,
  unknown
> = z.pipe(
  z.object({
    feedback_type: types.literal("tree_choice"),
    value: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "feedback_type": "feedbackType",
    });
  }),
);

export function treeChoiceRatingFromJSON(
  jsonString: string,
): SafeParseResult<TreeChoiceRating, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TreeChoiceRating$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TreeChoiceRating' from JSON`,
  );
}
