/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 06751fdaabcf
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ValidateLLMScorerDatasetResponse = {
  metricsExperimentId: string;
  projectId: string;
};

/** @internal */
export const ValidateLLMScorerDatasetResponse$inboundSchema: z.ZodMiniType<
  ValidateLLMScorerDatasetResponse,
  unknown
> = z.pipe(
  z.object({
    metrics_experiment_id: types.string(),
    project_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "metrics_experiment_id": "metricsExperimentId",
      "project_id": "projectId",
    });
  }),
);

export function validateLLMScorerDatasetResponseFromJSON(
  jsonString: string,
): SafeParseResult<ValidateLLMScorerDatasetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ValidateLLMScorerDatasetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ValidateLLMScorerDatasetResponse' from JSON`,
  );
}
