/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c366f3a44c65
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ChainPollTemplate,
  ChainPollTemplate$Outbound,
  ChainPollTemplate$outboundSchema,
} from "./chainpolltemplate.js";
import {
  FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType,
  FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType$Outbound,
  FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType$outboundSchema,
} from "./filterexpressionannotatedunionlogrecordsidfilterlogrecordsdatefilterlogrecordsnumberfilterlogrecordsbooleanfilterlogrecordscollectionfilterlogrecordstextfilterfieldinfoannotationnonetyperequiredtruediscriminatortype.js";
import {
  GeneratedScorerConfiguration,
  GeneratedScorerConfiguration$Outbound,
  GeneratedScorerConfiguration$outboundSchema,
} from "./generatedscorerconfiguration.js";
import {
  LogRecordsBooleanFilter,
  LogRecordsBooleanFilter$Outbound,
  LogRecordsBooleanFilter$outboundSchema,
} from "./logrecordsbooleanfilter.js";
import {
  LogRecordsCollectionFilter,
  LogRecordsCollectionFilter$Outbound,
  LogRecordsCollectionFilter$outboundSchema,
} from "./logrecordscollectionfilter.js";
import {
  LogRecordsDateFilter,
  LogRecordsDateFilter$Outbound,
  LogRecordsDateFilter$outboundSchema,
} from "./logrecordsdatefilter.js";
import {
  LogRecordsIDFilter,
  LogRecordsIDFilter$Outbound,
  LogRecordsIDFilter$outboundSchema,
} from "./logrecordsidfilter.js";
import {
  LogRecordsNumberFilter,
  LogRecordsNumberFilter$Outbound,
  LogRecordsNumberFilter$outboundSchema,
} from "./logrecordsnumberfilter.js";
import {
  LogRecordsSortClause,
  LogRecordsSortClause$Outbound,
  LogRecordsSortClause$outboundSchema,
} from "./logrecordssortclause.js";
import {
  LogRecordsTextFilter,
  LogRecordsTextFilter$Outbound,
  LogRecordsTextFilter$outboundSchema,
} from "./logrecordstextfilter.js";

export type ValidateLLMScorerLogRecordRequestFilter =
  | LogRecordsBooleanFilter
  | LogRecordsCollectionFilter
  | LogRecordsDateFilter
  | LogRecordsIDFilter
  | LogRecordsNumberFilter
  | LogRecordsTextFilter;

/**
 * Request to validate a new LLM scorer based on a log record.
 *
 * @remarks
 * This is used to create a new experiment with the copied log records to store the metric testing results.
 */
export type ValidateLLMScorerLogRecordRequest = {
  startingToken?: number | undefined;
  limit?: number | undefined;
  previousLastRowId?: string | null | undefined;
  /**
   * Log stream id associated with the traces.
   */
  logStreamId?: string | null | undefined;
  /**
   * Experiment id associated with the traces.
   */
  experimentId?: string | null | undefined;
  /**
   * Metrics testing id associated with the traces.
   */
  metricsTestingId?: string | null | undefined;
  filters?:
    | Array<
      | LogRecordsBooleanFilter
      | LogRecordsCollectionFilter
      | LogRecordsDateFilter
      | LogRecordsIDFilter
      | LogRecordsNumberFilter
      | LogRecordsTextFilter
    >
    | undefined;
  filterTree?:
    | FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType
    | null
    | undefined;
  /**
   * Sort for the query.  Defaults to native sort (created_at, id descending).
   */
  sort?: LogRecordsSortClause | null | undefined;
  truncateFields?: boolean | undefined;
  /**
   * If True, include computed child counts (e.g., num_traces for sessions, num_spans for traces).
   */
  includeCounts?: boolean | undefined;
  query: string;
  response: string;
  /**
   * Template for a chainpoll metric prompt,
   *
   * @remarks
   * containing all the info necessary to send a chainpoll prompt.
   */
  chainPollTemplate: ChainPollTemplate;
  scorerConfiguration: GeneratedScorerConfiguration;
  userPrompt: string;
};

/** @internal */
export type ValidateLLMScorerLogRecordRequestFilter$Outbound =
  | LogRecordsBooleanFilter$Outbound
  | LogRecordsCollectionFilter$Outbound
  | LogRecordsDateFilter$Outbound
  | LogRecordsIDFilter$Outbound
  | LogRecordsNumberFilter$Outbound
  | LogRecordsTextFilter$Outbound;

/** @internal */
export const ValidateLLMScorerLogRecordRequestFilter$outboundSchema:
  z.ZodMiniType<
    ValidateLLMScorerLogRecordRequestFilter$Outbound,
    ValidateLLMScorerLogRecordRequestFilter
  > = z.union([
    LogRecordsBooleanFilter$outboundSchema,
    LogRecordsCollectionFilter$outboundSchema,
    LogRecordsDateFilter$outboundSchema,
    LogRecordsIDFilter$outboundSchema,
    LogRecordsNumberFilter$outboundSchema,
    LogRecordsTextFilter$outboundSchema,
  ]);

export function validateLLMScorerLogRecordRequestFilterToJSON(
  validateLLMScorerLogRecordRequestFilter:
    ValidateLLMScorerLogRecordRequestFilter,
): string {
  return JSON.stringify(
    ValidateLLMScorerLogRecordRequestFilter$outboundSchema.parse(
      validateLLMScorerLogRecordRequestFilter,
    ),
  );
}

/** @internal */
export type ValidateLLMScorerLogRecordRequest$Outbound = {
  starting_token: number;
  limit: number;
  previous_last_row_id?: string | null | undefined;
  log_stream_id?: string | null | undefined;
  experiment_id?: string | null | undefined;
  metrics_testing_id?: string | null | undefined;
  filters?:
    | Array<
      | LogRecordsBooleanFilter$Outbound
      | LogRecordsCollectionFilter$Outbound
      | LogRecordsDateFilter$Outbound
      | LogRecordsIDFilter$Outbound
      | LogRecordsNumberFilter$Outbound
      | LogRecordsTextFilter$Outbound
    >
    | undefined;
  filter_tree?:
    | FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType$Outbound
    | null
    | undefined;
  sort?: LogRecordsSortClause$Outbound | null | undefined;
  truncate_fields: boolean;
  include_counts: boolean;
  query: string;
  response: string;
  chain_poll_template: ChainPollTemplate$Outbound;
  scorer_configuration: GeneratedScorerConfiguration$Outbound;
  user_prompt: string;
};

/** @internal */
export const ValidateLLMScorerLogRecordRequest$outboundSchema: z.ZodMiniType<
  ValidateLLMScorerLogRecordRequest$Outbound,
  ValidateLLMScorerLogRecordRequest
> = z.pipe(
  z.object({
    startingToken: z._default(z.int(), 0),
    limit: z._default(z.int(), 100),
    previousLastRowId: z.optional(z.nullable(z.string())),
    logStreamId: z.optional(z.nullable(z.string())),
    experimentId: z.optional(z.nullable(z.string())),
    metricsTestingId: z.optional(z.nullable(z.string())),
    filters: z.optional(
      z.array(
        z.union([
          LogRecordsBooleanFilter$outboundSchema,
          LogRecordsCollectionFilter$outboundSchema,
          LogRecordsDateFilter$outboundSchema,
          LogRecordsIDFilter$outboundSchema,
          LogRecordsNumberFilter$outboundSchema,
          LogRecordsTextFilter$outboundSchema,
        ]),
      ),
    ),
    filterTree: z.optional(
      z.nullable(
        FilterExpressionAnnotatedUnionLogRecordsIDFilterLogRecordsDateFilterLogRecordsNumberFilterLogRecordsBooleanFilterLogRecordsCollectionFilterLogRecordsTextFilterFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorType$outboundSchema,
      ),
    ),
    sort: z.optional(z.nullable(LogRecordsSortClause$outboundSchema)),
    truncateFields: z._default(z.boolean(), false),
    includeCounts: z._default(z.boolean(), false),
    query: z.string(),
    response: z.string(),
    chainPollTemplate: ChainPollTemplate$outboundSchema,
    scorerConfiguration: GeneratedScorerConfiguration$outboundSchema,
    userPrompt: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      startingToken: "starting_token",
      previousLastRowId: "previous_last_row_id",
      logStreamId: "log_stream_id",
      experimentId: "experiment_id",
      metricsTestingId: "metrics_testing_id",
      filterTree: "filter_tree",
      truncateFields: "truncate_fields",
      includeCounts: "include_counts",
      chainPollTemplate: "chain_poll_template",
      scorerConfiguration: "scorer_configuration",
      userPrompt: "user_prompt",
    });
  }),
);

export function validateLLMScorerLogRecordRequestToJSON(
  validateLLMScorerLogRecordRequest: ValidateLLMScorerLogRecordRequest,
): string {
  return JSON.stringify(
    ValidateLLMScorerLogRecordRequest$outboundSchema.parse(
      validateLLMScorerLogRecordRequest,
    ),
  );
}
