/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c30c36dce621
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type WriterIntegration = {
  organizationId: string;
  id?: string | null | undefined;
  name: "writer";
  extra?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const WriterIntegration$inboundSchema: z.ZodMiniType<
  WriterIntegration,
  unknown
> = z.pipe(
  z.object({
    organization_id: types.string(),
    id: z.optional(z.nullable(types.string())),
    name: types.literal("writer"),
    extra: z.optional(z.nullable(z.record(z.string(), z.any()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
    });
  }),
);

export function writerIntegrationFromJSON(
  jsonString: string,
): SafeParseResult<WriterIntegration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WriterIntegration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WriterIntegration' from JSON`,
  );
}
